from datetime import timedelta

TOKEN_MARKER = "dtca_v1"
PREFIX_BYTES = 12
PREFIX_LENGTH = 16
SECRET_BYTES = 32
SECRET_LENGTH = 43
PREFIX_COLLISION_RETRIES = 5
DIGEST_ALGORITHM = "pbkdf2_sha256"
DIGEST_VERSION = 1

DEFAULT_CREDENTIAL_LIFETIME = timedelta(days=30)
MAX_CREDENTIAL_LIFETIME = timedelta(days=90)
DEFAULT_ROTATION_OVERLAP = timedelta(0)
MAX_ROTATION_OVERLAP = timedelta(hours=1)
LAST_USED_WRITE_INTERVAL = timedelta(minutes=15)
IDEMPOTENCY_RETENTION = timedelta(hours=24)
RATE_WINDOW = timedelta(seconds=60)

READ_RATE_LIMIT = 120
WRITE_RATE_LIMIT = 30
ADAPTIVE_RATE_LIMIT = 10
MIN_RATE_COST = 1
MAX_RATE_COST = 10

MAX_JSON_BYTES = 65_536
MAX_JSON_DEPTH = 12
MAX_JSON_NODES = 2_000
MAX_JSON_KEY_LENGTH = 128
DEFAULT_PAGE_SIZE = 20
MAX_PAGE_SIZE = 100
MAX_BULK_ITEMS = 100
MAX_BULK_ERRORS = 100
MAX_IDEMPOTENCY_KEY_BYTES = 512
