# Generated by Django 6.0.7 on 2026-08-09 15:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalEventMapping',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('external_event_identifier', models.CharField(max_length=512)),
                ('canonical_repository', models.CharField(blank=True, max_length=255)),
                ('canonical_revision', models.CharField(blank=True, max_length=64)),
                ('canonical_source_key', models.CharField(blank=True, max_length=512)),
                ('canonical_slug_snapshot', models.SlugField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('review_required', 'Review required'), ('mapped', 'Mapped'), ('excluded', 'Excluded'), ('source_missing', 'Source missing')], max_length=24)),
                ('mapping_set_revision', models.PositiveBigIntegerField()),
                ('reviewer_ref', models.CharField(blank=True, max_length=128)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_historical_event_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('provider', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationAggregateRevision',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eligible_count', models.PositiveBigIntegerField()),
                ('excluded_count', models.PositiveBigIntegerField(default=0)),
                ('quarantined_count', models.PositiveBigIntegerField(default=0)),
                ('coverage_boundary', models.CharField(max_length=128)),
                ('status_policy_version', models.CharField(max_length=32)),
                ('combination_policy', models.CharField(choices=[('additive_disjoint', 'Additive, disjoint'), ('replacement', 'Replacement'), ('exclude', 'Exclude')], max_length=24)),
                ('aggregate_checksum', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('staged', 'Staged'), ('validated', 'Validated'), ('active', 'Active'), ('superseded', 'Superseded'), ('quarantined', 'Quarantined'), ('rolled_back', 'Rolled back')], default='staged', max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_revisions', to='events.historicaleventmapping')),
            ],
            options={
                'ordering': ('source_run_id', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationAggregateSlot',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_repository', models.CharField(max_length=255)),
                ('canonical_revision', models.CharField(max_length=64)),
                ('canonical_source_key', models.CharField(max_length=512)),
                ('canonical_slug_snapshot', models.SlugField(max_length=255)),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('coverage_boundary', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_slot', to='events.historicalregistrationaggregaterevision')),
            ],
            options={
                'ordering': ('canonical_source_key', 'provider', 'coverage_boundary'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationSourceRun',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('adapter_version', models.CharField(max_length=32)),
                ('schema_version', models.CharField(max_length=64)),
                ('whole_source_checksum', models.CharField(max_length=64)),
                ('source_reference_digest', models.CharField(max_length=64)),
                ('manifest_entry_total', models.PositiveIntegerField()),
                ('manifest_event_total', models.PositiveIntegerField()),
                ('parsed_row_total', models.PositiveBigIntegerField()),
                ('eligible_row_total', models.PositiveBigIntegerField()),
                ('excluded_row_total', models.PositiveBigIntegerField()),
                ('quarantined_event_total', models.PositiveIntegerField(default=0)),
                ('status_totals', models.JSONField(default=dict)),
                ('state_totals', models.JSONField(default=dict)),
                ('reason_codes', models.JSONField(default=list)),
                ('mapping_set_revision', models.PositiveBigIntegerField()),
                ('policy_version', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('staged', 'Staged'), ('validated', 'Validated'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('rolled_back', 'Rolled back'), ('quarantined', 'Quarantined')], default='staged', max_length=16)),
                ('actor_ref', models.CharField(blank=True, max_length=128)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_registration_source_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'permissions': (('historical_registration_import_manage', 'Can manage historical registration aggregate imports'), ('historical_registration_mapping_manage', 'Can manage historical event mappings')),
            },
        ),
        migrations.AddField(
            model_name='historicalregistrationaggregaterevision',
            name='source_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_revisions', to='events.historicalregistrationsourcerun'),
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationTotalState',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_repository', models.CharField(max_length=255)),
                ('canonical_revision', models.CharField(max_length=64)),
                ('canonical_source_key', models.CharField(max_length=512)),
                ('canonical_slug_snapshot', models.SlugField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('canonical_repository', 'canonical_revision', 'canonical_source_key'), name='events_hist_total_source_unique'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_hist_total_revision_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='historicaleventmapping',
            index=models.Index(fields=['provider', 'state'], name='events_hist_mapping_state'),
        ),
        migrations.AddIndex(
            model_name='historicaleventmapping',
            index=models.Index(fields=['canonical_repository', 'canonical_revision', 'canonical_source_key'], name='events_hist_mapping_source'),
        ),
        migrations.AddConstraint(
            model_name='historicaleventmapping',
            constraint=models.UniqueConstraint(fields=('provider', 'external_event_identifier'), name='events_hist_mapping_provider_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicaleventmapping',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_hist_mapping_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='historicaleventmapping',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_set_revision__gte', 1)), name='events_hist_mapping_set_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='historicaleventmapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('canonical_repository__gt', ''), ('canonical_revision__gt', ''), ('canonical_slug_snapshot__gt', ''), ('canonical_source_key__gt', ''), ('reviewer_ref__gt', ''), ('state', 'mapped')), models.Q(('reason_code__gt', ''), ('reviewer_ref__gt', ''), ('state', 'excluded')), ('state', 'review_required'), ('state', 'source_missing'), _connector='OR'), name='events_hist_mapping_state_evidence'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationaggregateslot',
            index=models.Index(fields=['canonical_repository', 'canonical_revision', 'canonical_source_key'], name='events_hist_slot_source'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregateslot',
            constraint=models.UniqueConstraint(fields=('canonical_repository', 'canonical_revision', 'canonical_source_key', 'provider', 'coverage_boundary'), name='events_hist_active_slot_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregateslot',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_hist_slot_revision_positive'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationsourcerun',
            index=models.Index(fields=['provider', 'state', '-created_at'], name='events_hist_run_state'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationsourcerun',
            index=models.Index(fields=['whole_source_checksum'], name='events_hist_run_checksum'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.UniqueConstraint(fields=('provider', 'whole_source_checksum', 'schema_version', 'mapping_set_revision', 'policy_version'), name='events_hist_run_replay_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_hist_run_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.CheckConstraint(condition=models.Q(('eligible_row_total__lte', models.F('parsed_row_total'))), name='events_hist_run_eligible_bounded'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.CheckConstraint(condition=models.Q(('excluded_row_total__lte', models.F('parsed_row_total'))), name='events_hist_run_excluded_bounded'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationaggregaterevision',
            index=models.Index(fields=['mapping', 'state', '-created_at'], name='events_hist_agg_state'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationaggregaterevision',
            index=models.Index(fields=['aggregate_checksum'], name='events_hist_agg_checksum'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregaterevision',
            constraint=models.UniqueConstraint(fields=('source_run', 'mapping', 'aggregate_checksum'), name='events_hist_aggregate_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregaterevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_hist_aggregate_revision_positive'),
        ),
    ]
