# Generated by Django 6.0.8 on 2026-09-03 10:32

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('jobs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('public_id', models.PositiveIntegerField(db_index=True, editable=False, null=True, unique=True)),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=255)),
                ('source_repository', models.CharField(max_length=255)),
                ('source_revision', models.CharField(max_length=64)),
                ('source_key', models.CharField(max_length=512)),
                ('source_path', models.CharField(default='', max_length=512)),
                ('source_checksum', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='published', max_length=16)),
            ],
            options={
                'ordering': ('source_key', 'id'),
                'constraints': [models.UniqueConstraint(fields=('source_repository', 'source_revision', 'source_key'), name='events_event_source_identity_unique'), models.CheckConstraint(condition=models.Q(('title__gt', '')), name='events_event_title_nonempty'), models.CheckConstraint(condition=models.Q(('public_id__isnull', True), ('public_id__gt', 0), _connector='OR'), name='events_event_public_id_positive'), models.CheckConstraint(condition=models.Q(('source_repository__gt', ''), ('source_revision__gt', ''), ('source_key__gt', '')), name='events_event_source_identity_nonempty')],
            },
        ),
        migrations.CreateModel(
            name='EventPublicIdSequence',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('next_public_id', models.PositiveIntegerField()),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('id', 1)), name='events_public_id_sequence_singleton'), models.CheckConstraint(condition=models.Q(('next_public_id__gt', 0)), name='events_public_id_sequence_positive')],
            },
        ),
        migrations.CreateModel(
            name='EventQnaRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_digest', models.CharField(max_length=64)),
                ('window_seconds', models.PositiveIntegerField()),
                ('window_started_at', models.DateTimeField()),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['scope_digest', 'window_seconds'], name='events_qna_rate_scope')],
                'constraints': [models.UniqueConstraint(fields=('scope_digest', 'window_seconds', 'window_started_at'), name='events_qna_rate_window_unique')],
            },
        ),
        migrations.CreateModel(
            name='EventQnaSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('listed', models.BooleanField(default=True)),
                ('allow_names', models.BooleanField(default=True)),
                ('require_names', models.BooleanField(default=False)),
                ('answered_placement', models.CharField(choices=[('separate', 'Separate'), ('bottom', 'Bottom'), ('inline', 'Inline')], default='separate', max_length=16)),
                ('default_sort', models.CharField(choices=[('popular', 'Popular'), ('recent', 'Recent')], default='popular', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('retention_days', models.PositiveIntegerField(blank=True, default=365, null=True)),
                ('state_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_delete_at', models.DateTimeField(blank=True, null=True)),
                ('q_total', models.PositiveBigIntegerField(default=0)),
                ('q_answered', models.PositiveBigIntegerField(default=0)),
                ('backend_key', models.CharField(default='native', max_length=32)),
                ('backend_reference', models.CharField(blank=True, max_length=255)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qna_session', to='events.event')),
                ('provisioning_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_provisioning_session', to='jobs.durablejob')),
            ],
            options={
                'ordering': ('event_id', 'id'),
                'permissions': (('view_event_qna', 'Can view event-linked Q&A'), ('manage_event_qna', 'Can manage event-linked Q&A')),
            },
        ),
        migrations.CreateModel(
            name='EventQnaQuestion',
            fields=[
                ('question_id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=315)),
                ('author_name', models.CharField(blank=True, default='', max_length=60)),
                ('participant_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('answered', 'Answered'), ('deleted', 'Deleted')], default='visible', max_length=16)),
                ('score', models.PositiveIntegerField(default=0)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.eventqnasession')),
            ],
            options={
                'ordering': ('-pinned', '-score', 'created_at', 'question_id'),
            },
        ),
        migrations.CreateModel(
            name='EventQnaCohostInvite',
            fields=[
                ('invite_id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=48)),
                ('passcode_digest', models.CharField(max_length=128)),
                ('created_by_ref', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohost_invites', to='events.eventqnasession')),
            ],
            options={
                'ordering': ('name', 'invite_id'),
            },
        ),
        migrations.CreateModel(
            name='EventQnaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.eventqnaquestion')),
            ],
        ),
        migrations.CreateModel(
            name='HistoricalEventMapping',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('external_event_identifier', models.CharField(max_length=512)),
                ('canonical_repository', models.CharField(blank=True, max_length=255)),
                ('canonical_revision', models.CharField(blank=True, max_length=64)),
                ('canonical_source_key', models.CharField(blank=True, max_length=512)),
                ('canonical_slug_snapshot', models.SlugField(blank=True, max_length=255)),
                ('state', models.CharField(choices=[('review_required', 'Review required'), ('mapped', 'Mapped'), ('excluded', 'Excluded'), ('source_missing', 'Source missing')], max_length=24)),
                ('mapping_set_revision', models.PositiveBigIntegerField()),
                ('reviewer_ref', models.CharField(blank=True, max_length=128)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('reason', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_registration_mappings', to='events.event')),
                ('reviewer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_historical_event_mappings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('provider', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationAggregateRevision',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('eligible_count', models.PositiveBigIntegerField()),
                ('excluded_count', models.PositiveBigIntegerField(default=0)),
                ('quarantined_count', models.PositiveBigIntegerField(default=0)),
                ('coverage_boundary', models.CharField(max_length=128)),
                ('status_policy_version', models.CharField(max_length=32)),
                ('combination_policy', models.CharField(choices=[('additive_disjoint', 'Additive, disjoint'), ('replacement', 'Replacement'), ('exclude', 'Exclude')], max_length=24)),
                ('aggregate_checksum', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('staged', 'Staged'), ('validated', 'Validated'), ('active', 'Active'), ('superseded', 'Superseded'), ('quarantined', 'Quarantined'), ('rolled_back', 'Rolled back')], default='staged', max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_revisions', to='events.historicaleventmapping')),
            ],
            options={
                'ordering': ('source_run_id', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationAggregateSlot',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_repository', models.CharField(max_length=255)),
                ('canonical_revision', models.CharField(max_length=64)),
                ('canonical_source_key', models.CharField(max_length=512)),
                ('canonical_slug_snapshot', models.SlugField(max_length=255)),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('coverage_boundary', models.CharField(max_length=128)),
                ('replacement_revision_id', models.UUIDField(blank=True, null=True)),
                ('replacement_eligible_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('replacement_combination_policy', models.CharField(blank=True, choices=[('additive_disjoint', 'Additive, disjoint'), ('replacement', 'Replacement'), ('exclude', 'Exclude')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_slot', to='events.historicalregistrationaggregaterevision')),
            ],
            options={
                'ordering': ('canonical_source_key', 'provider', 'coverage_boundary'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationPointerDisplacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_replacement_revision_id', models.UUIDField(blank=True, null=True)),
                ('row_replacement_eligible_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('row_replacement_combination_policy', models.CharField(blank=True, choices=[('additive_disjoint', 'Additive, disjoint'), ('replacement', 'Replacement'), ('exclude', 'Exclude')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('displaced_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='displaced_by_replacements', to='events.historicalregistrationaggregaterevision')),
                ('replacing_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointer_displacements', to='events.historicalregistrationaggregaterevision')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='displacement_history', to='events.historicalregistrationaggregateslot')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationSourceRun',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('adapter_version', models.CharField(max_length=32)),
                ('schema_version', models.CharField(max_length=64)),
                ('whole_source_checksum', models.CharField(max_length=64)),
                ('source_reference_digest', models.CharField(max_length=64)),
                ('manifest_entry_total', models.PositiveIntegerField()),
                ('manifest_event_total', models.PositiveIntegerField()),
                ('parsed_row_total', models.PositiveBigIntegerField()),
                ('eligible_row_total', models.PositiveBigIntegerField()),
                ('excluded_row_total', models.PositiveBigIntegerField()),
                ('quarantined_event_total', models.PositiveIntegerField(default=0)),
                ('status_totals', models.JSONField(default=dict)),
                ('state_totals', models.JSONField(default=dict)),
                ('reason_codes', models.JSONField(default=list)),
                ('mapping_set_revision', models.PositiveBigIntegerField()),
                ('policy_version', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('staged', 'Staged'), ('validated', 'Validated'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('rolled_back', 'Rolled back'), ('quarantined', 'Quarantined')], default='staged', max_length=16)),
                ('actor_ref', models.CharField(blank=True, max_length=128)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_registration_source_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'permissions': (('historical_registration_import_manage', 'Can manage historical registration aggregate imports'), ('historical_registration_mapping_manage', 'Can manage historical event mappings')),
            },
        ),
        migrations.AddField(
            model_name='historicalregistrationaggregaterevision',
            name='source_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_revisions', to='events.historicalregistrationsourcerun'),
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationTotalState',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_repository', models.CharField(max_length=255)),
                ('canonical_revision', models.CharField(max_length=64)),
                ('canonical_source_key', models.CharField(max_length=512)),
                ('canonical_slug_snapshot', models.SlugField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('canonical_repository', 'canonical_revision', 'canonical_source_key'), name='events_hist_total_source_unique'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_hist_total_revision_positive')],
            },
        ),
        migrations.CreateModel(
            name='EventAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_path', models.CharField(max_length=1024, unique=True)),
                ('kind', models.CharField(choices=[('legacy_date_path', 'Legacy date/title path'), ('legacy_uuid', 'Legacy UUID path'), ('legacy_path', 'Legacy path'), ('title_slug', 'Previous title slug'), ('reviewed', 'Reviewed alias')], max_length=24)),
                ('reason', models.CharField(max_length=255)),
                ('source_repository', models.CharField(max_length=255)),
                ('source_revision', models.CharField(max_length=64)),
                ('source_key', models.CharField(max_length=512)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='events.event')),
            ],
            options={
                'ordering': ('source_path', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('source_path__startswith', '/events/'), models.Q(('source_path__contains', '?'), _negated=True), models.Q(('source_path__contains', '#'), _negated=True)), name='events_alias_path_shape'), models.CheckConstraint(condition=models.Q(('source_repository__gt', ''), ('source_revision__gt', ''), ('source_key__gt', '')), name='events_alias_source_nonempty')],
            },
        ),
        migrations.AddConstraint(
            model_name='eventqnasession',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_qna_session_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='eventqnasession',
            constraint=models.CheckConstraint(condition=models.Q(('backend_key__gt', '')), name='events_qna_session_backend_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='eventqnasession',
            constraint=models.CheckConstraint(condition=models.Q(('q_answered__lte', models.F('q_total'))), name='events_qna_answered_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='eventqnasession',
            constraint=models.CheckConstraint(condition=models.Q(('retention_days__isnull', True), ('retention_days__gte', 1), _connector='OR'), name='events_qna_retention_positive'),
        ),
        migrations.AddIndex(
            model_name='eventqnaquestion',
            index=models.Index(fields=['session', 'status', 'created_at'], name='events_qna_q_status_time'),
        ),
        migrations.AddIndex(
            model_name='eventqnaquestion',
            index=models.Index(fields=['session', 'pinned', 'score'], name='events_qna_q_rank'),
        ),
        migrations.AddConstraint(
            model_name='eventqnaquestion',
            constraint=models.CheckConstraint(condition=models.Q(('text__gt', ''), ('participant_digest__gt', '')), name='events_qna_question_content_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='eventqnaquestion',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='events_qna_question_score_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='eventqnacohostinvite',
            constraint=models.UniqueConstraint(fields=('session', 'name'), name='events_qna_cohost_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='eventqnavote',
            constraint=models.UniqueConstraint(fields=('question', 'participant_digest'), name='events_qna_vote_participant_unique'),
        ),
        migrations.AddIndex(
            model_name='historicaleventmapping',
            index=models.Index(fields=['provider', 'state'], name='events_hist_mapping_state'),
        ),
        migrations.AddIndex(
            model_name='historicaleventmapping',
            index=models.Index(fields=['canonical_repository', 'canonical_revision', 'canonical_source_key'], name='events_hist_mapping_source'),
        ),
        migrations.AddConstraint(
            model_name='historicaleventmapping',
            constraint=models.UniqueConstraint(fields=('provider', 'external_event_identifier'), name='events_hist_mapping_provider_external_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicaleventmapping',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_hist_mapping_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='historicaleventmapping',
            constraint=models.CheckConstraint(condition=models.Q(('mapping_set_revision__gte', 1)), name='events_hist_mapping_set_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='historicaleventmapping',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('canonical_repository__gt', ''), ('canonical_revision__gt', ''), ('canonical_slug_snapshot__gt', ''), ('canonical_source_key__gt', ''), ('reviewer_ref__gt', ''), ('state', 'mapped')), models.Q(('reason_code__gt', ''), ('reviewer_ref__gt', ''), ('state', 'excluded')), ('state', 'review_required'), ('state', 'source_missing'), _connector='OR'), name='events_hist_mapping_state_evidence'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationaggregateslot',
            index=models.Index(fields=['canonical_repository', 'canonical_revision', 'canonical_source_key'], name='events_hist_slot_source'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregateslot',
            constraint=models.UniqueConstraint(fields=('canonical_repository', 'canonical_revision', 'canonical_source_key', 'provider', 'coverage_boundary'), name='events_hist_active_slot_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregateslot',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_hist_slot_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregateslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_revision__isnull', False), ('replacement_combination_policy', ''), ('replacement_eligible_count__isnull', True), ('replacement_revision_id__isnull', True)), models.Q(('active_revision__isnull', True), ('replacement_combination_policy__gt', ''), ('replacement_eligible_count__isnull', False), ('replacement_revision_id__isnull', False)), models.Q(('active_revision__isnull', True), ('replacement_combination_policy', ''), ('replacement_eligible_count__isnull', True), ('replacement_revision_id__isnull', True)), _connector='OR'), name='events_hist_slot_one_pointer'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationpointerdisplacement',
            constraint=models.UniqueConstraint(fields=('replacing_revision', 'slot'), name='events_hist_displacement_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationpointerdisplacement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('displaced_revision__isnull', False), ('row_replacement_combination_policy', ''), ('row_replacement_eligible_count__isnull', True), ('row_replacement_revision_id__isnull', True)), models.Q(('displaced_revision__isnull', True), ('row_replacement_combination_policy__gt', ''), ('row_replacement_eligible_count__isnull', False), ('row_replacement_revision_id__isnull', False)), _connector='OR'), name='events_hist_displacement_one_pointer'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationsourcerun',
            index=models.Index(fields=['provider', 'state', '-created_at'], name='events_hist_run_state'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationsourcerun',
            index=models.Index(fields=['whole_source_checksum'], name='events_hist_run_checksum'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.UniqueConstraint(fields=('provider', 'whole_source_checksum', 'schema_version', 'mapping_set_revision', 'policy_version'), name='events_hist_run_replay_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_hist_run_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.CheckConstraint(condition=models.Q(('eligible_row_total__lte', models.F('parsed_row_total'))), name='events_hist_run_eligible_bounded'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.CheckConstraint(condition=models.Q(('excluded_row_total__lte', models.F('parsed_row_total'))), name='events_hist_run_excluded_bounded'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationaggregaterevision',
            index=models.Index(fields=['mapping', 'state', '-created_at'], name='events_hist_agg_state'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationaggregaterevision',
            index=models.Index(fields=['aggregate_checksum'], name='events_hist_agg_checksum'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregaterevision',
            constraint=models.UniqueConstraint(fields=('source_run', 'mapping', 'aggregate_checksum'), name='events_hist_aggregate_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregaterevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='events_hist_aggregate_revision_positive'),
        ),
    ]
