# Generated by Django 6.0.7 on 2026-08-09 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalregistrationaggregateslot',
            name='replacement_combination_policy',
            field=models.CharField(blank=True, choices=[('additive_disjoint', 'Additive, disjoint'), ('replacement', 'Replacement'), ('exclude', 'Exclude')], max_length=24),
        ),
        migrations.AddField(
            model_name='historicalregistrationaggregateslot',
            name='replacement_eligible_count',
            field=models.PositiveBigIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='historicalregistrationaggregateslot',
            name='replacement_revision_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregateslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_revision__isnull', False), ('replacement_combination_policy', ''), ('replacement_eligible_count__isnull', True), ('replacement_revision_id__isnull', True)), models.Q(('active_revision__isnull', True), ('replacement_combination_policy__gt', ''), ('replacement_eligible_count__isnull', False), ('replacement_revision_id__isnull', False)), models.Q(('active_revision__isnull', True), ('replacement_combination_policy', ''), ('replacement_eligible_count__isnull', True), ('replacement_revision_id__isnull', True)), _connector='OR'), name='events_hist_slot_one_pointer'),
        ),
    ]
