# Generated by Django 6.0.8 on 2026-09-03 17:54
# Hand-adjusted: external_registrant_identifier was removed from
# EventRegistration (and its now-dangling unique constraint with it) before
# this ever shipped -- see events/models.py's EventRegistration docstring for
# why a natural key on this table was never load-bearing for replay safety.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrantIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_registrant_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventRegistrantImportProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('external_event_identifier', models.CharField(max_length=512)),
                ('completed', models.BooleanField(default=False)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_written', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('matched_account_total', models.PositiveIntegerField(default=0)),
                ('matched_prior_identity_total', models.PositiveIntegerField(default=0)),
                ('new_identity_total', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('provider', 'external_event_identifier'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_identifier'), name='events_registrant_import_progress_provider_external_unique')],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('status', models.CharField(max_length=32)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrant_registrations', to='events.event')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='events.eventregistrantidentity')),
            ],
            options={
                'ordering': ('event_id', 'provider', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='eventregistrantidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('normalized_email',), name='events_registrant_identity_email_unique_unmatched'),
        ),
        migrations.AddConstraint(
            model_name='eventregistrantidentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('normalized_email__isnull', True)), models.Q(('account__isnull', True), ('normalized_email__isnull', False)), _connector='OR'), name='events_registrant_identity_exactly_one_anchor'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['identity'], name='events_registration_identity'),
        ),
    ]
