# Generated by Django 6.0.7 on 2026-08-09

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0002_historicalregistrationaggregateslot_replacement_combination_policy_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="HistoricalRegistrationPointerDisplacement",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("row_replacement_revision_id", models.UUIDField(blank=True, null=True)),
                (
                    "row_replacement_eligible_count",
                    models.PositiveBigIntegerField(blank=True, null=True),
                ),
                (
                    "row_replacement_combination_policy",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("additive_disjoint", "Additive, disjoint"),
                            ("replacement", "Replacement"),
                            ("exclude", "Exclude"),
                        ],
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "displaced_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="displaced_by_replacements",
                        to="events.historicalregistrationaggregaterevision",
                    ),
                ),
                (
                    "replacing_revision",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="pointer_displacements",
                        to="events.historicalregistrationaggregaterevision",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="displacement_history",
                        to="events.historicalregistrationaggregateslot",
                    ),
                ),
            ],
            options={"ordering": ("created_at", "id")},
        ),
        migrations.AddConstraint(
            model_name="historicalregistrationpointerdisplacement",
            constraint=models.UniqueConstraint(
                fields=("replacing_revision", "slot"),
                name="events_hist_displacement_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="historicalregistrationpointerdisplacement",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("displaced_revision__isnull", False),
                        ("row_replacement_combination_policy", ""),
                        ("row_replacement_eligible_count__isnull", True),
                        ("row_replacement_revision_id__isnull", True),
                    ),
                    models.Q(
                        ("displaced_revision__isnull", True),
                        ("row_replacement_combination_policy__gt", ""),
                        ("row_replacement_eligible_count__isnull", False),
                        ("row_replacement_revision_id__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="events_hist_displacement_one_pointer",
            ),
        ),
    ]
