# Generated by Django 6.0.7 on 2026-08-12 12:04

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_historicalregistrationpointerdisplacement'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=1000)),
                ('slug', models.SlugField(max_length=255)),
                ('source_repository', models.CharField(max_length=255)),
                ('source_revision', models.CharField(max_length=64)),
                ('source_key', models.CharField(max_length=512)),
                ('source_path', models.CharField(default='', max_length=512)),
                ('source_checksum', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('source_key', 'id'),
                'constraints': [models.UniqueConstraint(fields=('source_repository', 'source_revision', 'source_key'), name='events_event_source_identity_unique'), models.CheckConstraint(condition=models.Q(('title__gt', '')), name='events_event_title_nonempty'), models.CheckConstraint(condition=models.Q(('source_repository__gt', ''), ('source_revision__gt', ''), ('source_key__gt', '')), name='events_event_source_identity_nonempty')],
            },
        ),
        migrations.AddField(
            model_name='historicaleventmapping',
            name='event',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_registration_mappings', to='events.event'),
        ),
        migrations.CreateModel(
            name='EventAlias',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_path', models.CharField(max_length=1024, unique=True)),
                ('kind', models.CharField(choices=[('legacy_path', 'Legacy path'), ('title_slug', 'Previous title slug'), ('reviewed', 'Reviewed alias')], max_length=24)),
                ('reason', models.CharField(max_length=255)),
                ('source_repository', models.CharField(max_length=255)),
                ('source_revision', models.CharField(max_length=64)),
                ('source_key', models.CharField(max_length=512)),
                ('activated_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='events.event')),
            ],
            options={
                'ordering': ('source_path', 'id'),
                'constraints': [models.CheckConstraint(condition=models.Q(('source_path__startswith', '/events/'), models.Q(('source_path__contains', '?'), _negated=True), models.Q(('source_path__contains', '#'), _negated=True)), name='events_alias_path_shape'), models.CheckConstraint(condition=models.Q(('source_repository__gt', ''), ('source_revision__gt', ''), ('source_key__gt', '')), name='events_alias_source_nonempty')],
            },
        ),
    ]
