# Generated by Django 6.0.8 on 2026-09-05 09:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_registrant_interest_signal'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('webinar', 'Webinar'), ('workshop', 'Workshop'), ('podcast', 'Podcast'), ('conference', 'Conference')], db_index=True, max_length=16)),
                ('starts_at', models.DateTimeField(db_index=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('season', models.PositiveIntegerField(blank=True, null=True)),
                ('episode', models.PositiveIntegerField(blank=True, null=True)),
                ('description_html', models.TextField(blank=True)),
                ('description_text', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='events.event')),
            ],
            options={
                'ordering': ('-starts_at', 'event_id'),
            },
        ),
        migrations.CreateModel(
            name='EventLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('url', models.URLField(max_length=2048)),
                ('position', models.PositiveSmallIntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links', to='events.eventcontent')),
            ],
            options={
                'ordering': ('content_id', 'position'),
            },
        ),
        migrations.CreateModel(
            name='EventSpeaker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('public_path', models.CharField(blank=True, max_length=1024)),
                ('position', models.PositiveSmallIntegerField()),
                ('content', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='speakers', to='events.eventcontent')),
            ],
            options={
                'ordering': ('content_id', 'position'),
            },
        ),
        migrations.AddConstraint(
            model_name='eventcontent',
            constraint=models.CheckConstraint(condition=models.Q(('ends_at__isnull', True), ('ends_at__gte', models.F('starts_at')), _connector='OR'), name='events_event_content_ends_after_start'),
        ),
        migrations.AddConstraint(
            model_name='eventcontent',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('episode__isnull', True), ('season__isnull', True)), models.Q(('episode__isnull', False), ('season__isnull', False)), _connector='OR'), name='events_event_content_season_episode_together'),
        ),
        migrations.AddConstraint(
            model_name='eventlink',
            constraint=models.UniqueConstraint(fields=('content', 'position'), name='events_event_link_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='eventlink',
            constraint=models.CheckConstraint(condition=models.Q(('label__gt', '')), name='events_event_link_labelled'),
        ),
        migrations.AddConstraint(
            model_name='eventspeaker',
            constraint=models.UniqueConstraint(fields=('content', 'position'), name='events_event_speaker_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='eventspeaker',
            constraint=models.UniqueConstraint(fields=('content', 'key'), name='events_event_speaker_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='eventspeaker',
            constraint=models.CheckConstraint(condition=models.Q(('key__gt', ''), ('name__gt', '')), name='events_event_speaker_identified'),
        ),
    ]
