# Generated by Django 6.0.8 on 2026-09-11 20:40

from django.db import migrations


class Migration(migrations.Migration):
    """Retire ``EventAlias`` -- model, table, and every alias kind -- outright.

    An Event is addressed only by its id; no other path (a previous title
    slug, a reviewed rename, a legacy date/title or UUID path) is retained for
    provenance or lookup any more.  The local dev database held zero
    ``EventAlias`` rows at the time this migration was written (the retired
    legacy-kind rows were deleted by a data migration in the same working
    session, before this one), so no data migration precedes this: dropping
    the table loses nothing.  Constraints are removed first because SQLite
    cannot drop a table out from under a ``CheckConstraint`` that still
    references it; Django's own migration autodetector sequenced this.
    """

    dependencies = [
        ('events', '0006_alter_eventqnasession_provisioning_job'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventalias',
            name='events_alias_path_shape',
        ),
        migrations.RemoveConstraint(
            model_name='eventalias',
            name='events_alias_source_nonempty',
        ),
        migrations.DeleteModel(
            name='EventAlias',
        ),
    ]
