# Generated by Django 6.0.8 on 2026-09-16 19:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0007_delete_eventalias'),
        # Run only after event_qna.0001 has copied the Q&A rows out of the
        # events_* tables this migration drops.
        ('event_qna', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventqnacohostinvite',
            name='events_qna_cohost_name_unique',
        ),
        migrations.RemoveIndex(
            model_name='eventqnaquestion',
            name='events_qna_q_status_time',
        ),
        migrations.RemoveIndex(
            model_name='eventqnaquestion',
            name='events_qna_q_rank',
        ),
        migrations.RemoveConstraint(
            model_name='eventqnaquestion',
            name='events_qna_question_content_nonempty',
        ),
        migrations.RemoveConstraint(
            model_name='eventqnaquestion',
            name='events_qna_question_score_nonnegative',
        ),
        migrations.RemoveIndex(
            model_name='eventqnaratelimit',
            name='events_qna_rate_scope',
        ),
        migrations.RemoveConstraint(
            model_name='eventqnaratelimit',
            name='events_qna_rate_window_unique',
        ),
        migrations.DeleteModel(
            name='EventQnaRateLimit',
        ),
        migrations.RemoveConstraint(
            model_name='eventqnasession',
            name='events_qna_session_revision_positive',
        ),
        migrations.RemoveConstraint(
            model_name='eventqnasession',
            name='events_qna_session_backend_nonempty',
        ),
        migrations.RemoveConstraint(
            model_name='eventqnasession',
            name='events_qna_answered_lte_total',
        ),
        migrations.RemoveConstraint(
            model_name='eventqnasession',
            name='events_qna_retention_positive',
        ),
        migrations.RemoveConstraint(
            model_name='eventqnavote',
            name='events_qna_vote_participant_unique',
        ),
        migrations.RemoveField(
            model_name='eventqnaquestion',
            name='session',
        ),
        migrations.RemoveField(
            model_name='eventqnasession',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventqnasession',
            name='provisioning_job',
        ),
        migrations.RemoveField(
            model_name='eventqnavote',
            name='question',
        ),
        migrations.DeleteModel(
            name='EventQnaCohostInvite',
        ),
        migrations.DeleteModel(
            name='EventQnaSession',
        ),
        migrations.DeleteModel(
            name='EventQnaQuestion',
        ),
        migrations.DeleteModel(
            name='EventQnaVote',
        ),
    ]
