# Generated by Django 6.0.8 on 2026-09-16 19:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_remove_eventqnacohostinvite_events_qna_cohost_name_unique_and_more'),
        # Run only after historical_registrations.0001 has copied the rows out
        # of the events_* tables this migration drops.
        ('historical_registrations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='historicalregistrationaggregaterevision',
            name='events_hist_agg_checksum',
        ),
        migrations.RemoveIndex(
            model_name='historicalregistrationaggregaterevision',
            name='events_hist_agg_state',
        ),
        migrations.RemoveIndex(
            model_name='historicalregistrationaggregaterevision',
            name='events_hist_agg_run_ext_id',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationaggregaterevision',
            name='events_hist_aggregate_revision_positive',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationaggregaterevision',
            name='events_hist_aggregate_revision_unique',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationaggregaterevision',
            name='events_hist_aggregate_external_id_nonempty',
        ),
        migrations.RemoveIndex(
            model_name='historicalregistrationaggregateslot',
            name='events_hist_slot_source',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationaggregateslot',
            name='events_hist_active_slot_unique',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationaggregateslot',
            name='events_hist_slot_revision_positive',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationaggregateslot',
            name='events_hist_slot_one_pointer',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationpointerdisplacement',
            name='events_hist_displacement_unique',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationpointerdisplacement',
            name='events_hist_displacement_one_pointer',
        ),
        migrations.RemoveIndex(
            model_name='historicalregistrationsourcerun',
            name='events_hist_run_state',
        ),
        migrations.RemoveIndex(
            model_name='historicalregistrationsourcerun',
            name='events_hist_run_checksum',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationsourcerun',
            name='events_hist_run_replay_unique',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationsourcerun',
            name='events_hist_run_revision_positive',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationsourcerun',
            name='events_hist_run_eligible_bounded',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationsourcerun',
            name='events_hist_run_excluded_bounded',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationtotalstate',
            name='events_hist_total_source_unique',
        ),
        migrations.RemoveConstraint(
            model_name='historicalregistrationtotalstate',
            name='events_hist_total_revision_positive',
        ),
        migrations.DeleteModel(
            name='HistoricalRegistrationTotalState',
        ),
        migrations.RemoveField(
            model_name='historicalregistrationaggregateslot',
            name='active_revision',
        ),
        migrations.RemoveField(
            model_name='historicalregistrationpointerdisplacement',
            name='displaced_revision',
        ),
        migrations.RemoveField(
            model_name='historicalregistrationpointerdisplacement',
            name='replacing_revision',
        ),
        migrations.RemoveField(
            model_name='historicalregistrationpointerdisplacement',
            name='slot',
        ),
        migrations.RemoveField(
            model_name='historicalregistrationsourcerun',
            name='actor',
        ),
        migrations.DeleteModel(
            name='HistoricalRegistrationAggregateRevision',
        ),
        migrations.DeleteModel(
            name='HistoricalRegistrationAggregateSlot',
        ),
        migrations.DeleteModel(
            name='HistoricalRegistrationPointerDisplacement',
        ),
        migrations.DeleteModel(
            name='HistoricalRegistrationSourceRun',
        ),
    ]
