# Generated by Django 6.0.8 on 2026-09-16 21:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_remove_historicalregistrationaggregaterevision_events_hist_agg_checksum_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='eventregistrantidentity',
            name='events_registrant_identity_email_unique_unmatched',
        ),
        migrations.RemoveConstraint(
            model_name='eventregistrantidentity',
            name='events_registrant_identity_exactly_one_anchor',
        ),
        migrations.RemoveConstraint(
            model_name='eventregistrantimportprogress',
            name='events_registrant_import_progress_provider_external_unique',
        ),
        migrations.DeleteModel(
            name='EventRegistrantImportProgress',
        ),
        migrations.RemoveConstraint(
            model_name='eventregistrantinterestsignal',
            name='events_registrant_interest_signal_unique',
        ),
        migrations.RemoveIndex(
            model_name='eventregistration',
            name='events_registration_identity',
        ),
        migrations.RemoveField(
            model_name='eventregistrantidentity',
            name='account',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='event',
        ),
        migrations.RemoveField(
            model_name='eventregistration',
            name='identity',
        ),
        migrations.DeleteModel(
            name='EventRegistrantInterestSignal',
        ),
        migrations.DeleteModel(
            name='EventRegistrantIdentity',
        ),
        migrations.DeleteModel(
            name='EventRegistration',
        ),
    ]
