# Generated by Django 6.0.8 on 2026-08-20 11:58

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_eventqnasession'),
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQnaCohostInvite',
            fields=[
                ('invite_id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=48)),
                ('passcode_digest', models.CharField(max_length=128)),
                ('created_by_ref', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('name', 'invite_id'),
            },
        ),
        migrations.CreateModel(
            name='EventQnaQuestion',
            fields=[
                ('question_id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=315)),
                ('author_name', models.CharField(blank=True, max_length=60, null=True)),
                ('participant_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('answered', 'Answered'), ('deleted', 'Deleted')], default='visible', max_length=16)),
                ('score', models.PositiveIntegerField(default=0)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-pinned', '-score', 'created_at', 'question_id'),
            },
        ),
        migrations.CreateModel(
            name='EventQnaRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_digest', models.CharField(max_length=64)),
                ('window_seconds', models.PositiveIntegerField()),
                ('window_started_at', models.DateTimeField()),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='EventQnaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name='eventqnasession',
            options={'ordering': ('event_id', 'id'), 'permissions': (('view_event_qna', 'Can view event-linked Q&A'), ('manage_event_qna', 'Can manage event-linked Q&A'))},
        ),
        migrations.AddField(
            model_name='event',
            name='lifecycle',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('archived', 'Archived')], db_index=True, default='published', max_length=16),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='allow_names',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='answered_placement',
            field=models.CharField(choices=[('separate', 'Separate'), ('bottom', 'Bottom'), ('inline', 'Inline')], default='separate', max_length=16),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='archive_delete_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='default_sort',
            field=models.CharField(choices=[('popular', 'Popular'), ('recent', 'Recent')], default='popular', max_length=16),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='expires_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='listed',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='q_answered',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='q_total',
            field=models.PositiveBigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='require_names',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='retention_days',
            field=models.PositiveIntegerField(blank=True, default=365, null=True),
        ),
        migrations.AddField(
            model_name='eventqnasession',
            name='state_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddConstraint(
            model_name='eventqnasession',
            constraint=models.CheckConstraint(condition=models.Q(('q_answered__lte', models.F('q_total'))), name='events_qna_answered_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='eventqnasession',
            constraint=models.CheckConstraint(condition=models.Q(('retention_days__isnull', True), ('retention_days__gte', 1), _connector='OR'), name='events_qna_retention_positive'),
        ),
        migrations.AddField(
            model_name='eventqnacohostinvite',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohost_invites', to='events.eventqnasession'),
        ),
        migrations.AddField(
            model_name='eventqnaquestion',
            name='session',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='events.eventqnasession'),
        ),
        migrations.AddIndex(
            model_name='eventqnaratelimit',
            index=models.Index(fields=['scope_digest', 'window_seconds'], name='events_qna_rate_scope'),
        ),
        migrations.AddConstraint(
            model_name='eventqnaratelimit',
            constraint=models.UniqueConstraint(fields=('scope_digest', 'window_seconds', 'window_started_at'), name='events_qna_rate_window_unique'),
        ),
        migrations.AddField(
            model_name='eventqnavote',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='events.eventqnaquestion'),
        ),
        migrations.AddConstraint(
            model_name='eventqnacohostinvite',
            constraint=models.UniqueConstraint(fields=('session', 'name'), name='events_qna_cohost_name_unique'),
        ),
        migrations.AddIndex(
            model_name='eventqnaquestion',
            index=models.Index(fields=['session', 'status', 'created_at'], name='events_qna_q_status_time'),
        ),
        migrations.AddIndex(
            model_name='eventqnaquestion',
            index=models.Index(fields=['session', 'pinned', 'score'], name='events_qna_q_rank'),
        ),
        migrations.AddConstraint(
            model_name='eventqnaquestion',
            constraint=models.CheckConstraint(condition=models.Q(('text__gt', ''), ('participant_digest__gt', '')), name='events_qna_question_content_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='eventqnaquestion',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='events_qna_question_score_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='eventqnavote',
            constraint=models.UniqueConstraint(fields=('question', 'participant_digest'), name='events_qna_vote_participant_unique'),
        ),
    ]
