# Generated by Django 6.0.8 on 2026-08-20 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_eventqnacohostinvite_eventqnaquestion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventqnaquestion',
            name='author_name',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
    ]
