# Generated by Django 6.0.8 on 2026-09-03 10:32

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SchedulerLease',
            fields=[
                ('key', models.CharField(default='default', editable=False, max_length=32, primary_key=True, serialize=False)),
                ('owner_id', models.CharField(blank=True, max_length=128)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('acquired_at', models.DateTimeField(blank=True, null=True)),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'constraints': [models.CheckConstraint(condition=models.Q(('key', 'default')), name='jobs_scheduler_lease_singleton'), models.CheckConstraint(condition=models.Q(models.Q(('acquired_at__isnull', False), ('expires_at__isnull', False), ('heartbeat_at__isnull', False), ('lease_token__isnull', False), models.Q(('owner_id', ''), _negated=True)), models.Q(('lease_token__isnull', True), ('acquired_at__isnull', True), ('heartbeat_at__isnull', True), ('expires_at__isnull', True), ('owner_id', '')), _connector='OR'), name='jobs_scheduler_lease_state_consistent')],
            },
        ),
        migrations.CreateModel(
            name='WorkerHeartbeat',
            fields=[
                ('worker_id', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('lease_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('started_at', models.DateTimeField()),
                ('heartbeat_at', models.DateTimeField()),
                ('expires_at', models.DateTimeField()),
                ('metadata', models.JSONField(default=dict)),
            ],
            options={
                'ordering': ('worker_id',),
                'indexes': [models.Index(fields=['expires_at'], name='jobs_heartbeat_expiry')],
                'constraints': [models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('heartbeat_at'))), name='jobs_heartbeat_expiry_after_beat'), models.CheckConstraint(condition=models.Q(('heartbeat_at__gte', models.F('started_at'))), name='jobs_heartbeat_after_start')],
            },
        ),
        migrations.CreateModel(
            name='DurableJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('handler', models.CharField(max_length=128)),
                ('deduplication_key_hash', models.CharField(max_length=64)),
                ('payload_hash', models.CharField(max_length=64)),
                ('payload', models.JSONField(default=dict)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('retry_wait', 'Waiting to retry'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=3)),
                ('available_at', models.DateTimeField()),
                ('next_wakeup_at', models.DateTimeField()),
                ('wakeup_count', models.PositiveIntegerField(default=0)),
                ('lease_token', models.UUIDField(blank=True, editable=False, null=True)),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True)),
                ('claimed_by', models.CharField(blank=True, max_length=128)),
                ('last_error_code', models.CharField(blank=True, max_length=64)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('operation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='durable_jobs', to='core.operation')),
            ],
            options={
                'ordering': ('available_at', 'created_at', 'id'),
                'indexes': [models.Index(fields=['status', 'available_at', 'next_wakeup_at'], name='jobs_durable_due'), models.Index(fields=['status', 'lease_expires_at'], name='jobs_durable_lease'), models.Index(fields=['correlation_id'], name='jobs_durable_correlation')],
                'constraints': [models.CheckConstraint(condition=models.Q(('max_attempts__gte', 1)), name='jobs_durable_max_attempts_positive'), models.UniqueConstraint(fields=('handler', 'deduplication_key_hash'), name='jobs_durable_handler_dedupe_unique'), models.CheckConstraint(condition=models.Q(('attempt_count__lte', models.F('max_attempts'))), name='jobs_durable_attempts_bounded'), models.CheckConstraint(condition=models.Q(models.Q(('lease_expires_at__isnull', False), ('lease_token__isnull', False), ('status', 'running'), models.Q(('claimed_by', ''), _negated=True)), models.Q(models.Q(('status', 'running'), _negated=True), ('lease_token__isnull', True), ('lease_expires_at__isnull', True), ('claimed_by', '')), _connector='OR'), name='jobs_durable_lease_state_consistent'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', False), ('status__in', ('succeeded', 'failed', 'cancelled'))), models.Q(models.Q(('status__in', ('succeeded', 'failed', 'cancelled')), _negated=True), ('completed_at__isnull', True)), _connector='OR'), name='jobs_durable_terminal_time_consistent')],
            },
        ),
    ]
