# Generated by Django 6.0.8 on 2026-09-03 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=128)),
                ('key_hash', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=16)),
                ('owner_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('progress_current', models.PositiveBigIntegerField(default=0)),
                ('progress_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cancellable', models.BooleanField(default=False)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('result_summary', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('actor_ref', models.CharField(blank=True, max_length=128)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OperationalSetting',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('string', 'String'), ('string_list', 'String list'), ('json_object', 'JSON object')], max_length=16)),
                ('value', models.JSONField()),
                ('source', models.CharField(max_length=64)),
                ('definition_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
                'permissions': (('read_operational_settings', 'Can read operational settings'), ('change_operational_settings', 'Can change operational settings')),
            },
        ),
        migrations.CreateModel(
            name='OperationalSettingRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('string', 'String'), ('string_list', 'String list'), ('json_object', 'JSON object')], max_length=16)),
                ('value', models.JSONField()),
                ('source', models.CharField(max_length=64)),
                ('definition_version', models.PositiveIntegerField()),
                ('revision', models.PositiveBigIntegerField()),
                ('changed_by_ref', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('setting_id', 'revision'),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='SiteNavigationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=80)),
                ('target', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField()),
                ('visible', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('position', 'key'),
            },
        ),
        migrations.CreateModel(
            name='SiteNavigationMenu',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('source', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
                'permissions': (('read_site_navigation', 'Can read site navigation'), ('change_site_navigation', 'Can change site navigation')),
            },
        ),
        migrations.CreateModel(
            name='SiteNavigationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_key', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=64)),
                ('revision', models.PositiveBigIntegerField()),
                ('entries', models.JSONField(default=list)),
                ('changed_by_ref', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('menu_id', 'revision'),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], max_length=16)),
                ('source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
                'permissions': (('read_sponsors', 'Can read sponsors'), ('change_sponsors', 'Can change sponsors'), ('export_sponsors', 'Can export the sponsor directory')),
            },
        ),
        migrations.CreateModel(
            name='SponsorPlacementAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement_key', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ('placement_key', 'position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SponsorRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], max_length=16)),
                ('source', models.CharField(max_length=64)),
                ('revision', models.PositiveBigIntegerField()),
                ('assignments', models.JSONField(default=list)),
                ('changed_by_ref', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('sponsor_id', 'revision'),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authenticated_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('-authenticated_at', '-id'),
                'permissions': (('access_studio', 'Can access Studio'), ('browse_audit', 'Can browse Studio audit events'), ('execute_high_risk_fixture', 'Can execute the test-only high-risk fixture')),
            },
        ),
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_ref', models.CharField(blank=True, max_length=128)),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(max_length=128)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('denied', 'Denied'), ('failed', 'Failed')], max_length=16)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('job_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key_hash', models.CharField(blank=True, max_length=64)),
                ('changes', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('source_ip_class', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
    ]
