# Generated by Django 6.0.7 on 2026-08-08 02:36

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


APPEND_ONLY_GUARDS = (
    ("core_auditevent", "dtc_core_audit_append_only", "actor_id"),
    (
        "core_operationalsettingrevision",
        "dtc_core_setting_revision_append_only",
        "changed_by_id",
    ),
)

APPEND_ONLY_EXPLICIT_TEST_DATABASE_NAMES = frozenset({"dtc_test"})


def is_append_only_test_database(database_name):
    return (
        database_name in APPEND_ONLY_EXPLICIT_TEST_DATABASE_NAMES
        or database_name.startswith("test_")
    )


def install_append_only_guards(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    quote = schema_editor.connection.ops.quote_name
    database_name = str(schema_editor.connection.settings_dict.get("NAME", ""))
    allow_test_flush = bool(
        getattr(settings, "CORE_ALLOW_APPEND_ONLY_TEST_FLUSH", False)
    )
    if allow_test_flush and not is_append_only_test_database(database_name):
        raise RuntimeError("append-only test flush requires a Django test database")
    for table, function, retention_column in APPEND_ONLY_GUARDS:
        trigger = f"{function}_trigger"
        schema_editor.execute(
            f"""
            CREATE OR REPLACE FUNCTION {quote(function)}() RETURNS trigger
            LANGUAGE plpgsql AS $$
            BEGIN
                IF TG_OP = 'UPDATE' THEN
                    IF OLD.{quote(retention_column)} IS NOT NULL
                       AND NEW.{quote(retention_column)} IS NULL
                       AND (to_jsonb(NEW) - '{retention_column}')
                           IS NOT DISTINCT FROM (to_jsonb(OLD) - '{retention_column}')
                    THEN
                        RETURN NEW;
                    END IF;
                END IF;
                RAISE EXCEPTION 'append-only evidence cannot be changed'
                    USING ERRCODE = '55000';
            END;
            $$
            """
        )
        if not allow_test_flush:
            truncate_trigger = f"{function}_truncate_trigger"
            schema_editor.execute(
                f"""
                CREATE TRIGGER {quote(truncate_trigger)}
                BEFORE TRUNCATE ON {quote(table)}
                FOR EACH STATEMENT EXECUTE FUNCTION {quote(function)}()
                """
            )
        schema_editor.execute(
            f"""
            CREATE TRIGGER {quote(trigger)}
            BEFORE UPDATE OR DELETE ON {quote(table)}
            FOR EACH ROW EXECUTE FUNCTION {quote(function)}()
            """
        )


def remove_append_only_guards(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor != "postgresql":
        return
    quote = schema_editor.connection.ops.quote_name
    for table, function, _retention_column in reversed(APPEND_ONLY_GUARDS):
        trigger = f"{function}_trigger"
        truncate_trigger = f"{function}_truncate_trigger"
        schema_editor.execute(
            f"DROP TRIGGER IF EXISTS {quote(truncate_trigger)} ON {quote(table)}"
        )
        schema_editor.execute(f"DROP TRIGGER IF EXISTS {quote(trigger)} ON {quote(table)}")
        schema_editor.execute(f"DROP FUNCTION IF EXISTS {quote(function)}()")


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_ref', models.CharField(blank=True, max_length=128)),
                ('action', models.CharField(max_length=128)),
                ('target_type', models.CharField(max_length=128)),
                ('target_id', models.UUIDField(blank=True, null=True)),
                ('target_label', models.CharField(blank=True, max_length=255)),
                ('outcome', models.CharField(choices=[('succeeded', 'Succeeded'), ('denied', 'Denied'), ('failed', 'Failed')], max_length=16)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('job_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key_hash', models.CharField(blank=True, max_length=64)),
                ('changes', models.JSONField(default=dict)),
                ('metadata', models.JSONField(default=dict)),
                ('source_ip_class', models.CharField(blank=True, max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.CreateModel(
            name='IdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('scope', models.CharField(max_length=128)),
                ('key_hash', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], default='in_progress', max_length=16)),
                ('owner_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('result', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'indexes': [models.Index(fields=['status', 'created_at'], name='core_idempotency_status'), models.Index(fields=['request_hash'], name='core_idempotency_request')],
                'constraints': [models.UniqueConstraint(fields=('scope', 'key_hash'), name='core_idempotency_scope_key_unique'), models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('result__isnull', True), ('status', 'in_progress')), models.Q(('completed_at__isnull', False), ('result__isnull', False), ('status', 'completed')), _connector='OR'), name='core_idempotency_state_consistent')],
            },
        ),
        migrations.CreateModel(
            name='Operation',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(max_length=128)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=16)),
                ('progress_current', models.PositiveBigIntegerField(default=0)),
                ('progress_total', models.PositiveBigIntegerField(blank=True, null=True)),
                ('cancellable', models.BooleanField(default=False)),
                ('cancellation_requested_at', models.DateTimeField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255)),
                ('result_summary', models.JSONField(default=dict)),
                ('errors', models.JSONField(default=list)),
                ('actor_ref', models.CharField(blank=True, max_length=128)),
                ('request_id', models.CharField(blank=True, max_length=128)),
                ('correlation_id', models.CharField(blank=True, max_length=128)),
                ('idempotency_key_hash', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='OperationalSetting',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128, unique=True)),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('string', 'String'), ('string_list', 'String list'), ('json_object', 'JSON object')], max_length=16)),
                ('value', models.JSONField()),
                ('source', models.CharField(max_length=64)),
                ('definition_version', models.PositiveIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
                'indexes': [models.Index(fields=['source', 'key'], name='core_setting_source_key')],
                'constraints': [models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_setting_revision_positive'), models.CheckConstraint(condition=models.Q(('definition_version__gte', 1)), name='core_setting_definition_positive')],
            },
        ),
        migrations.CreateModel(
            name='OperationalSettingRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=128)),
                ('value_type', models.CharField(choices=[('boolean', 'Boolean'), ('integer', 'Integer'), ('string', 'String'), ('string_list', 'String list'), ('json_object', 'JSON object')], max_length=16)),
                ('value', models.JSONField()),
                ('source', models.CharField(max_length=64)),
                ('definition_version', models.PositiveIntegerField()),
                ('revision', models.PositiveBigIntegerField()),
                ('changed_by_ref', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_event', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='setting_revision', to='core.auditevent')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_setting_revisions', to=settings.AUTH_USER_MODEL)),
                ('setting', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.operationalsetting')),
            ],
            options={
                'ordering': ('setting_id', 'revision'),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
            },
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', '-created_at'], name='core_audit_action_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_type', 'target_id', '-created_at'], name='core_audit_target_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id'], name='core_audit_request'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['correlation_id'], name='core_audit_correlation'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['job_id'], name='core_audit_job'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_ref'], name='core_audit_actor_ref'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status', '-created_at'], name='core_operation_status_time'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['kind', '-created_at'], name='core_operation_kind_time'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['correlation_id'], name='core_operation_correlation'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_operation_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('progress_total__isnull', True), ('progress_current__lte', models.F('progress_total')), _connector='OR'), name='core_operation_progress_bounded'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', False), ('status__in', ('succeeded', 'failed', 'cancelled'))), models.Q(('finished_at__isnull', True), ('status__in', ('pending', 'running'))), _connector='OR'), name='core_operation_finish_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='operationalsettingrevision',
            index=models.Index(fields=['key', '-revision'], name='core_setting_history_key'),
        ),
        migrations.AddConstraint(
            model_name='operationalsettingrevision',
            constraint=models.UniqueConstraint(fields=('setting', 'revision'), name='core_setting_history_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='operationalsettingrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_setting_history_revision_positive'),
        ),
        migrations.RunPython(
            install_append_only_guards,
            remove_append_only_guards,
        ),
    ]
