# Generated by Django 6.0.7 on 2026-08-08 11:26

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StaffSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('authenticated_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_staff_sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-authenticated_at', '-id'),
                'permissions': (('access_studio', 'Can access Studio'), ('browse_audit', 'Can browse Studio audit events'), ('execute_high_risk_fixture', 'Can execute the test-only high-risk fixture')),
                'indexes': [models.Index(fields=['user', 'revoked_at', '-authenticated_at'], name='core_staff_session_user')],
                'constraints': [models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('authenticated_at')), _connector='OR'), name='core_staff_session_revoked_after_auth')],
            },
        ),
    ]
