# Generated by Django 6.0.8 on 2026-09-03 10:32

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('management_auth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='auditevent',
            name='api_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='management_auth.apiprincipal'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['status', 'created_at'], name='core_idempotency_status'),
        ),
        migrations.AddIndex(
            model_name='idempotencyrecord',
            index=models.Index(fields=['request_hash'], name='core_idempotency_request'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.UniqueConstraint(fields=('scope', 'key_hash'), name='core_idempotency_scope_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='idempotencyrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('result__isnull', True), ('status', 'in_progress')), models.Q(('completed_at__isnull', False), ('result__isnull', False), ('status', 'completed')), _connector='OR'), name='core_idempotency_state_consistent'),
        ),
        migrations.AddField(
            model_name='operation',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operation',
            name='api_principal',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operations', to='management_auth.apiprincipal'),
        ),
        migrations.AddIndex(
            model_name='operationalsetting',
            index=models.Index(fields=['source', 'key'], name='core_setting_source_key'),
        ),
        migrations.AddConstraint(
            model_name='operationalsetting',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_setting_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='operationalsetting',
            constraint=models.CheckConstraint(condition=models.Q(('definition_version__gte', 1)), name='core_setting_definition_positive'),
        ),
        migrations.AddField(
            model_name='operationalsettingrevision',
            name='audit_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='setting_revisions', to='core.auditevent'),
        ),
        migrations.AddField(
            model_name='operationalsettingrevision',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operational_setting_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='operationalsettingrevision',
            name='setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.operationalsetting'),
        ),
        migrations.AddIndex(
            model_name='sitenavigationmenu',
            index=models.Index(fields=['key'], name='core_navigation_menu_key'),
        ),
        migrations.AddConstraint(
            model_name='sitenavigationmenu',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_navigation_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='sitenavigationmenu',
            constraint=models.CheckConstraint(condition=models.Q(('key', 'primary')), name='core_navigation_menu_key_allowlist'),
        ),
        migrations.AddConstraint(
            model_name='sitenavigationmenu',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ('studio', 'admin_api'))), name='core_navigation_source_allowlist'),
        ),
        migrations.AddField(
            model_name='sitenavigationentry',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.sitenavigationmenu'),
        ),
        migrations.AddField(
            model_name='sitenavigationrevision',
            name='audit_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='navigation_revisions', to='core.auditevent'),
        ),
        migrations.AddField(
            model_name='sitenavigationrevision',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_navigation_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sitenavigationrevision',
            name='menu',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.sitenavigationmenu'),
        ),
        migrations.AddIndex(
            model_name='sponsor',
            index=models.Index(fields=['lifecycle', 'key'], name='core_sponsor_lifecycle_key'),
        ),
        migrations.AddConstraint(
            model_name='sponsor',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_sponsor_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='sponsor',
            constraint=models.CheckConstraint(condition=models.Q(('lifecycle__in', ('draft', 'active', 'archived'))), name='core_sponsor_lifecycle_allowlist'),
        ),
        migrations.AddField(
            model_name='sponsorplacementassignment',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.sponsor'),
        ),
        migrations.AddField(
            model_name='sponsorrevision',
            name='audit_event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_revisions', to='core.auditevent'),
        ),
        migrations.AddField(
            model_name='sponsorrevision',
            name='changed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_revisions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sponsorrevision',
            name='sponsor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.sponsor'),
        ),
        migrations.AddField(
            model_name='staffsession',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='studio_staff_sessions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['action', '-created_at'], name='core_audit_action_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['target_type', 'target_id', '-created_at'], name='core_audit_target_time'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['request_id'], name='core_audit_request'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['correlation_id'], name='core_audit_correlation'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['job_id'], name='core_audit_job'),
        ),
        migrations.AddIndex(
            model_name='auditevent',
            index=models.Index(fields=['actor_ref'], name='core_audit_actor_ref'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['status', '-created_at'], name='core_operation_status_time'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['kind', '-created_at'], name='core_operation_kind_time'),
        ),
        migrations.AddIndex(
            model_name='operation',
            index=models.Index(fields=['correlation_id'], name='core_operation_correlation'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_operation_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(('progress_total__isnull', True), ('progress_current__lte', models.F('progress_total')), _connector='OR'), name='core_operation_progress_bounded'),
        ),
        migrations.AddConstraint(
            model_name='operation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('finished_at__isnull', False), ('status__in', ('succeeded', 'failed', 'cancelled'))), models.Q(('finished_at__isnull', True), ('status__in', ('pending', 'running'))), _connector='OR'), name='core_operation_finish_state_consistent'),
        ),
        migrations.AddIndex(
            model_name='operationalsettingrevision',
            index=models.Index(fields=['key', '-revision'], name='core_setting_history_key'),
        ),
        migrations.AddConstraint(
            model_name='operationalsettingrevision',
            constraint=models.UniqueConstraint(fields=('setting', 'revision'), name='core_setting_history_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='operationalsettingrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_setting_history_revision_positive'),
        ),
        migrations.AddIndex(
            model_name='sitenavigationentry',
            index=models.Index(fields=['menu', 'position'], name='core_navigation_entry_order'),
        ),
        migrations.AddConstraint(
            model_name='sitenavigationentry',
            constraint=models.UniqueConstraint(fields=('menu', 'key'), name='core_navigation_entry_key_unique'),
        ),
        migrations.AddConstraint(
            model_name='sitenavigationentry',
            constraint=models.UniqueConstraint(fields=('menu', 'position'), name='core_navigation_entry_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='sitenavigationentry',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 12)), name='core_navigation_entry_position_bounded'),
        ),
        migrations.AddIndex(
            model_name='sitenavigationrevision',
            index=models.Index(fields=['menu_key', '-revision'], name='core_navigation_history_key'),
        ),
        migrations.AddConstraint(
            model_name='sitenavigationrevision',
            constraint=models.UniqueConstraint(fields=('menu', 'revision'), name='core_navigation_history_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='sitenavigationrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_navigation_history_revision_positive'),
        ),
        migrations.AddIndex(
            model_name='sponsorplacementassignment',
            index=models.Index(fields=['placement_key', 'enabled', 'position'], name='core_sponsor_assignment_public'),
        ),
        migrations.AddConstraint(
            model_name='sponsorplacementassignment',
            constraint=models.UniqueConstraint(fields=('sponsor', 'placement_key'), name='core_sponsor_assignment_unique'),
        ),
        migrations.AddConstraint(
            model_name='sponsorplacementassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('placement_key', 'position'), name='core_sponsor_assignment_position_unique'),
        ),
        migrations.AddConstraint(
            model_name='sponsorplacementassignment',
            constraint=models.CheckConstraint(condition=models.Q(('placement_key', 'events_hub')), name='core_sponsor_placement_allowlist'),
        ),
        migrations.AddConstraint(
            model_name='sponsorplacementassignment',
            constraint=models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='core_sponsor_assignment_position_positive'),
        ),
        migrations.AddIndex(
            model_name='sponsorrevision',
            index=models.Index(fields=['key', '-revision'], name='core_sponsor_history_key'),
        ),
        migrations.AddConstraint(
            model_name='sponsorrevision',
            constraint=models.UniqueConstraint(fields=('sponsor', 'revision'), name='core_sponsor_history_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='sponsorrevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_sponsor_history_revision_positive'),
        ),
        migrations.AddIndex(
            model_name='staffsession',
            index=models.Index(fields=['user', 'revoked_at', '-authenticated_at'], name='core_staff_session_user'),
        ),
        migrations.AddConstraint(
            model_name='staffsession',
            constraint=models.CheckConstraint(condition=models.Q(('revoked_at__isnull', True), ('revoked_at__gte', models.F('authenticated_at')), _connector='OR'), name='core_staff_session_revoked_after_auth'),
        ),
    ]
