# Generated by Django 6.0.8 on 2026-09-03 18:00

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sponsor',
            name='description',
            field=models.TextField(blank=True, help_text='Longer copy shown on the public sponsor directory. Short-line placements such as events_hub use tagline instead and can leave this empty.'),
        ),
        migrations.AddField(
            model_name='sponsor',
            name='logo_asset_key',
            field=models.CharField(blank=True, help_text="Logo key relative to the site-assets prefix, e.g. 'sponsors/example.png'. Empty renders no logo.", max_length=200, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\.\\.)(?!.*\\\\)(?!\\w+:)[\\w.-]+(?:/[\\w.-]+)*$', "Enter a key relative to the site-assets prefix, e.g. 'sponsors/example.png'.")]),
        ),
        migrations.AddField(
            model_name='sponsorrevision',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sponsorrevision',
            name='logo_asset_key',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.RemoveConstraint(
            model_name='sponsorplacementassignment',
            name='core_sponsor_placement_allowlist',
        ),
        migrations.AddConstraint(
            model_name='sponsorplacementassignment',
            constraint=models.CheckConstraint(condition=models.Q(('placement_key__in', ('events_hub', 'public_directory'))), name='core_sponsor_placement_allowlist'),
        ),
    ]
