# Generated by Django 6.0.7 on 2026-08-10 10:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_management_principal_attribution"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="operationalsetting",
            options={
                "ordering": ("key",),
                "permissions": (
                    ("read_operational_settings", "Can read operational settings"),
                    ("change_operational_settings", "Can change operational settings"),
                ),
            },
        ),
        migrations.AlterField(
            model_name="operationalsettingrevision",
            name="audit_event",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="setting_revisions",
                to="core.auditevent",
            ),
        ),
    ]
