# Generated by Django 6.0.8 on 2026-09-03 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sponsor_public_directory'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sitenavigationrevision',
            name='core_navigation_history_key',
        ),
        migrations.RemoveConstraint(
            model_name='sitenavigationrevision',
            name='core_navigation_history_revision_unique',
        ),
        migrations.RemoveConstraint(
            model_name='sitenavigationrevision',
            name='core_navigation_history_revision_positive',
        ),
        migrations.DeleteModel(
            name='SiteNavigationRevision',
        ),
    ]
