# Generated by Django 6.0.7 on 2026-08-18 18:30

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_site_settings_permissions_and_batch_audit'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64, unique=True)),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], max_length=16)),
                ('source', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
                'permissions': (('read_sponsors', 'Can read sponsors'), ('change_sponsors', 'Can change sponsors'), ('export_sponsors', 'Can export the sponsor directory')),
                'indexes': [models.Index(fields=['lifecycle', 'key'], name='core_sponsor_lifecycle_key')],
                'constraints': [models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_sponsor_revision_positive'), models.CheckConstraint(condition=models.Q(('lifecycle__in', ('draft', 'active', 'archived'))), name='core_sponsor_lifecycle_allowlist')],
            },
        ),
        migrations.CreateModel(
            name='SponsorPlacementAssignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('placement_key', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField()),
                ('enabled', models.BooleanField(default=True)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assignments', to='core.sponsor')),
            ],
            options={
                'ordering': ('placement_key', 'position', 'id'),
                'indexes': [models.Index(fields=['placement_key', 'enabled', 'position'], name='core_sponsor_assignment_public')],
                'constraints': [models.UniqueConstraint(fields=('sponsor', 'placement_key'), name='core_sponsor_assignment_unique'), models.UniqueConstraint(condition=models.Q(('enabled', True)), fields=('placement_key', 'position'), name='core_sponsor_assignment_position_unique'), models.CheckConstraint(condition=models.Q(('placement_key', 'events_hub')), name='core_sponsor_placement_allowlist'), models.CheckConstraint(condition=models.Q(('position__gte', 1)), name='core_sponsor_assignment_position_positive')],
            },
        ),
        migrations.CreateModel(
            name='SponsorRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=64)),
                ('name', models.CharField(max_length=120)),
                ('url', models.CharField(blank=True, max_length=500)),
                ('tagline', models.CharField(blank=True, max_length=200)),
                ('lifecycle', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], max_length=16)),
                ('source', models.CharField(max_length=64)),
                ('revision', models.PositiveBigIntegerField()),
                ('assignments', models.JSONField(default=list)),
                ('changed_by_ref', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sponsor_revisions', to='core.auditevent')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sponsor_revisions', to=settings.AUTH_USER_MODEL)),
                ('sponsor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.sponsor')),
            ],
            options={
                'ordering': ('sponsor_id', 'revision'),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['key', '-revision'], name='core_sponsor_history_key')],
                'constraints': [models.UniqueConstraint(fields=('sponsor', 'revision'), name='core_sponsor_history_revision_unique'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_sponsor_history_revision_positive')],
            },
        ),
    ]
