# Generated by Django 6.0.8 on 2026-09-03 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_remove_site_navigation_revision'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='operationalsettingrevision',
            name='core_setting_history_key',
        ),
        migrations.RemoveConstraint(
            model_name='operationalsettingrevision',
            name='core_setting_history_revision_unique',
        ),
        migrations.RemoveConstraint(
            model_name='operationalsettingrevision',
            name='core_setting_history_revision_positive',
        ),
        migrations.DeleteModel(
            name='OperationalSettingRevision',
        ),
    ]
