# Generated by Django 6.0.7 on 2026-08-18 20:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_sponsor_directory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteNavigationMenu',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32, unique=True)),
                ('source', models.CharField(max_length=64)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('key',),
                'permissions': (('read_site_navigation', 'Can read site navigation'), ('change_site_navigation', 'Can change site navigation')),
                'indexes': [models.Index(fields=['key'], name='core_navigation_menu_key')],
                'constraints': [models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_navigation_revision_positive'), models.CheckConstraint(condition=models.Q(('key', 'primary')), name='core_navigation_menu_key_allowlist'), models.CheckConstraint(condition=models.Q(('source__in', ('studio', 'admin_api'))), name='core_navigation_source_allowlist')],
            },
        ),
        migrations.CreateModel(
            name='SiteNavigationEntry',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('key', models.CharField(max_length=32)),
                ('label', models.CharField(max_length=80)),
                ('target', models.CharField(max_length=64)),
                ('position', models.PositiveIntegerField()),
                ('visible', models.BooleanField(default=True)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entries', to='core.sitenavigationmenu')),
            ],
            options={
                'ordering': ('position', 'key'),
                'indexes': [models.Index(fields=['menu', 'position'], name='core_navigation_entry_order')],
                'constraints': [models.UniqueConstraint(fields=('menu', 'key'), name='core_navigation_entry_key_unique'), models.UniqueConstraint(fields=('menu', 'position'), name='core_navigation_entry_position_unique'), models.CheckConstraint(condition=models.Q(('position__gte', 1), ('position__lte', 12)), name='core_navigation_entry_position_bounded')],
            },
        ),
        migrations.CreateModel(
            name='SiteNavigationRevision',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('menu_key', models.CharField(max_length=32)),
                ('source', models.CharField(max_length=64)),
                ('revision', models.PositiveBigIntegerField()),
                ('entries', models.JSONField(default=list)),
                ('changed_by_ref', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('audit_event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='navigation_revisions', to='core.auditevent')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_navigation_revisions', to=settings.AUTH_USER_MODEL)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='history', to='core.sitenavigationmenu')),
            ],
            options={
                'ordering': ('menu_id', 'revision'),
                'base_manager_name': 'objects',
                'default_manager_name': 'objects',
                'indexes': [models.Index(fields=['menu_key', '-revision'], name='core_navigation_history_key')],
                'constraints': [models.UniqueConstraint(fields=('menu', 'revision'), name='core_navigation_history_revision_unique'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='core_navigation_history_revision_positive')],
            },
        ),
    ]
