# Generated by Django 6.0.8 on 2026-09-03 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_remove_operational_setting_revision'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='sponsorrevision',
            name='core_sponsor_history_key',
        ),
        migrations.RemoveConstraint(
            model_name='sponsorrevision',
            name='core_sponsor_history_revision_unique',
        ),
        migrations.RemoveConstraint(
            model_name='sponsorrevision',
            name='core_sponsor_history_revision_positive',
        ),
        migrations.DeleteModel(
            name='SponsorRevision',
        ),
    ]
