# Generated by Django 6.0.8 on 2026-09-04 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_sponsor_revision'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffsession',
            options={'ordering': ('-authenticated_at', '-id'), 'permissions': (('access_studio', 'Can access Studio'), ('browse_audit', 'Can browse Studio audit events'), ('export_audit', 'Can export Studio audit events'), ('execute_high_risk_fixture', 'Can execute the test-only high-risk fixture'))},
        ),
        migrations.AddField(
            model_name='staffsession',
            name='last_seen_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
