# Generated by Django 6.0.8 on 2026-09-16 11:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_copy_operational_settings_to_cb_config"),
    ]

    operations = [
        migrations.AddField(
            model_name="sponsor",
            name="featured_on_home",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "Show this sponsor on the homepage teaser, not only on /sponsors. "
                    "Reserved for current, long-term sponsors."
                ),
            ),
        ),
    ]
