# Generated by Django 6.0.8 on 2026-09-03 10:32

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DatamailerContactEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=320)),
                ('occurred_at', models.DateTimeField(blank=True, null=True)),
                ('audience', models.CharField(blank=True, max_length=120)),
                ('client', models.CharField(blank=True, max_length=120)),
                ('preference_key', models.CharField(blank=True, max_length=80)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('duplicate_count', models.PositiveIntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['email'], name='dm_events_email_idx'), models.Index(fields=['event_type', 'created_at'], name='dm_events_type_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='DatamailerOutboxDispatchRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('processed_count', models.PositiveIntegerField(default=0)),
                ('acked_count', models.PositiveIntegerField(default=0)),
                ('retrying_count', models.PositiveIntegerField(default=0)),
                ('failed_count', models.PositiveIntegerField(default=0)),
                ('last_error', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-started_at', '-id'],
                'indexes': [models.Index(fields=['status', 'started_at'], name='dm_outbox_run_status_idx')],
            },
        ),
        migrations.CreateModel(
            name='DatamailerOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_id', models.CharField(max_length=255, unique=True)),
                ('event_type', models.CharField(db_index=True, max_length=80)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('ordering_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('acked', 'Acked'), ('retrying', 'Retrying'), ('failed', 'Failed'), ('dead', 'Dead')], db_index=True, default='pending', max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('max_attempts', models.PositiveIntegerField(default=8)),
                ('next_attempt_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('last_attempt_at', models.DateTimeField(blank=True, null=True)),
                ('acked_at', models.DateTimeField(blank=True, null=True)),
                ('last_error', models.TextField(blank=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['status', 'next_attempt_at'], name='dm_outbox_status_next_idx'), models.Index(fields=['ordering_key', 'created_at'], name='dm_outbox_ordering_idx'), models.Index(fields=['event_type', 'created_at'], name='dm_outbox_type_created_idx')],
            },
        ),
        migrations.CreateModel(
            name='DatamailerSendAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('send_type', models.CharField(choices=[('transactional', 'Transactional'), ('recipient_list', 'Recipient list'), ('transient_recipient_list', 'Transient recipient list')], db_index=True, max_length=40)),
                ('status', models.CharField(choices=[('succeeded', 'Succeeded'), ('failed', 'Failed')], db_index=True, max_length=20)),
                ('idempotency_key', models.CharField(db_index=True, max_length=255)),
                ('template_key', models.CharField(blank=True, max_length=120)),
                ('category_tag', models.CharField(blank=True, max_length=80)),
                ('list_key', models.CharField(blank=True, db_index=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=120)),
                ('event', models.CharField(blank=True, max_length=120)),
                ('intended_count', models.PositiveIntegerField(default=0)),
                ('created_count', models.PositiveIntegerField(default=0)),
                ('enqueued_count', models.PositiveIntegerField(default=0)),
                ('skipped_count', models.PositiveIntegerField(default=0)),
                ('idempotent_replay_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('response_payload', models.JSONField(blank=True, default=dict)),
                ('occurred_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-occurred_at', '-id'],
                'indexes': [models.Index(fields=['status', 'occurred_at'], name='dm_send_status_occurred_idx'), models.Index(fields=['category_tag', 'occurred_at'], name='dm_send_category_occurred_idx'), models.Index(fields=['event', 'occurred_at'], name='dm_send_event_occurred_idx')],
                'constraints': [models.UniqueConstraint(fields=('send_type', 'idempotency_key'), name='dm_send_audit_type_idem_uniq')],
            },
        ),
    ]
