from django.urls import path, re_path

from . import legal_views, public_views

urlpatterns = [
    path("terms", legal_views.terms, name="terms"),
    path("terms/", public_views.permanent_public_redirect, {"target": "/terms"}),
    path("privacy", legal_views.privacy, name="privacy"),
    path("privacy/", public_views.permanent_public_redirect, {"target": "/privacy"}),
    path("impressum", legal_views.impressum, name="impressum"),
    path(
        "impressum/",
        public_views.permanent_public_redirect,
        {"target": "/impressum"},
    ),
    path("blog", public_views.collection_hub, {"collection": "articles"}, name="articles"),
    path("articles.html", public_views.permanent_public_redirect, {"target": "/blog"}),
    path("blog/", public_views.permanent_public_redirect, {"target": "/blog"}),
    path(
        "blog/<path:slug>/",
        public_views.permanent_detail_redirect,
        {"collection": "blog"},
    ),
    path(
        "blog/ai-dev-tools-zoomcamp.html",
        public_views.article_detail,
        {"slug": "ai-dev-tools-zoomcamp"},
        name="article-ai-dev-tools",
    ),
    path("blog/<path:slug>.html", public_views.article_detail, name="public-article"),
    path(
        "blog/<path:slug>",
        public_views.permanent_detail_redirect,
        {"collection": "blog"},
    ),
    path("podcast", public_views.podcast_hub, name="podcast"),
    path("podcast.html", public_views.permanent_public_redirect, {"target": "/podcast"}),
    path("podcast/", public_views.permanent_public_redirect, {"target": "/podcast"}),
    path(
        "podcast/<path:slug>/",
        public_views.permanent_detail_redirect,
        {"collection": "podcast"},
    ),
    path(
        "podcast/s24e06-how-to-build-ai-that-actually-ships-in-production.html",
        public_views.podcast_detail,
        {"slug": "s24e06-how-to-build-ai-that-actually-ships-in-production"},
        name="podcast-ai-production",
    ),
    path("podcast/<path:slug>.html", public_views.podcast_detail, name="public-podcast"),
    path(
        "podcast/<path:slug>",
        public_views.permanent_detail_redirect,
        {"collection": "podcast"},
    ),
    path("books", public_views.collection_hub, {"collection": "books"}, name="books"),
    path("books.html", public_views.permanent_public_redirect, {"target": "/books"}),
    path("books/", public_views.permanent_public_redirect, {"target": "/books"}),
    path(
        "books/<path:slug>/",
        public_views.permanent_detail_redirect,
        {"collection": "books"},
    ),
    path(
        "books/20250922-how-software-fails.html",
        public_views.book_detail,
        {"slug": "20250922-how-software-fails"},
        name="book-how-software-fails",
    ),
    path("books/<path:slug>.html", public_views.book_detail, name="public-book"),
    path(
        "books/<path:slug>",
        public_views.permanent_detail_redirect,
        {"collection": "books"},
    ),
    path(
        "people/<path:slug>/",
        public_views.permanent_detail_redirect,
        {"collection": "people"},
    ),
    path(
        "people/aleksandrkim.html",
        public_views.person_detail,
        {"slug": "aleksandrkim"},
        name="person-aleksandr-kim",
    ),
    path("people/<path:slug>.html", public_views.person_detail, name="public-person"),
    path(
        "people/<path:slug>",
        public_views.permanent_detail_redirect,
        {"collection": "people"},
    ),
    path("events", public_views.events, name="events"),
    path("events.html", public_views.permanent_public_redirect, {"target": "/events"}),
    path("events/", public_views.permanent_public_redirect, {"target": "/events"}),
    # The reviewed legacy map stores clean one-segment paths.  Keep the historical trailing-slash
    # spelling as an explicit route so redirect behavior never depends on APPEND_SLASH.
    re_path(
        r"^events/(?P<legacy_path>[^/]+)/$",
        public_views.event_legacy_redirect,
        name="public-event-legacy-trailing-slash",
    ),
    path(
        "events/<uuid:event_id>/<slug:slug>",
        public_views.event_detail,
        name="public-event",
    ),
    path(
        "events/<uuid:event_id>",
        public_views.event_detail_without_slug,
        name="public-event-without-slug",
    ),
    path(
        "events/<path:legacy_path>",
        public_views.event_legacy_redirect,
        name="public-event-legacy",
    ),
    path("wiki", public_views.wiki_hub, name="wiki-home"),
    path("wiki/", public_views.permanent_public_redirect, {"target": "/wiki"}),
    path("wiki/search-corpus.json", public_views.wiki_search_json, name="wiki-search-json"),
    path("wiki/graph", public_views.wiki_graph, name="wiki-graph"),
    path("wiki/graph/graph.json", public_views.wiki_graph_json, name="wiki-graph-json"),
    path("wiki/special-pages", public_views.wiki_special, name="wiki-special"),
    path(
        "wiki/special-pages/<slug:category>",
        public_views.wiki_special,
        name="wiki-special-category",
    ),
    path("wiki/feed.xml", public_views.wiki_feed, name="wiki-feed"),
    path("wiki/sitemap.xml", public_views.wiki_sitemap, name="wiki-sitemap"),
    path("wiki/robots.txt", public_views.wiki_robots, name="wiki-robots"),
    path("wiki/assets/<path:asset>", public_views.wiki_asset, name="wiki-asset"),
    path("wiki/<path:slug>", public_views.wiki_detail, name="public-wiki"),
    path("images/<path:media_path>", public_views.media, name="public-media"),
]
