# Generated by Django 6.0.8 on 2026-09-16 19:22

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models

# The old events_* Q&A tables, in the order their rows must be written so
# foreign keys land after the rows they point at.
_COPY_ORDER = (
    ("events_eventqnasession", "event_qna", "EventQnaSession"),
    ("events_eventqnaquestion", "event_qna", "EventQnaQuestion"),
    ("events_eventqnavote", "event_qna", "EventQnaVote"),
    ("events_eventqnacohostinvite", "event_qna", "EventQnaCohostInvite"),
    ("events_eventqnaratelimit", "event_qna", "EventQnaRateLimit"),
)


def copy_qna_rows_out_of_events(apps, schema_editor):
    """Copy Q&A rows out of the old events_* tables before events.0008 drops them.

    The old and new tables carry identical column names, so each row is read as
    a dict from the source table and written into the new model as-is.  On a
    fresh database where the events app never created its tables (or after the
    P5 rebuild removes it), this is a no-op.  Irreversible by design: the
    source tables are dropped immediately after, so there is nothing to copy
    back to.
    """

    connection = schema_editor.connection
    existing = set(connection.introspection.table_names(connection.cursor()))
    for table, app_label, model_name in _COPY_ORDER:
        if table not in existing:
            continue
        Model = apps.get_model(app_label, model_name)
        with connection.cursor() as cursor:
            columns = [
                column.name
                for column in connection.introspection.get_table_description(cursor, table)
            ]
            select = ", ".join(f'"{name}"' for name in columns)
            for row in cursor.execute(f'SELECT {select} FROM "{table}"').fetchall():
                Model.objects.create(**dict(zip(columns, row)))


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cb_jobs', '0002_jobintent_cb_jobs_external_id_unique'),
        ('events', '0007_delete_eventalias'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventQnaRateLimit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scope_digest', models.CharField(max_length=64)),
                ('window_seconds', models.PositiveIntegerField()),
                ('window_started_at', models.DateTimeField()),
                ('hits', models.PositiveIntegerField(default=0)),
            ],
            options={
                'indexes': [models.Index(fields=['scope_digest', 'window_seconds'], name='event_qna_rate_scope')],
                'constraints': [models.UniqueConstraint(fields=('scope_digest', 'window_seconds', 'window_started_at'), name='event_qna_rate_window_unique')],
            },
        ),
        migrations.CreateModel(
            name='EventQnaSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('state', models.CharField(choices=[('draft', 'Draft'), ('open', 'Open'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=16)),
                ('listed', models.BooleanField(default=True)),
                ('allow_names', models.BooleanField(default=True)),
                ('require_names', models.BooleanField(default=False)),
                ('answered_placement', models.CharField(choices=[('separate', 'Separate'), ('bottom', 'Bottom'), ('inline', 'Inline')], default='separate', max_length=16)),
                ('default_sort', models.CharField(choices=[('popular', 'Popular'), ('recent', 'Recent')], default='popular', max_length=16)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('retention_days', models.PositiveIntegerField(blank=True, default=365, null=True)),
                ('state_changed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('archive_delete_at', models.DateTimeField(blank=True, null=True)),
                ('q_total', models.PositiveBigIntegerField(default=0)),
                ('q_answered', models.PositiveBigIntegerField(default=0)),
                ('backend_key', models.CharField(default='native', max_length=32)),
                ('backend_reference', models.CharField(blank=True, max_length=255)),
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='qna_session', to='events.event')),
                ('provisioning_job', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='qna_provisioning_session', to='cb_jobs.jobintent')),
            ],
            options={
                'ordering': ('event_id', 'id'),
                'permissions': (('view_event_qna', 'Can view event-linked Q&A'), ('manage_event_qna', 'Can manage event-linked Q&A')),
            },
        ),
        migrations.CreateModel(
            name='EventQnaQuestion',
            fields=[
                ('question_id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('text', models.CharField(max_length=315)),
                ('author_name', models.CharField(blank=True, default='', max_length=60)),
                ('participant_digest', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('visible', 'Visible'), ('answered', 'Answered'), ('deleted', 'Deleted')], default='visible', max_length=16)),
                ('score', models.PositiveIntegerField(default=0)),
                ('pinned', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='event_qna.eventqnasession')),
            ],
            options={
                'ordering': ('-pinned', '-score', 'created_at', 'question_id'),
            },
        ),
        migrations.CreateModel(
            name='EventQnaCohostInvite',
            fields=[
                ('invite_id', models.CharField(editable=False, max_length=26, primary_key=True, serialize=False)),
                ('name', models.SlugField(max_length=48)),
                ('passcode_digest', models.CharField(max_length=128)),
                ('created_by_ref', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cohost_invites', to='event_qna.eventqnasession')),
            ],
            options={
                'ordering': ('name', 'invite_id'),
            },
        ),
        migrations.CreateModel(
            name='EventQnaVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('participant_digest', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='event_qna.eventqnaquestion')),
            ],
        ),
        migrations.AddConstraint(
            model_name='eventqnasession',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='event_qna_session_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='eventqnasession',
            constraint=models.CheckConstraint(condition=models.Q(('backend_key__gt', '')), name='event_qna_session_backend_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='eventqnasession',
            constraint=models.CheckConstraint(condition=models.Q(('q_answered__lte', models.F('q_total'))), name='event_qna_answered_lte_total'),
        ),
        migrations.AddConstraint(
            model_name='eventqnasession',
            constraint=models.CheckConstraint(condition=models.Q(('retention_days__isnull', True), ('retention_days__gte', 1), _connector='OR'), name='event_qna_retention_positive'),
        ),
        migrations.AddIndex(
            model_name='eventqnaquestion',
            index=models.Index(fields=['session', 'status', 'created_at'], name='event_qna_q_status_time'),
        ),
        migrations.AddIndex(
            model_name='eventqnaquestion',
            index=models.Index(fields=['session', 'pinned', 'score'], name='event_qna_q_rank'),
        ),
        migrations.AddConstraint(
            model_name='eventqnaquestion',
            constraint=models.CheckConstraint(condition=models.Q(('text__gt', ''), ('participant_digest__gt', '')), name='event_qna_question_content_nonempty'),
        ),
        migrations.AddConstraint(
            model_name='eventqnaquestion',
            constraint=models.CheckConstraint(condition=models.Q(('score__gte', 0)), name='event_qna_question_score_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='eventqnacohostinvite',
            constraint=models.UniqueConstraint(fields=('session', 'name'), name='event_qna_cohost_name_unique'),
        ),
        migrations.AddConstraint(
            model_name='eventqnavote',
            constraint=models.UniqueConstraint(fields=('question', 'participant_digest'), name='event_qna_vote_participant_unique'),
        ),
        migrations.RunPython(copy_qna_rows_out_of_events, migrations.RunPython.noop),
    ]
