# Generated by Django 6.0.8 on 2026-09-03 10:32

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('student', 'Student'), ('instructor', 'Instructor')], default='student', max_length=10)),
                ('certificate_name', models.CharField(blank=True, help_text='Your actual name that will appear on your certificates', max_length=255, null=True, verbose_name='Certificate name')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Country')),
                ('region', models.CharField(blank=True, max_length=100, verbose_name='Region')),
                ('registration_role', models.CharField(blank=True, help_text='Role last used on a course registration form', max_length=40, verbose_name='Registration role')),
                ('github_url', models.URLField(blank=True, null=True, verbose_name='GitHub URL')),
                ('linkedin_url', models.URLField(blank=True, null=True, verbose_name='LinkedIn URL')),
                ('personal_website_url', models.URLField(blank=True, null=True, verbose_name='Personal website URL')),
                ('about_me', models.TextField(blank=True, null=True, verbose_name='About me')),
                ('dark_mode', models.BooleanField(default=False, help_text='Enable dark mode theme', verbose_name='Dark mode')),
                ('preferred_timezone', models.CharField(blank=True, default='', help_text='IANA timezone used for backend-rendered deadlines and notification emails.', max_length=100, verbose_name='Preferred timezone')),
                ('home_dismissals', models.JSONField(blank=True, default=dict, help_text='Allowlisted signed-in-home checklist/nudge keys this member has already skipped, completed, or dismissed.', verbose_name='Home dismissals')),
                ('normalized_email', models.EmailField(blank=True, db_index=True, editable=False, max_length=254, null=True)),
                ('identity_state', models.CharField(choices=[('legacy', 'Legacy-compatible'), ('active', 'Verified active identity'), ('quarantined', 'Needs identity review'), ('absorbed', 'Absorbed into a survivor')], db_index=True, default='legacy', max_length=16)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AccountIdentityAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_user_id', models.PositiveBigIntegerField(unique=True)),
                ('source_snapshot_id', models.CharField(max_length=64)),
                ('mapping_checksum', models.CharField(max_length=64)),
                ('review_reference', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('survivor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='identity_aliases', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('source_user_id',),
            },
        ),
        migrations.CreateModel(
            name='AccountIdentityQuarantine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fingerprint', models.CharField(max_length=64, unique=True)),
                ('source_snapshot_id', models.CharField(max_length=64)),
                ('source_user_ids', models.JSONField(default=list)),
                ('reason_codes', models.JSONField(default=list)),
                ('status', models.CharField(choices=[('open', 'Open'), ('resolved', 'Resolved')], default='open', max_length=16)),
                ('resolution_reference', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'indexes': [models.Index(fields=['status', 'created_at'], name='accounts_quarantine_status')],
            },
        ),
        migrations.CreateModel(
            name='AccountReconciliationRun',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_snapshot_id', models.CharField(max_length=64)),
                ('mapping_checksum', models.CharField(max_length=64)),
                ('mode', models.CharField(choices=[('apply', 'Apply'), ('rollback_check', 'Rollback check')], max_length=16)),
                ('source_account_count', models.PositiveBigIntegerField()),
                ('survivor_account_count', models.PositiveBigIntegerField()),
                ('alias_count', models.PositiveBigIntegerField(default=0)),
                ('quarantine_count', models.PositiveBigIntegerField(default=0)),
                ('relationship_counts', models.JSONField(default=dict)),
                ('relationship_checksums', models.JSONField(default=dict)),
                ('report_checksum', models.CharField(max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('created_at', 'id'),
                'constraints': [models.UniqueConstraint(fields=('source_snapshot_id', 'mapping_checksum', 'mode'), name='accounts_reconciliation_run_unique')],
            },
        ),
        migrations.CreateModel(
            name='Token',
            fields=[
                ('key', models.CharField(max_length=40, primary_key=True, serialize=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('identity_state', 'active'), ('normalized_email__isnull', False)), fields=('normalized_email',), name='accounts_active_normalized_email_unique'),
        ),
        migrations.AddIndex(
            model_name='accountidentityalias',
            index=models.Index(fields=['survivor', 'source_user_id'], name='accounts_alias_survivor_source'),
        ),
        migrations.AddConstraint(
            model_name='accountidentityalias',
            constraint=models.CheckConstraint(condition=models.Q(('source_user_id', models.F('survivor_id')), _negated=True), name='accounts_identity_alias_distinct'),
        ),
    ]
