# Generated by Django 6.0.8 on 2026-09-03 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpLearnerImportProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=64, unique=True)),
                ('last_source_id', models.BigIntegerField(default=0)),
                ('rows_written', models.PositiveBigIntegerField(default=0)),
                ('rows_skipped', models.PositiveBigIntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('table',),
            },
        ),
        migrations.AddField(
            model_name='customuser',
            name='cmp_source_user_id',
            field=models.BigIntegerField(blank=True, db_index=True, editable=False, null=True, verbose_name='CMP source user ID'),
        ),
        migrations.AddConstraint(
            model_name='customuser',
            constraint=models.UniqueConstraint(condition=models.Q(('cmp_source_user_id__isnull', False)), fields=('cmp_source_user_id',), name='accounts_cmp_source_user_id_unique'),
        ),
    ]
