# Generated by Django 6.0.8 on 2026-09-03 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_cmp_learner_import_progress'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='newsletter_subscribed',
            field=models.BooleanField(default=True, help_text='Whether this account receives newsletter email.', verbose_name='Newsletter subscribed'),
        ),
    ]
