# Generated by Django 6.0.8 on 2026-09-03 18:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_customuser_newsletter_subscribed'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='user',
            name='accounts_cmp_source_user_id_unique',
        ),
        migrations.RemoveField(
            model_name='user',
            name='cmp_source_user_id',
        ),
    ]
