# Generated by Django 6.0.8 on 2026-09-08 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_cmp_source_user_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpLearnerClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_id', models.BigIntegerField(unique=True)),
                ('user_id', models.BigIntegerField(db_index=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('source_id',),
            },
        ),
        migrations.CreateModel(
            name='CmpLearnerImportBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32, unique=True)),
                ('schema_version', models.IntegerField()),
                ('importer_version', models.CharField(max_length=64)),
                ('source_sha256', models.CharField(max_length=64)),
                ('target_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
