# Generated by Django 6.0.8 on 2026-09-09 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_cmplearnerclaim_cmplearnerimportbinding'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email_course_updates',
            field=models.BooleanField(blank=True, help_text='Mail category opt-out for general course-related emails. Unset means allowed.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_deadline_reminders',
            field=models.BooleanField(blank=True, help_text='Mail category opt-out for deadline reminders. Unset means allowed.', null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_submission_confirmations',
            field=models.BooleanField(blank=True, help_text='Mail category opt-out for submission confirmations and score emails. Unset means allowed.', null=True),
        ),
    ]
