# Generated by Django 6.0.8 on 2026-09-09 20:07
# Renumbered from 0007 after D3.1 landed 0007-0009 on main.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_rename_user_tables"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="email_course_updates",
            field=models.BooleanField(
                blank=True,
                help_text="Mail category opt-out for general course-related emails. Unset means allowed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_deadline_reminders",
            field=models.BooleanField(
                blank=True,
                help_text="Mail category opt-out for deadline reminders. Unset means allowed.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="email_submission_confirmations",
            field=models.BooleanField(
                blank=True,
                help_text="Mail category opt-out for submission confirmations and score emails. Unset means allowed.",
                null=True,
            ),
        ),
    ]
