# Generated by Django 6.0.8 on 2026-09-02 20:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_backfill_normalized_identity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='home_dismissals',
            field=models.JSONField(blank=True, default=dict, help_text='Allowlisted signed-in-home checklist/nudge keys this member has already skipped, completed, or dismissed.', verbose_name='Home dismissals'),
        ),
    ]
