"""Reviewed deployment targets for the release pipeline.

A deployment target is a *named, reviewed profile* of one applied website stack:
its account and region, the hostname it serves, the physical resource namespace
its ECS/ECR/IAM identifiers derive from, the Django settings module and
``DTC_ENVIRONMENT`` its tasks run with, and its desired counts.  Every gate in
``deploy/`` reads its expectations from the selected target instead of pinning
one deployment's strings, so moving the pipeline to another reviewed stack is a
configuration change rather than an edit spread across the release tooling.

The selection stays closed, following the precedent set by
``deploy.development_target``:

* the allowlist lives in code (:data:`DEPLOYMENT_TARGETS`);
* ``DTC_DEPLOYMENT_TARGET`` only *selects* a member of that allowlist, so a
  mistyped or injected value fails at import rather than widening the boundary;
* a retired target can still be read for historical evidence but can never be
  selected for a deployment; and
* every expectation a target publishes is still compared exactly, so a stack
  that disagrees with its own reviewed profile fails closed with the name of the
  value that disagreed.

Some identifiers are generated by AWS and cannot be known before the stack is
applied -- the KMS key ARN, the hosted zone id, subnet and security-group ids,
and the load-balancer target-group ARN.  They are never invented here.  A target
either *pins* the reviewed value it was verified against (the historical sandbox
does) or declares the strict shape the supplied value must have
(:data:`SUPPLIED_IDENTIFIERS`), scoped to that target's own account, region and
namespace.  Supplying another deployment's subnet or a wrong-account key ARN is
therefore still rejected.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import sys
from collections.abc import Mapping
from dataclasses import dataclass, field
from typing import Any

from deploy.contracts import ReleaseContractError

DEPLOYMENT_TARGET_VARIABLE = "DTC_DEPLOYMENT_TARGET"
#: The target the pipeline deploys when nothing selects another one.  The
#: sandbox stack this repository used to deploy was destroyed on 2026-09-02, so
#: the production stack is the only deployable reviewed target.
DEFAULT_DEPLOYMENT_TARGET = "website-production"

_JSON_LIST_VALUES = frozenset({"CONTAINER_NAMES", "ECS_SUBNET_IDS", "ECS_SECURITY_GROUP_IDS"})

#: Container names are fixed by ``modules/django-website`` for every stack.
CONTAINER_NAMES = '{"migration":"migration","web":"web","worker":"worker"}'


class DeploymentTargetError(RuntimeError):
    """The configured deployment target is not a reviewed, deployable target."""


@dataclass(frozen=True, slots=True)
class CpuArchitecture:
    """One ``runtime_platform.cpu_architecture`` a Fargate task can declare.

    ECS does not reject a task definition whose image was built for the other
    architecture.  It starts the task, the kernel refuses the binary, and the
    task dies with nothing useful in its log, so the release pipeline has to
    build, assert and publish exactly the architecture the task definition
    declares.  Every name the pipeline needs for one architecture is derived
    here from that single Terraform value rather than repeated as a literal.
    """

    #: ``docker buildx build --platform`` value.
    build_platform: str
    #: ``docker image inspect --format '{{.Architecture}}'`` value.
    image_architecture: str
    #: ``platform.machine()`` of a host that runs this architecture natively.
    runner_machine: str
    #: GitHub-hosted runner label that executes this architecture natively.
    runner_label: str


#: The ``cpu_architecture`` values ``modules/django-website`` accepts.  Keep the
#: keys exactly the strings its ``validation`` block allows.
CPU_ARCHITECTURES: Mapping[str, CpuArchitecture] = {
    "ARM64": CpuArchitecture(
        build_platform="linux/arm64",
        image_architecture="arm64",
        runner_machine="aarch64",
        runner_label="ubuntu-24.04-arm",
    ),
    "X86_64": CpuArchitecture(
        build_platform="linux/amd64",
        image_architecture="amd64",
        runner_machine="x86_64",
        runner_label="ubuntu-latest",
    ),
}


@dataclass(frozen=True, slots=True)
class SuppliedIdentifier:
    """A physical value AWS generates, which arrives as a validated input."""

    name: str
    #: Where the owner obtains the value.  Recorded so an operator does not have
    #: to guess, and so a reviewer can tell an input apart from a reviewed pin.
    source: str
    #: ``str.format`` template evaluated against the target, giving a pattern
    #: scoped to that target's own account, region and namespace.
    pattern_template: str

    def pattern(self, target: DeploymentTarget) -> re.Pattern[str]:
        return re.compile(
            self.pattern_template.format(
                account=re.escape(target.aws_account_id),
                region=re.escape(target.aws_region),
                namespace=re.escape(target.resource_namespace),
            )
        )


SUPPLIED_IDENTIFIERS: tuple[SuppliedIdentifier, ...] = (
    SuppliedIdentifier(
        name="HOSTED_ZONE_ID",
        source="terraform output hosted_zone_id (Route 53 assigns it at zone creation)",
        pattern_template=r"Z[A-Z0-9]{{4,30}}",
    ),
    SuppliedIdentifier(
        name="KMS_KEY_ARN",
        source="terraform output kms_key_arn (KMS assigns the key id at creation)",
        pattern_template=(
            r"arn:aws:kms:{region}:{account}:key/"
            r"[0-9a-f]{{8}}-[0-9a-f]{{4}}-[0-9a-f]{{4}}-[0-9a-f]{{4}}-[0-9a-f]{{12}}"
        ),
    ),
    SuppliedIdentifier(
        name="ECS_SUBNET_IDS",
        source="terraform output task_subnet_ids (VPC assigns the subnet ids)",
        pattern_template=r'\["subnet-[0-9a-f]{{8,17}}"(?:,"subnet-[0-9a-f]{{8,17}}")*\]',
    ),
    SuppliedIdentifier(
        name="ECS_SECURITY_GROUP_IDS",
        source="terraform output task_security_group_ids (EC2 assigns the group ids)",
        pattern_template=r'\["sg-[0-9a-f]{{8,17}}"(?:,"sg-[0-9a-f]{{8,17}}")*\]',
    ),
    SuppliedIdentifier(
        name="WEB_TARGET_GROUP_ARN",
        source="terraform output web_target_group_arn (ELB assigns the ARN suffix)",
        pattern_template=(
            r"arn:aws:elasticloadbalancing:{region}:{account}:"
            r"targetgroup/{namespace}-web/[0-9a-f]{{16}}"
        ),
    ),
)
_SUPPLIED_BY_NAME = {identifier.name: identifier for identifier in SUPPLIED_IDENTIFIERS}


@dataclass(frozen=True, slots=True)
class DeploymentTarget:
    """One reviewed deployment target.

    Every field is a value a reviewer can read off the applied Terraform root,
    except :attr:`pinned_identifiers`, which records AWS-generated values that
    have already been reviewed for this target.
    """

    name: str
    aws_account_id: str
    aws_region: str
    hostname: str
    #: ``var.name`` of the ``modules/django-website`` instantiation.  Every ECS,
    #: ECR, IAM and Secrets Manager identifier below derives from it.
    resource_namespace: str
    settings_module: str
    dtc_environment: str
    #: The origin public canonical links point at.  A non-indexable staging or
    #: development host still declares the production apex (spec 02).
    canonical_origin: str
    #: Whether the deployed application marks every response ``noindex``.
    robots_noindex: bool
    github_environment: str
    terraform_root: str
    terraform_state_bucket: str
    #: ``task_cpu_architecture`` of this target's Terraform root, which
    #: ``modules/django-website`` puts in every task definition's
    #: ``runtime_platform``.  The release image is built for exactly this.
    task_cpu_architecture: str
    assign_public_ip: bool
    web_desired_count: int
    worker_desired_count: int
    resource_project_tag: str
    resource_environment_tag: str
    web_concurrency: str = "2"
    #: A retired target keeps its reviewed values so recorded evidence still
    #: resolves, but can never be selected for a deployment.
    retired: bool = False
    #: Reviewed exact values for AWS-generated identifiers, where a stack has
    #: already been applied and verified.  Anything absent here must be supplied
    #: at deploy time and is shape-validated instead.
    pinned_identifiers: Mapping[str, str] = field(default_factory=dict)

    def __post_init__(self) -> None:
        unknown = sorted(set(self.pinned_identifiers) - set(_SUPPLIED_BY_NAME))
        if unknown:
            raise DeploymentTargetError(
                f"{self.name} pins identifiers that are not supplied values: {', '.join(unknown)}"
            )
        if self.task_cpu_architecture not in CPU_ARCHITECTURES:
            raise DeploymentTargetError(
                f"{self.name} declares an unreviewed task CPU architecture: "
                f"{self.task_cpu_architecture!r}"
            )

    # -- release image architecture ----------------------------------------

    @property
    def cpu_architecture(self) -> CpuArchitecture:
        """The names derived from this target's declared task CPU architecture."""

        return CPU_ARCHITECTURES[self.task_cpu_architecture]

    @property
    def build_platform(self) -> str:
        return self.cpu_architecture.build_platform

    @property
    def image_architecture(self) -> str:
        return self.cpu_architecture.image_architecture

    @property
    def runner_machine(self) -> str:
        return self.cpu_architecture.runner_machine

    @property
    def runner_label(self) -> str:
        return self.cpu_architecture.runner_label

    # -- derived physical identifiers -------------------------------------

    @property
    def origin(self) -> str:
        return f"https://{self.hostname}"

    @property
    def terraform_state_key(self) -> str:
        return f"{self.terraform_root}/terraform.tfstate"

    @property
    def ecr_repository_name(self) -> str:
        return self.resource_namespace

    @property
    def ecr_repository_uri(self) -> str:
        return (
            f"{self.aws_account_id}.dkr.ecr.{self.aws_region}.amazonaws.com/"
            f"{self.ecr_repository_name}"
        )

    @property
    def ecs_cluster_arn(self) -> str:
        return (
            f"arn:aws:ecs:{self.aws_region}:{self.aws_account_id}:cluster/{self.resource_namespace}"
        )

    @property
    def web_service_name(self) -> str:
        return f"{self.resource_namespace}-web"

    @property
    def worker_service_name(self) -> str:
        return f"{self.resource_namespace}-worker"

    @property
    def web_task_family(self) -> str:
        return self.web_service_name

    @property
    def worker_task_family(self) -> str:
        return self.worker_service_name

    @property
    def migration_task_family(self) -> str:
        return f"{self.resource_namespace}-migration"

    @property
    def task_families(self) -> frozenset[str]:
        return frozenset(
            {self.web_task_family, self.worker_task_family, self.migration_task_family}
        )

    def _role_arn(self, suffix: str) -> str:
        return f"arn:aws:iam::{self.aws_account_id}:role/{self.resource_namespace}-{suffix}"

    @property
    def publisher_role_arn(self) -> str:
        return self._role_arn("github-publisher")

    @property
    def deployer_role_arn(self) -> str:
        return self._role_arn("github-deployer")

    @property
    def task_role_arn(self) -> str:
        return self._role_arn("task-application")

    @property
    def execution_role_arn(self) -> str:
        return self._role_arn("task-execution")

    def _secret_arn_pattern(self, container: str) -> re.Pattern[str]:
        return re.compile(
            rf"^arn:aws:secretsmanager:{re.escape(self.aws_region)}:{re.escape(self.aws_account_id)}"
            rf":secret:{re.escape(self.resource_namespace)}/{re.escape(container)}"
            rf"-[A-Za-z0-9]{{6}}$"
        )

    @property
    def database_secret_arn_pattern(self) -> re.Pattern[str]:
        return self._secret_arn_pattern("database-url")

    @property
    def django_secret_arn_pattern(self) -> re.Pattern[str]:
        return self._secret_arn_pattern("django-secret-key")

    def task_definition_arn_prefix(self, family: str) -> str:
        if family not in self.task_families:
            raise ReleaseContractError(f"task family is outside the {self.name} deployment target")
        return f"arn:aws:ecs:{self.aws_region}:{self.aws_account_id}:task-definition/{family}:"

    # -- runtime contract --------------------------------------------------

    @property
    def safety_environment(self) -> dict[str, str]:
        """Environment that keeps the adopted Datamailer client inert."""

        return {
            "DATAMAILER_SYNC_ON_USER_CREATE": "0",
            "DATAMAILER_OUTBOX_DISPATCH_IMMEDIATELY": "0",
            "DATAMAILER_TRANSACTIONAL_DRY_RUN": "1",
            "DATAMAILER_URL": "",
            "DATAMAILER_API_KEY": "",
        }

    @property
    def public_media_environment(self) -> dict[str, str]:
        """Where a deployed workload reads the public projection images from."""

        return {
            "PUBLIC_MEDIA_STORE_BACKEND": "s3",
            "PUBLIC_MEDIA_S3_BUCKET": "dtc-website-media",
            "PUBLIC_MEDIA_S3_REGION": self.aws_region,
        }

    @property
    def fixed_nonsecret_environment(self) -> dict[str, str]:
        """The exact non-secret container environment this target deploys."""

        return {
            "CANONICAL_ORIGIN": self.canonical_origin,
            "DJANGO_ALLOWED_HOSTS": self.hostname,
            "DJANGO_CSRF_TRUSTED_ORIGINS": self.origin,
            "DJANGO_SETTINGS_MODULE": self.settings_module,
            "DTC_ENVIRONMENT": self.dtc_environment,
            "OBSERVABILITY_EVENT_BACKENDS": "log",
            "WEB_CONCURRENCY": self.web_concurrency,
            "AWS_DEFAULT_REGION": self.aws_region,
            "AWS_REGION": self.aws_region,
            **self.public_media_environment,
            **self.safety_environment,
        }

    # -- supplied identifiers ---------------------------------------------

    def identifier_disagreement(self, name: str, value: str | None) -> str | None:
        """Return a reason when ``value`` is not this target's identifier."""

        identifier = _SUPPLIED_BY_NAME.get(name)
        if identifier is None:
            raise DeploymentTargetError(f"{name} is not a supplied deployment identifier")
        if not value:
            return "is missing"
        pinned = self.pinned_identifiers.get(name)
        normalized = _normalize_json(name, value)
        if pinned is not None:
            if normalized != _normalize_json(name, pinned):
                return "differs from the reviewed value"
            return None
        if identifier.pattern(self).fullmatch(normalized) is None:
            return f"is not a {self.name} {name.lower().replace('_', ' ')}"
        # A subnet, security-group or hosted-zone id carries no account, so its
        # shape alone cannot tell one deployment's from another's.  Any value
        # another reviewed target pinned is therefore rejected by name, and the
        # remaining protection is that the deployer role can only act inside its
        # own account.
        for other in DEPLOYMENT_TARGETS.values():
            if other.name == self.name:
                continue
            reviewed = other.pinned_identifiers.get(name)
            if reviewed is not None and _normalize_json(name, reviewed) == normalized:
                return f"belongs to the {other.name} deployment target"
        return None


def _normalize_json(name: str, value: str) -> str:
    if name not in _JSON_LIST_VALUES:
        return value
    try:
        return json.dumps(json.loads(value), separators=(",", ":"), sort_keys=True)
    except json.JSONDecodeError as error:
        raise ReleaseContractError(f"deployment variable {name} is not valid JSON") from error


# The destroyed sandbox stack.  Retained, not deleted: the Gate-B and release
# evidence recorded in this repository was verified against exactly these
# values, and deleting the profile would orphan that history.  It is retired, so
# it can be read but never deployed.
_WEBSITE_SANDBOX = DeploymentTarget(
    name="website-sandbox",
    retired=True,
    aws_account_id="817685572750",
    aws_region="eu-west-1",
    hostname="web.dtcdev.click",
    resource_namespace="website-sandbox",
    settings_module="website.settings.development",
    dtc_environment="development",
    canonical_origin="https://datatalks.club",
    robots_noindex=True,
    github_environment="sandbox",
    terraform_root="sandbox/website",
    terraform_state_bucket="datamailer-sandbox-817685572750-us-east-1-tfstate",
    # sandbox/website ran on Intel Fargate.  Recorded as it was applied so the
    # retired profile still explains the amd64 images this repository published
    # to it; it can never be selected, so it can never build one again.
    task_cpu_architecture="X86_64",
    assign_public_ip=True,
    web_desired_count=1,
    worker_desired_count=1,
    resource_project_tag="website",
    resource_environment_tag="sandbox",
    pinned_identifiers={
        "HOSTED_ZONE_ID": "Z05963572WVWFHDQZH5NE",
        "KMS_KEY_ARN": (
            "arn:aws:kms:eu-west-1:817685572750:key/b9181223-d870-4bae-92d2-fc28b7813887"
        ),
        "ECS_SUBNET_IDS": '["subnet-0614747082352aecf","subnet-001e1960dcfc4fa60"]',
        "ECS_SECURITY_GROUP_IDS": '["sg-0641397bd1c2083f0"]',
    },
)

# The production stack, reviewed against DataTalksClub/aws-infra main/website.
# prod.datatalks.club is staging for its whole life: it stays non-indexable and
# declares the production apex canonical, so the corpus cannot be indexed twice
# while the apex still serves the legacy site.  Its AWS-generated identifiers
# are supplied at deploy time and are deliberately not pinned here.
_WEBSITE_PRODUCTION = DeploymentTarget(
    name="website-production",
    aws_account_id="387546586013",
    aws_region="eu-west-1",
    hostname="prod.datatalks.club",
    resource_namespace="website-production",
    settings_module="website.settings.production",
    dtc_environment="production",
    canonical_origin="https://datatalks.club",
    robots_noindex=True,
    github_environment="production",
    terraform_root="main/website",
    terraform_state_bucket="dtc-terraform-state-387546586013",
    # main/website runs on Graviton: task_cpu_architecture = "ARM64", which is
    # about 20% cheaper on Fargate.  scripts/verify_development_seo_terraform.py
    # reads that value back out of the trusted Terraform source, so this and the
    # applied stack cannot diverge without a check failing.
    task_cpu_architecture="ARM64",
    assign_public_ip=False,
    web_desired_count=2,
    worker_desired_count=1,
    resource_project_tag="website",
    resource_environment_tag="production",
)

#: Every reviewed deployment target, deployable or retired.
DEPLOYMENT_TARGETS: Mapping[str, DeploymentTarget] = {
    target.name: target for target in (_WEBSITE_PRODUCTION, _WEBSITE_SANDBOX)
}


def registered_target(name: str) -> DeploymentTarget:
    """Return a reviewed target by name, including retired ones."""

    try:
        return DEPLOYMENT_TARGETS[name]
    except KeyError:
        raise DeploymentTargetError(f"{name!r} is not a reviewed deployment target") from None


def deployment_target(environ: Mapping[str, str] | None = None) -> DeploymentTarget:
    """Return the selected deployment target, failing closed on anything else."""

    values = os.environ if environ is None else environ
    name = values.get(DEPLOYMENT_TARGET_VARIABLE) or DEFAULT_DEPLOYMENT_TARGET
    target = registered_target(name)
    if target.retired:
        raise DeploymentTargetError(f"deployment target {name!r} is retired and cannot be deployed")
    return target


#: The target every ``deploy`` module binds to.  Resolved once, at import, so a
#: process cannot change deployment target part-way through a release.
SELECTED_TARGET = deployment_target()


# -- environment validation ------------------------------------------------

_EXACT_EXPECTATIONS = {
    "AWS_REGION": lambda target: target.aws_region,
    "ECR_REPOSITORY_NAME": lambda target: target.ecr_repository_name,
    "ECR_REPOSITORY_URI": lambda target: target.ecr_repository_uri,
    "PUBLISHER_ROLE_ARN": lambda target: target.publisher_role_arn,
    "DEPLOYER_ROLE_ARN": lambda target: target.deployer_role_arn,
    "TASK_ROLE_ARN": lambda target: target.task_role_arn,
    "EXECUTION_ROLE_ARN": lambda target: target.execution_role_arn,
    "ECS_CLUSTER_ARN": lambda target: target.ecs_cluster_arn,
    "WEB_SERVICE_NAME": lambda target: target.web_service_name,
    "WORKER_SERVICE_NAME": lambda target: target.worker_service_name,
    "WEB_FAMILY": lambda target: target.web_task_family,
    "WORKER_FAMILY": lambda target: target.worker_task_family,
    "MIGRATION_FAMILY": lambda target: target.migration_task_family,
    "CONTAINER_NAMES": lambda target: CONTAINER_NAMES,
    "ASSIGN_PUBLIC_IP": lambda target: "true" if target.assign_public_ip else "false",
    "WEB_DESIRED_COUNT": lambda target: str(target.web_desired_count),
    "WORKER_DESIRED_COUNT": lambda target: str(target.worker_desired_count),
    "PROJECT_TAG": lambda target: target.resource_project_tag,
    "ENVIRONMENT_TAG": lambda target: target.resource_environment_tag,
}

#: Which values each workflow role profile must present.  ``supplied`` names are
#: AWS-generated inputs; the rest are compared against the target exactly.
_ROLE_PROFILES: dict[str, dict[str, tuple[str, ...]]] = {
    "publisher": {
        "exact": ("AWS_REGION", "ECR_REPOSITORY_URI", "ECR_REPOSITORY_NAME", "PUBLISHER_ROLE_ARN"),
        "supplied": (),
    },
    "publisher-probe": {
        "exact": ("AWS_REGION", "ECR_REPOSITORY_NAME", "PUBLISHER_ROLE_ARN"),
        "supplied": ("HOSTED_ZONE_ID", "KMS_KEY_ARN"),
    },
    "deployer-probe": {
        "exact": (
            "AWS_REGION",
            "DEPLOYER_ROLE_ARN",
            "ECR_REPOSITORY_NAME",
            "ECS_CLUSTER_ARN",
            "WEB_SERVICE_NAME",
            "WORKER_SERVICE_NAME",
            "WEB_FAMILY",
            "WORKER_FAMILY",
            "MIGRATION_FAMILY",
        ),
        "supplied": ("HOSTED_ZONE_ID", "KMS_KEY_ARN", "WEB_TARGET_GROUP_ARN"),
    },
    "main-claim-probe": {
        "exact": ("AWS_REGION", "DEPLOYER_ROLE_ARN", "PUBLISHER_ROLE_ARN"),
        "supplied": (),
    },
    "environment-claim-probe": {
        "exact": ("AWS_REGION", "PUBLISHER_ROLE_ARN"),
        "supplied": (),
    },
    "prior-capture": {
        "exact": (
            "AWS_REGION",
            "ECR_REPOSITORY_URI",
            "DEPLOYER_ROLE_ARN",
            "ECS_CLUSTER_ARN",
            "WEB_SERVICE_NAME",
            "WORKER_SERVICE_NAME",
            "WEB_FAMILY",
            "WORKER_FAMILY",
            "MIGRATION_FAMILY",
            "CONTAINER_NAMES",
            "TASK_ROLE_ARN",
            "EXECUTION_ROLE_ARN",
            "ASSIGN_PUBLIC_IP",
            "WEB_DESIRED_COUNT",
            "WORKER_DESIRED_COUNT",
        ),
        "supplied": ("ECS_SUBNET_IDS", "ECS_SECURITY_GROUP_IDS", "WEB_TARGET_GROUP_ARN"),
    },
    "deployer": {
        "exact": (
            "AWS_REGION",
            "ECR_REPOSITORY_URI",
            "DEPLOYER_ROLE_ARN",
            "ECS_CLUSTER_ARN",
            "WEB_SERVICE_NAME",
            "WORKER_SERVICE_NAME",
            "WEB_FAMILY",
            "WORKER_FAMILY",
            "MIGRATION_FAMILY",
            "CONTAINER_NAMES",
            "TASK_ROLE_ARN",
            "EXECUTION_ROLE_ARN",
            "ASSIGN_PUBLIC_IP",
            "WEB_DESIRED_COUNT",
            "WORKER_DESIRED_COUNT",
            "PROJECT_TAG",
            "ENVIRONMENT_TAG",
        ),
        "supplied": ("ECS_SUBNET_IDS", "ECS_SECURITY_GROUP_IDS", "WEB_TARGET_GROUP_ARN"),
    },
}
ROLE_PROFILES: tuple[str, ...] = tuple(sorted(_ROLE_PROFILES))


def role_profile_expectations(profile: str, target: DeploymentTarget) -> dict[str, str]:
    """Return the exact values ``profile`` must present for ``target``."""

    try:
        names = _ROLE_PROFILES[profile]["exact"]
    except KeyError as error:
        raise ReleaseContractError("unknown deployment role profile") from error
    return {name: _EXACT_EXPECTATIONS[name](target) for name in names}


def validate_environment(
    profile: str,
    values: Mapping[str, str],
    target: DeploymentTarget | None = None,
) -> None:
    """Fail closed when workflow variables select a different physical deployment."""

    resolved = SELECTED_TARGET if target is None else target
    expected = role_profile_expectations(profile, resolved)
    supplied = _ROLE_PROFILES[profile]["supplied"]

    missing = sorted(name for name in (*expected, *supplied) if not values.get(name))
    if missing:
        raise ReleaseContractError(
            f"{resolved.name} configuration is missing required values: " + ", ".join(missing)
        )
    mismatched = {
        name
        for name, expected_value in expected.items()
        if _normalize_json(name, values[name]) != _normalize_json(name, expected_value)
    }
    mismatched.update(
        name
        for name in supplied
        if resolved.identifier_disagreement(name, values.get(name)) is not None
    )
    if mismatched:
        raise ReleaseContractError(
            f"{resolved.name} configuration selects unexpected physical values: "
            + ", ".join(sorted(mismatched))
        )


def task_definition_arn_prefix(family: str) -> str:
    """Return the selected target's exact task-definition ARN prefix."""

    return SELECTED_TARGET.task_definition_arn_prefix(family)


def validate_release_record(payload: Any, target: DeploymentTarget | None = None) -> None:
    """Validate an immutable release record against one target's exact identifiers."""

    resolved = SELECTED_TARGET if target is None else target
    legacy_keys = {
        "image_digest",
        "migration_task_definition_arn",
        "rollback_eligible",
        "source_sha",
        "web_desired_count",
        "web_task_definition_arn",
        "worker_desired_count",
        "worker_task_definition_arn",
    }
    schema2_keys = legacy_keys | {"identity_schema", "version"}
    if not isinstance(payload, dict):
        raise ReleaseContractError("release record fields differ")
    payload_keys = frozenset(payload)
    if payload_keys not in {frozenset(legacy_keys), frozenset(schema2_keys)}:
        raise ReleaseContractError("release record fields differ")
    source_sha = payload["source_sha"]
    image_digest = payload["image_digest"]
    if not isinstance(source_sha, str) or re.fullmatch(r"[0-9a-f]{40}", source_sha) is None:
        raise ReleaseContractError("release record source SHA differs")
    if payload_keys == frozenset(schema2_keys):
        if payload["identity_schema"] != 2 or not isinstance(payload["version"], str):
            raise ReleaseContractError("release record identity schema differs")
        if re.fullmatch(
            r"[0-9]{8}-[0-9]{6}-[0-9a-f]{7}", payload["version"]
        ) is None or not payload["version"].endswith(f"-{source_sha[:7]}"):
            raise ReleaseContractError("release record version differs")
    if (
        not isinstance(image_digest, str)
        or re.fullmatch(r"sha256:[0-9a-f]{64}", image_digest) is None
        or image_digest
        in {
            "sha256:" + "0" * 64,
            "sha256:" + "1" * 64,
        }
    ):
        raise ReleaseContractError("release record image digest differs")
    family_fields = {
        "web_task_definition_arn": resolved.web_task_family,
        "worker_task_definition_arn": resolved.worker_task_family,
        "migration_task_definition_arn": resolved.migration_task_family,
    }
    for field_name, family in family_fields.items():
        value = payload[field_name]
        prefix = resolved.task_definition_arn_prefix(family)
        if (
            not isinstance(value, str)
            or re.fullmatch(re.escape(prefix) + r"[1-9][0-9]*", value) is None
        ):
            raise ReleaseContractError(f"release record {field_name} differs")
    if (
        payload["web_desired_count"] != resolved.web_desired_count
        or type(payload["web_desired_count"]) is not int
        or payload["worker_desired_count"] != resolved.worker_desired_count
        or type(payload["worker_desired_count"]) is not int
        or payload["rollback_eligible"] is not True
    ):
        raise ReleaseContractError("release record safety fields differ")


#: The architecture names a workflow may ask for, in ``GITHUB_OUTPUT`` order.
ARCHITECTURE_FIELDS: tuple[str, ...] = (
    "task_cpu_architecture",
    "build_platform",
    "image_architecture",
    "runner_machine",
    "runner_label",
)


def architecture_fields(target: DeploymentTarget | None = None) -> dict[str, str]:
    """Return the release image architecture names of one deployment target."""

    resolved = SELECTED_TARGET if target is None else target
    return {name: str(getattr(resolved, name)) for name in ARCHITECTURE_FIELDS}


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Validate deployment variables against the selected deployment target"
    )
    parser.add_argument("command", choices=[*ROLE_PROFILES, "architecture", "release-record"])
    parser.add_argument(
        "--field",
        choices=ARCHITECTURE_FIELDS,
        help=(
            "print one architecture value instead of every 'name=value' line "
            "(architecture command only)"
        ),
    )
    arguments = parser.parse_args()
    try:
        if arguments.command == "architecture":
            fields = architecture_fields()
            if arguments.field is not None:
                print(fields[arguments.field])
            else:
                for name, value in fields.items():
                    print(f"{name}={value}")
        elif arguments.command == "release-record":
            validate_release_record(json.load(sys.stdin))
        else:
            validate_environment(arguments.command, os.environ)
    except (json.JSONDecodeError, ReleaseContractError, DeploymentTargetError) as error:
        print(f"Deployment target validation failed safely: {error}", file=sys.stderr)
        raise SystemExit(1) from None


if __name__ == "__main__":
    main()
