# Generated by Django 6.0.8 on 2026-09-03 18:47

import django.db.models.deletion
from django.db import migrations, models


def _copy_active_baselines_onto_campaigns(apps, schema_editor):
    """Carry each campaign's currently-active baseline onto the new plain fields.

    Only a slot that is genuinely live today has anything to copy:

    * ``baseline_plus_native`` -- the active baseline revision's recorded
      cohort and count, and the slot's native cutover instant, but only when
      the revision (and its source run) are themselves ``active``.  That
      mirrors exactly what the old ``public_course_registration_count``
      required before it would show a number at all, so a slot that was
      mid-rollback or otherwise not fully active is left alone (baseline 0,
      no cutover -- the same "nothing published" outcome the old code
      produced by returning ``None`` for a campaign with no native rows
      yet either).
    * ``rows_only`` -- the baseline was already reconciled away in favor of
      the real rows, so there is nothing left to carry: baseline stays 0
      and there is no cutover, which makes the new formula count the
      native rows directly, exactly as the old rows-only mode did.
    """

    CourseRegistrationCountSlot = apps.get_model("courses", "CourseRegistrationCountSlot")
    RegistrationCampaign = apps.get_model("courses", "RegistrationCampaign")
    slots = CourseRegistrationCountSlot.objects.select_related(
        "active_baseline_revision",
        "active_baseline_revision__source_run",
    )
    for slot in slots:
        if slot.mode != "baseline_plus_native":
            continue
        baseline = slot.active_baseline_revision
        if (
            baseline is None
            or baseline.state != "active"
            or baseline.source_run.state != "active"
        ):
            continue
        RegistrationCampaign.objects.filter(pk=slot.campaign_id).update(
            registration_baseline_cohort_id=slot.cohort_id,
            registration_baseline_count=baseline.baseline_count,
            registration_native_start_at=slot.native_start_at,
        )


def _noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='courseregistrationcountrevision',
            name='courses_count_revision_target',
        ),
        migrations.RemoveIndex(
            model_name='courseregistrationcountrevision',
            name='courses_count_rev_checksum',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountrevision',
            name='courses_count_revision_target_unique',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountrevision',
            name='courses_count_revision_one_active',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountrevision',
            name='courses_count_revision_positive',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountrevision',
            name='courses_count_revision_timestamp_pair',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountrevision',
            name='courses_count_revision_nonoverlap',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountrevision',
            name='courses_count_revision_state_valid',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountrevision',
            name='courses_count_revision_evidence',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountslot',
            name='courses_count_slot_target_unique',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountslot',
            name='courses_count_slot_revision_positive',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountslot',
            name='courses_count_slot_public_revision_positive',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountslot',
            name='courses_count_slot_mode_pointer',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountslot',
            name='courses_count_slot_prior_mode_valid',
        ),
        migrations.RemoveIndex(
            model_name='courseregistrationcountsourcerun',
            name='courses_count_run_state',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountsourcerun',
            name='courses_count_run_checksum_unique',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountsourcerun',
            name='courses_count_run_revision_positive',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountsourcerun',
            name='courses_count_run_frozen_before_capture',
        ),
        migrations.RemoveConstraint(
            model_name='courseregistrationcountsourcerun',
            name='courses_count_run_state_valid',
        ),
        migrations.AddField(
            model_name='registrationcampaign',
            name='registration_baseline_cohort',
            field=models.ForeignKey(blank=True, help_text='The cohort the baseline count below was recorded for. A campaign that has rotated to promote a different cohort since no longer applies it -- a baseline recorded for a finished edition never carries onto whatever cohort registers next.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='courses.cohort'),
        ),
        migrations.AddField(
            model_name='registrationcampaign',
            name='registration_baseline_count',
            field=models.PositiveIntegerField(db_default=0, default=0, help_text="Registrations that happened before this campaign's CourseRegistration rows existed (a one-time recorded historical figure, e.g. from a legacy CMP export). Zero for a campaign whose registrations are all native rows."),
        ),
        migrations.AddField(
            model_name='registrationcampaign',
            name='registration_native_start_at',
            field=models.DateTimeField(blank=True, help_text='When native CourseRegistration rows became the complete record for this campaign. Only registrations at or after this instant are added to the baseline above; unset when there is no baseline to protect against double-counting.', null=True),
        ),
        migrations.RunPython(
            _copy_active_baselines_onto_campaigns,
            _noop,
        ),
        migrations.RemoveField(
            model_name='courseregistrationcountslot',
            name='active_baseline_revision',
        ),
        migrations.RemoveField(
            model_name='courseregistrationcountslot',
            name='campaign',
        ),
        migrations.RemoveField(
            model_name='courseregistrationcountslot',
            name='cohort',
        ),
        migrations.RemoveField(
            model_name='courseregistrationcountslot',
            name='prior_baseline_revision',
        ),
        migrations.RemoveField(
            model_name='courseregistrationcountsourcerun',
            name='actor',
        ),
        migrations.DeleteModel(
            name='CourseRegistrationCountRevision',
        ),
        migrations.DeleteModel(
            name='CourseRegistrationCountSlot',
        ),
        migrations.DeleteModel(
            name='CourseRegistrationCountSourceRun',
        ),
    ]
