# Generated by Django 6.0.8 on 2026-09-05 10:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_simplify_registration_counts'),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='delivery_format',
            field=models.CharField(blank=True, db_default='', default='', help_text="How this cohort is delivered, such as 'Online'.", max_length=64),
        ),
        migrations.AddField(
            model_name='cohort',
            name='promo_summary',
            field=models.TextField(blank=True, db_default='', default='', help_text='One-sentence summary shown where this cohort is advertised.'),
        ),
        migrations.CreateModel(
            name='CohortBuildItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=500)),
                ('position', models.PositiveSmallIntegerField()),
                ('cohort', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='build_items', to='courses.cohort')),
            ],
            options={
                'ordering': ('cohort_id', 'position'),
                'constraints': [models.UniqueConstraint(fields=('cohort', 'position'), name='courses_cohort_build_item_position_unique'), models.CheckConstraint(condition=models.Q(('text__gt', '')), name='courses_cohort_build_item_text_nonempty')],
            },
        ),
    ]
