# Generated by Django 6.0.8 on 2026-08-20 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_curriculum_and_project_criteria'),
    ]

    operations = [
        migrations.AlterField(
            model_name='module',
            name='link',
            field=models.URLField(blank=True, help_text='Optional destination for the module heading.'),
        ),
        migrations.AlterField(
            model_name='unit',
            name='link',
            field=models.URLField(blank=True, help_text='Optional destination for the unit.'),
        ),
    ]
