# Generated by Django 6.0.8 on 2026-09-05 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0003_cohort_delivery_format_cohort_promo_summary_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CmpHistoryImportProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("table", models.CharField(max_length=64, unique=True)),
                ("last_source_id", models.BigIntegerField(default=0)),
                ("rows_created", models.PositiveBigIntegerField(default=0)),
                ("rows_attached", models.PositiveBigIntegerField(default=0)),
                ("rows_skipped", models.PositiveBigIntegerField(default=0)),
                ("unresolved", models.JSONField(blank=True, default=dict)),
                ("completed", models.BooleanField(default=False)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "CMP history import progress",
                "verbose_name_plural": "CMP history import progress",
                "ordering": ("table",),
            },
        ),
    ]
