# Generated by Django 6.0.8 on 2026-09-07 18:34

import courses.curriculum_source_validators
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_cmphistoryimportprogress'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CohortSharedModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='CurriculumRouteAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_path', models.CharField(max_length=1024, unique=True)),
                ('target_kind', models.CharField(choices=[('shared_module', 'Shared module'), ('shared_lesson', 'Shared lesson'), ('github_archive', 'GitHub archive')], max_length=20)),
                ('archive_path', models.CharField(blank=True, default='', max_length=1024)),
                ('reason', models.CharField(max_length=500)),
                ('source_commit_sha', models.CharField(max_length=40)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='SharedCurriculum',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('parser_version', models.CharField(max_length=128)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SharedCurriculumAsset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('public_path', models.CharField(max_length=1024, unique=True)),
                ('storage_key', models.CharField(max_length=1024, unique=True)),
                ('content_type', models.CharField(blank=True, default='', max_length=128)),
                ('byte_size', models.PositiveBigIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='SharedLesson',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('position', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('content_markdown', models.TextField(blank=True)),
                ('rendered_html', models.TextField(blank=True)),
                ('video_url', models.URLField(blank=True)),
                ('code_sources', models.JSONField(blank=True, default=list, validators=[courses.curriculum_source_validators.validate_unit_code_sources])),
                ('published', models.BooleanField(default=True)),
                ('retired_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.CreateModel(
            name='SharedLessonReadState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('read_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='SharedModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source_content_id', models.UUIDField(blank=True, null=True)),
                ('source_path', models.CharField(blank=True, max_length=1024, null=True, validators=[django.core.validators.RegexValidator('^(?!/)(?!.*\\\\).+$', 'Enter a repository-relative POSIX path.')])),
                ('source_commit_sha', models.CharField(blank=True, max_length=40, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{40}$', 'Enter a full lowercase Git SHA.')])),
                ('source_checksum', models.CharField(blank=True, max_length=64, null=True, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('position', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=100)),
                ('title', models.CharField(max_length=200)),
                ('overview_markdown', models.TextField(blank=True, default='')),
                ('overview_rendered_html', models.TextField(blank=True, default='')),
                ('summary', models.CharField(blank=True, default='', max_length=500)),
                ('published', models.BooleanField(default=True)),
                ('retired_at', models.DateTimeField(blank=True, help_text='Set when a source import removes this module from the current graph. Retired rows are absent from navigation but retained while learner progress or a route alias requires them.', null=True)),
            ],
            options={
                'ordering': ('position', 'id'),
            },
        ),
        migrations.RemoveConstraint(
            model_name='cohort',
            name='courses_cohort_curriculum_format_valid',
        ),
        migrations.AddField(
            model_name='cohort',
            name='archive_commit_sha',
            field=models.CharField(blank=True, default='', help_text='The full lowercase commit SHA the archive URL was derived from.', max_length=40),
        ),
        migrations.AddField(
            model_name='cohort',
            name='archive_notice_path',
            field=models.CharField(blank=True, default='', help_text='Repository-relative POSIX path of the archive notice Markdown. Required together with the derived URL and commit for github_archive cohorts; absent for current ones.', max_length=1024),
        ),
        migrations.AddField(
            model_name='cohort',
            name='archive_url',
            field=models.URLField(blank=True, default='', help_text='The immutable GitHub blob URL of the archive notice, derived by the importer from the validated repository, the full incoming commit SHA, and the notice path.', max_length=2048),
        ),
        migrations.AddField(
            model_name='cohort',
            name='curriculum_source',
            field=models.CharField(choices=[('current', 'Current'), ('github_archive', 'GitHub archive')], db_default='current', default='current', help_text='Whether this cohort follows the current curriculum or is a GitHub-only archive of materially different, older material.', max_length=15),
        ),
        migrations.AddField(
            model_name='cohort',
            name='delivery_mode',
            field=models.CharField(choices=[('live', 'Live'), ('self_paced', 'Self-paced')], db_default='live', default='live', help_text='How this cohort is delivered. A self-paced cohort reads the shared current curriculum with ungraded practice only; delivery is never overloaded with an archive value.', max_length=12),
        ),
        migrations.AlterField(
            model_name='cohort',
            name='curriculum_format',
            field=models.CharField(choices=[('legacy', 'Legacy'), ('modules', 'Modules'), ('shared', 'Shared current curriculum')], db_default='legacy', default='legacy', help_text='The curriculum presentation used by this cohort.', max_length=7),
        ),
        migrations.AddField(
            model_name='cohortsharedmodule',
            name='cohort',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_module_placements', to='courses.cohort'),
        ),
        migrations.AddField(
            model_name='cohortsharedmodule',
            name='terminal_homework',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='shared_module_placements', to='courses.homework'),
        ),
        migrations.AddField(
            model_name='curriculumroutealias',
            name='archive_cohort',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='archive_route_aliases', to='courses.cohort'),
        ),
        migrations.AddField(
            model_name='sharedcurriculum',
            name='course',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='shared_curriculum', to='courses.course'),
        ),
        migrations.AddField(
            model_name='cohort',
            name='shared_curriculum',
            field=models.ForeignKey(blank=True, help_text="The course's current shared graph, used only by curriculum_format=shared cohorts and validated to belong to the cohort's course.", null=True, on_delete=django.db.models.deletion.PROTECT, related_name='cohorts', to='courses.sharedcurriculum'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('curriculum_format__in', ['legacy', 'modules', 'shared'])), name='courses_cohort_curriculum_format_valid'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('delivery_mode__in', ['live', 'self_paced'])), name='courses_cohort_delivery_mode_valid'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(('curriculum_source__in', ['current', 'github_archive'])), name='courses_cohort_curriculum_source_valid'),
        ),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('curriculum_source', 'github_archive'), models.Q(('archive_notice_path', ''), _negated=True), models.Q(('archive_url', ''), _negated=True), ('archive_commit_sha__regex', '^[0-9a-f]{40}$')), models.Q(('curriculum_source', 'current'), ('archive_notice_path', ''), ('archive_url', ''), ('archive_commit_sha', '')), _connector='OR'), name='courses_cohort_archive_identity_ck'),
        ),
        migrations.AddField(
            model_name='sharedcurriculumasset',
            name='lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to='courses.sharedlesson'),
        ),
        migrations.AddField(
            model_name='curriculumroutealias',
            name='shared_lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_aliases', to='courses.sharedlesson'),
        ),
        migrations.AddField(
            model_name='sharedlessonreadstate',
            name='shared_lesson',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='read_states', to='courses.sharedlesson'),
        ),
        migrations.AddField(
            model_name='sharedlessonreadstate',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_lesson_read_states', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sharedmodule',
            name='curriculum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modules', to='courses.sharedcurriculum'),
        ),
        migrations.AddField(
            model_name='sharedlesson',
            name='module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='courses.sharedmodule'),
        ),
        migrations.AddField(
            model_name='curriculumroutealias',
            name='shared_module',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='route_aliases', to='courses.sharedmodule'),
        ),
        migrations.AddField(
            model_name='cohortsharedmodule',
            name='shared_module',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='courses.sharedmodule'),
        ),
        migrations.AddConstraint(
            model_name='sharedcurriculum',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_checksum__isnull', True), ('source_commit_sha__isnull', True), ('source_content_id__isnull', True), ('source_path__isnull', True)), models.Q(('source_checksum__isnull', False), ('source_commit_sha__isnull', False), ('source_content_id__isnull', False), ('source_path__isnull', False), ('source_commit_sha__regex', '^[0-9a-f]{40}$'), ('source_checksum__regex', '^[0-9a-f]{64}$')), _connector='OR'), name='courses_shared_curriculum_source_complete'),
        ),
        migrations.AddConstraint(
            model_name='sharedcurriculumasset',
            constraint=models.UniqueConstraint(fields=('lesson', 'source_path'), name='courses_shared_curriculum_asset_source_uq'),
        ),
        migrations.AddConstraint(
            model_name='sharedcurriculumasset',
            constraint=models.CheckConstraint(condition=models.Q(('byte_size__gte', 0)), name='courses_shared_curriculum_asset_size_ck'),
        ),
        migrations.AddConstraint(
            model_name='sharedlessonreadstate',
            constraint=models.UniqueConstraint(fields=('user', 'shared_lesson'), name='courses_shared_lesson_read_state_uq'),
        ),
        migrations.AddConstraint(
            model_name='sharedmodule',
            constraint=models.UniqueConstraint(fields=('curriculum', 'slug'), name='courses_shared_module_curriculum_slug_uq'),
        ),
        migrations.AddConstraint(
            model_name='sharedmodule',
            constraint=models.UniqueConstraint(fields=('curriculum', 'position'), name='courses_shared_module_curriculum_position_uq'),
        ),
        migrations.AddConstraint(
            model_name='sharedmodule',
            constraint=models.UniqueConstraint(condition=models.Q(('source_content_id__isnull', False)), fields=('curriculum', 'source_content_id'), name='courses_shared_module_source_content_uq'),
        ),
        migrations.AddConstraint(
            model_name='sharedmodule',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_checksum__isnull', True), ('source_commit_sha__isnull', True), ('source_content_id__isnull', True), ('source_path__isnull', True)), models.Q(('source_checksum__isnull', False), ('source_commit_sha__isnull', False), ('source_content_id__isnull', False), ('source_path__isnull', False), ('source_commit_sha__regex', '^[0-9a-f]{40}$'), ('source_checksum__regex', '^[0-9a-f]{64}$')), _connector='OR'), name='courses_shared_module_source_complete'),
        ),
        migrations.AddConstraint(
            model_name='sharedlesson',
            constraint=models.UniqueConstraint(fields=('module', 'slug'), name='courses_shared_lesson_module_slug_uq'),
        ),
        migrations.AddConstraint(
            model_name='sharedlesson',
            constraint=models.UniqueConstraint(fields=('module', 'position'), name='courses_shared_lesson_module_position_uq'),
        ),
        migrations.AddConstraint(
            model_name='sharedlesson',
            constraint=models.UniqueConstraint(condition=models.Q(('source_content_id__isnull', False)), fields=('module', 'source_content_id'), name='courses_shared_lesson_source_content_uq'),
        ),
        migrations.AddConstraint(
            model_name='sharedlesson',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('source_checksum__isnull', True), ('source_commit_sha__isnull', True), ('source_content_id__isnull', True), ('source_path__isnull', True)), models.Q(('source_checksum__isnull', False), ('source_commit_sha__isnull', False), ('source_content_id__isnull', False), ('source_path__isnull', False), ('source_commit_sha__regex', '^[0-9a-f]{40}$'), ('source_checksum__regex', '^[0-9a-f]{64}$')), _connector='OR'), name='courses_shared_lesson_source_complete'),
        ),
        migrations.AddConstraint(
            model_name='curriculumroutealias',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('shared_module__isnull', False), ('target_kind', 'shared_module')), models.Q(('shared_lesson__isnull', False), ('target_kind', 'shared_lesson')), models.Q(('archive_cohort__isnull', False), ('archive_path__gt', ''), ('target_kind', 'github_archive')), _connector='OR'), name='courses_curriculum_route_alias_target_ck'),
        ),
        migrations.AddConstraint(
            model_name='cohortsharedmodule',
            constraint=models.UniqueConstraint(fields=('cohort', 'shared_module'), name='courses_cohort_shared_module_pair_uq'),
        ),
        migrations.AddConstraint(
            model_name='cohortsharedmodule',
            constraint=models.UniqueConstraint(fields=('cohort', 'position'), name='courses_cohort_shared_module_position_uq'),
        ),
    ]
