# Generated by Django 6.0.8 on 2026-09-08 22:34

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0006_source_content_id_compound'),
    ]

    operations = [
        migrations.CreateModel(
            name='CmpHistoryImportBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(max_length=32, unique=True)),
                ('schema_version', models.IntegerField()),
                ('importer_version', models.CharField(max_length=64)),
                ('source_sha256', models.CharField(max_length=64)),
                ('target_uuid', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'CMP history import binding',
                'verbose_name_plural': 'CMP history import bindings',
            },
        ),
        migrations.CreateModel(
            name='CmpHistoryClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('table', models.CharField(max_length=64)),
                ('source_id', models.BigIntegerField()),
                ('target_id', models.BigIntegerField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ('table', 'source_id'),
                'constraints': [models.UniqueConstraint(fields=('table', 'source_id'), name='courses_cmphistoryclaim_table_source_unique')],
            },
        ),
    ]
