# Generated by Django 6.0.8 on 2026-09-11 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_cmphistoryimportbinding_cmphistoryclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cohort',
            name='faq_document_url',
        ),
    ]
