# Generated by Django 6.0.8 on 2026-09-17 05:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0014_course_weekly_commitment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='courseregistration',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_course_registrations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaderboardcomplaint',
            name='reporter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_leaderboard_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='leaderboardcomplaint',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='site_resolved_leaderboard_complaints', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='projectvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_project_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userwrappedstatistics',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='site_wrapped_statistics', to=settings.AUTH_USER_MODEL),
        ),
    ]
