# Generated by Django 6.0.8 on 2026-09-17 20:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0018_learnerprofile_refresh"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="testimonial",
            name="courses_testimonial_placement_scope",
        ),
        migrations.AlterField(
            model_name="testimonial",
            name="placement",
            field=models.CharField(
                choices=[
                    ("homepage", "Homepage"),
                    ("tour", "Community tour"),
                    ("course", "Course family"),
                ],
                help_text="Homepage and tour testimonials carry no course; course testimonials carry exactly one.",
                max_length=16,
            ),
        ),
        migrations.AddConstraint(
            model_name="testimonial",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("course__isnull", True), ("placement__in", ["homepage", "tour"])),
                    models.Q(("course__isnull", False), ("placement", "course")),
                    _connector="OR",
                ),
                name="courses_testimonial_placement_scope",
            ),
        ),
    ]
