# Generated by Django 6.0.8 on 2026-09-19 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0019_add_tour_testimonial_placement'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRepoEnrichment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo', models.CharField(help_text="Original 'owner/name' slug the submission was keyed by.", max_length=300, unique=True)),
                ('repo_lower', models.CharField(db_index=True, help_text="Lowercased 'owner/name' for case-insensitive joins.", max_length=300, unique=True)),
                ('effective_url', models.URLField(blank=True, help_text='Current repository URL, following renames. Blank when gone.')),
                ('availability', models.CharField(blank=True, help_text="'live' when reachable, otherwise the unavailability reason.", max_length=300)),
                ('is_unavailable', models.BooleanField(db_index=True, default=False)),
                ('is_coursework', models.BooleanField(default=False, help_text='Repository is a homework/coursework collection, not a capstone.')),
                ('card_summary', models.CharField(blank=True, max_length=200)),
                ('what_it_is', models.TextField(blank=True)),
                ('interesting', models.TextField(blank=True)),
                ('why_check', models.TextField(blank=True)),
                ('improvements', models.TextField(blank=True)),
                ('topics', models.TextField(blank=True, help_text='Comma-separated topic labels.')),
                ('confidence', models.CharField(blank=True, help_text='Write-up confidence: high, medium, low, baseline, or blank.', max_length=20)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'project repo enrichment',
                'verbose_name_plural': 'project repo enrichments',
                'ordering': ('repo',),
            },
        ),
    ]
