# Generated by Django 6.0.7 on 2026-08-11

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0040_courseregistration_company_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseRegistrationCountSourceRun",
            fields=[
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("adapter_version", models.CharField(max_length=32)),
                ("schema_version", models.CharField(max_length=64)),
                ("count_policy_version", models.CharField(max_length=32)),
                ("whole_source_checksum", models.CharField(max_length=64)),
                ("source_byte_size", models.PositiveBigIntegerField()),
                ("schema_contract_checksum", models.CharField(max_length=64)),
                ("aggregate_manifest_checksum", models.CharField(max_length=64)),
                ("source_reference_digest", models.CharField(max_length=64, unique=True)),
                ("captured_at", models.DateTimeField()),
                ("source_frozen_at", models.DateTimeField()),
                ("campaign_total", models.PositiveIntegerField()),
                ("row_total", models.PositiveBigIntegerField()),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("validated", "Validated"),
                            ("active", "Active"),
                            ("cancelled", "Cancelled"),
                            ("rolled_back", "Rolled back"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="staged",
                        max_length=16,
                    ),
                ),
                ("actor_ref", models.CharField(blank=True, max_length=128)),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="course_registration_count_source_runs",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at", "-id"),
                "permissions": (
                    (
                        "registration_count_baseline_manage",
                        "Can manage course registration count baselines",
                    ),
                ),
            },
        ),
        migrations.CreateModel(
            name="CourseRegistrationCountRevision",
            fields=[
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("campaign_slug_snapshot", models.SlugField(max_length=255)),
                ("cohort_slug_snapshot", models.SlugField(max_length=255)),
                ("baseline_count", models.PositiveBigIntegerField()),
                ("source_min_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_max_created_at", models.DateTimeField(blank=True, null=True)),
                ("coverage_cutoff_at", models.DateTimeField()),
                ("proposed_native_start_at", models.DateTimeField()),
                ("aggregate_checksum", models.CharField(max_length=64)),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("staged", "Staged"),
                            ("validated", "Validated"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("rolled_back", "Rolled back"),
                            ("quarantined", "Quarantined"),
                        ],
                        default="staged",
                        max_length=16,
                    ),
                ),
                ("reason_code", models.CharField(blank=True, max_length=64)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_revisions",
                        to="courses.registrationcampaign",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_count_revisions",
                        to="courses.course",
                    ),
                ),
                (
                    "source_run",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="count_revisions",
                        to="courses.courseregistrationcountsourcerun",
                    ),
                ),
            ],
            options={
                "ordering": (
                    "source_run_id",
                    "campaign_slug_snapshot",
                    "cohort_slug_snapshot",
                ),
            },
        ),
        migrations.CreateModel(
            name="CourseRegistrationCountSlot",
            fields=[
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("campaign_slug_snapshot", models.SlugField(max_length=255)),
                ("cohort_slug_snapshot", models.SlugField(max_length=255)),
                (
                    "mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("baseline_plus_native", "Baseline plus native rows"),
                            ("rows_only", "Rows only"),
                        ],
                        max_length=24,
                    ),
                ),
                ("native_start_at", models.DateTimeField(blank=True, null=True)),
                ("row_replacement_revision_id", models.UUIDField(blank=True, null=True)),
                (
                    "prior_mode",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("baseline_plus_native", "Baseline plus native rows"),
                            ("rows_only", "Rows only"),
                        ],
                        max_length=24,
                    ),
                ),
                ("prior_native_start_at", models.DateTimeField(blank=True, null=True)),
                (
                    "prior_row_replacement_revision_id",
                    models.UUIDField(blank=True, null=True),
                ),
                ("public_total_revision", models.PositiveBigIntegerField(default=1)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_baseline_revision",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_slot",
                        to="courses.courseregistrationcountrevision",
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_count_slots",
                        to="courses.registrationcampaign",
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="registration_count_slots",
                        to="courses.course",
                    ),
                ),
                (
                    "prior_baseline_revision",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="prior_slots",
                        to="courses.courseregistrationcountrevision",
                    ),
                ),
            ],
            options={
                "ordering": ("campaign_slug_snapshot", "cohort_slug_snapshot"),
                "constraints": [
                    models.UniqueConstraint(
                        fields=("campaign", "cohort"),
                        name="courses_count_slot_target_unique",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("revision__gte", 1)),
                        name="courses_count_slot_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("public_total_revision__gte", 1)),
                        name="courses_count_slot_public_revision_positive",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            models.Q(
                                ("active_baseline_revision__isnull", True),
                                ("mode", ""),
                                ("native_start_at__isnull", True),
                                ("row_replacement_revision_id__isnull", True),
                            ),
                            models.Q(
                                ("active_baseline_revision__isnull", False),
                                ("mode", "baseline_plus_native"),
                                ("native_start_at__isnull", False),
                                ("row_replacement_revision_id__isnull", True),
                            ),
                            models.Q(
                                ("active_baseline_revision__isnull", True),
                                ("mode", "rows_only"),
                                ("native_start_at__isnull", False),
                                ("row_replacement_revision_id__isnull", False),
                            ),
                            _connector="OR",
                        ),
                        name="courses_count_slot_mode_pointer",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("prior_mode__in", ("", "baseline_plus_native", "rows_only"))
                        ),
                        name="courses_count_slot_prior_mode_valid",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="courseregistrationcountsourcerun",
            index=models.Index(fields=["state", "-created_at"], name="courses_count_run_state"),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountsourcerun",
            constraint=models.UniqueConstraint(
                fields=("whole_source_checksum",),
                name="courses_count_run_checksum_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountsourcerun",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="courses_count_run_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountsourcerun",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_frozen_at__lte", models.F("captured_at"))),
                name="courses_count_run_frozen_before_capture",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountsourcerun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "staged",
                            "validated",
                            "active",
                            "cancelled",
                            "rolled_back",
                            "quarantined",
                        ),
                    )
                ),
                name="courses_count_run_state_valid",
            ),
        ),
        migrations.AddIndex(
            model_name="courseregistrationcountrevision",
            index=models.Index(
                fields=["campaign", "cohort", "state"],
                name="courses_count_revision_target",
            ),
        ),
        migrations.AddIndex(
            model_name="courseregistrationcountrevision",
            index=models.Index(fields=["aggregate_checksum"], name="courses_count_rev_checksum"),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountrevision",
            constraint=models.UniqueConstraint(
                fields=("source_run", "campaign", "cohort"),
                name="courses_count_revision_target_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountrevision",
            constraint=models.UniqueConstraint(
                condition=models.Q(("state", "active")),
                fields=("campaign", "cohort"),
                name="courses_count_revision_one_active",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)),
                name="courses_count_revision_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_max_created_at__isnull", True),
                        ("source_min_created_at__isnull", True),
                    ),
                    models.Q(
                        ("source_max_created_at__isnull", False),
                        ("source_min_created_at__isnull", False),
                        ("source_min_created_at__lte", models.F("source_max_created_at")),
                    ),
                    _connector="OR",
                ),
                name="courses_count_revision_timestamp_pair",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("coverage_cutoff_at__lt", models.F("proposed_native_start_at"))
                ),
                name="courses_count_revision_nonoverlap",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        (
                            "staged",
                            "validated",
                            "active",
                            "superseded",
                            "rolled_back",
                            "quarantined",
                        ),
                    )
                ),
                name="courses_count_revision_state_valid",
            ),
        ),
        migrations.AddConstraint(
            model_name="courseregistrationcountrevision",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("baseline_count", 0),
                        ("source_max_created_at__isnull", True),
                        ("source_min_created_at__isnull", True),
                    ),
                    models.Q(
                        ("baseline_count__gt", 0),
                        ("source_max_created_at__isnull", False),
                        ("source_min_created_at__isnull", False),
                    ),
                    _connector="OR",
                ),
                name="courses_count_revision_evidence",
            ),
        ),
    ]
