# Generated by Django 6.0.8 on 2026-08-20 18:00

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


# This first release has no reviewed existing-cohort opt-in.  Keeping the
# allow-list explicit makes the legacy default deterministic and prevents
# migration heuristics from selecting module cohorts from content or dates.
MODULE_COHORT_ALLOWLIST = frozenset()


def backfill_project_criteria(apps, schema_editor):
    """Preserve legacy provenance and seed each project's ordered rubric."""

    Cohort = apps.get_model("courses", "Cohort")
    Project = apps.get_model("courses", "Project")
    ReviewCriteria = apps.get_model("courses", "ReviewCriteria")
    ProjectCriteriaAssignment = apps.get_model("courses", "ProjectCriteriaAssignment")
    database = schema_editor.connection.alias

    for cohort in Cohort.objects.using(database).order_by("pk"):
        format_value = "modules" if cohort.pk in MODULE_COHORT_ALLOWLIST else "legacy"
        Cohort.objects.using(database).filter(pk=cohort.pk).update(
            curriculum_format=format_value,
        )

        criteria = (
            ReviewCriteria.objects.using(database)
            .filter(
                course_id=cohort.pk,
            )
            .order_by("pk")
        )
        project_ids = (
            Project.objects.using(database)
            .filter(
                course_id=cohort.pk,
            )
            .order_by("pk")
            .values_list("pk", flat=True)
        )

        for project_id in project_ids:
            for position, criterion in enumerate(criteria):
                ProjectCriteriaAssignment.objects.using(database).get_or_create(
                    project_id=project_id,
                    criteria_id=criterion.pk,
                    defaults={"position": position},
                )


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0042_course_schema_bridge"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CurriculumFlowItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="Module",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=200)),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional destination for the module heading.",
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="ProjectCriteriaAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.CreateModel(
            name="Unit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("position", models.PositiveIntegerField()),
                ("slug", models.SlugField()),
                ("title", models.CharField(max_length=200)),
                (
                    "link",
                    models.URLField(
                        blank=True,
                        help_text="Optional destination for the unit.",
                        validators=[django.core.validators.URLValidator(schemes=["http", "https"])],
                    ),
                ),
            ],
            options={
                "ordering": ("position", "id"),
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="curriculum_format",
            field=models.CharField(
                choices=[("legacy", "Legacy"), ("modules", "Modules")],
                db_default="legacy",
                default="legacy",
                help_text="The curriculum presentation used by this cohort.",
                max_length=7,
            ),
        ),
        migrations.AlterField(
            model_name="reviewcriteria",
            name="course",
            field=models.ForeignKey(
                blank=True,
                help_text="Deprecated legacy cohort provenance; use project criteria assignments.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="courses.cohort",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.CheckConstraint(
                condition=models.Q(("curriculum_format__in", ["legacy", "modules"])),
                name="courses_cohort_curriculum_format_valid",
            ),
        ),
        migrations.AddField(
            model_name="curriculumflowitem",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_items",
                to="courses.cohort",
            ),
        ),
        migrations.AddField(
            model_name="curriculumflowitem",
            name="project",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_items",
                to="courses.project",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="modules",
                to="courses.cohort",
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="terminal_homework",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="terminal_module",
                to="courses.homework",
            ),
        ),
        migrations.AddField(
            model_name="curriculumflowitem",
            name="module",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="flow_items",
                to="courses.module",
            ),
        ),
        migrations.AddField(
            model_name="projectcriteriaassignment",
            name="criteria",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="project_assignments",
                to="courses.reviewcriteria",
            ),
        ),
        migrations.AddField(
            model_name="projectcriteriaassignment",
            name="project",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="criteria_assignments",
                to="courses.project",
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="module",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="units",
                to="courses.module",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("cohort", "position"), name="courses_module_cohort_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                fields=("cohort", "slug"), name="courses_module_cohort_slug_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumflowitem",
            constraint=models.UniqueConstraint(
                fields=("cohort", "position"), name="courses_flow_item_cohort_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumflowitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("module__isnull", False)),
                fields=("cohort", "module"),
                name="courses_flow_item_module_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumflowitem",
            constraint=models.UniqueConstraint(
                condition=models.Q(("project__isnull", False)),
                fields=("cohort", "project"),
                name="courses_flow_item_project_unique",
            ),
        ),
        migrations.AddConstraint(
            model_name="curriculumflowitem",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("module__isnull", False), ("project__isnull", True)),
                    models.Q(("module__isnull", True), ("project__isnull", False)),
                    _connector="OR",
                ),
                name="courses_flow_item_exactly_one_target",
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcriteriaassignment",
            constraint=models.UniqueConstraint(
                fields=("project", "position"), name="courses_project_criteria_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="projectcriteriaassignment",
            constraint=models.UniqueConstraint(
                fields=("project", "criteria"), name="courses_project_criteria_definition_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("module", "position"), name="courses_unit_module_position_unique"
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                fields=("module", "slug"), name="courses_unit_module_slug_unique"
            ),
        ),
        migrations.RunPython(
            backfill_project_criteria,
            migrations.RunPython.noop,
        ),
    ]
