# Generated by Django 6.0.8 on 2026-08-20 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0044_alter_module_link_alter_unit_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='criteriaresponse',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.reviewcriteria'),
        ),
        migrations.AlterField(
            model_name='projectcriteriaassignment',
            name='criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='project_assignments', to='courses.reviewcriteria'),
        ),
        migrations.AlterField(
            model_name='projectevaluationscore',
            name='review_criteria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='courses.reviewcriteria'),
        ),
    ]
