# Generated by Django 6.0.8 on 2026-08-20 18:31

from django.conf import settings
from django.db import migrations, models


def backfill_cohort_identifiers(apps, schema_editor):
    Cohort = apps.get_model("courses", "Cohort")
    database = schema_editor.connection.alias

    for cohort in Cohort.objects.using(database).filter(identifier="").iterator():
        Cohort.objects.using(database).filter(pk=cohort.pk).update(
            identifier=str(cohort.year),
        )


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0045_alter_criteriaresponse_criteria_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='cohort',
            name='identifier',
            field=models.SlugField(default='', help_text="Stable public identifier for this cohort, such as '2026' or 'spring-2026'.", max_length=80),
        ),
        migrations.RunPython(backfill_cohort_identifiers, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='cohort',
            constraint=models.UniqueConstraint(fields=('course', 'identifier'), name='courses_cohort_course_identifier_unique'),
        ),
    ]
