# Generated by Django 6.0.8 on 2026-08-20 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0046_cohort_identifier_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cohort',
            name='identifier',
            field=models.SlugField(blank=True, default='', help_text="Stable public identifier for this cohort, such as '2026' or 'spring-2026'.", max_length=80),
        ),
    ]
