# Generated by Django 6.0.8 on 2026-08-20 20:46

import uuid

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0047_alter_cohort_identifier"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseCurriculumImportRun",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_uuid", models.UUIDField()),
                (
                    "source_stable_id",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[a-z0-9][a-z0-9._-]{0,127}$",
                                "Enter a canonical source stable ID.",
                            )
                        ],
                    ),
                ),
                (
                    "repository_owner",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$",
                                "Enter a canonical repository owner or name.",
                            )
                        ],
                    ),
                ),
                (
                    "repository_name",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$",
                                "Enter a canonical repository owner or name.",
                            )
                        ],
                    ),
                ),
                (
                    "repository_branch",
                    models.CharField(
                        max_length=255,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9][A-Za-z0-9._/-]{0,254}$",
                                "Enter a canonical repository branch.",
                            )
                        ],
                    ),
                ),
                (
                    "commit_sha",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                            )
                        ],
                    ),
                ),
                ("schema_version", models.PositiveIntegerField()),
                (
                    "parser_version",
                    models.CharField(
                        max_length=128,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$",
                                "Enter a canonical source version.",
                            )
                        ],
                    ),
                ),
                (
                    "state",
                    models.CharField(
                        choices=[
                            ("received", "Received"),
                            ("validating", "Validating"),
                            ("applying", "Applying"),
                            ("succeeded", "Succeeded"),
                            ("rejected", "Rejected"),
                            ("failed", "Failed"),
                        ],
                        default="received",
                        max_length=16,
                    ),
                ),
                (
                    "manifest_checksum",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("diagnostics", models.JSONField(blank=True, default=list)),
                ("counts", models.JSONField(blank=True, default=dict)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("finished_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ("-created_at", "-id"),
            },
        ),
        migrations.AddField(
            model_name="cohort",
            name="source_checksum",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="source_commit_sha",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="cohort",
            name="source_content_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="cohort",
            name="source_path",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!/)(?!.*\\\\).+$", "Enter a repository-relative POSIX path."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="source_checksum",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="source_commit_sha",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="source_content_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="course",
            name="source_path",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!/)(?!.*\\\\).+$", "Enter a repository-relative POSIX path."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="course",
            name="source_stable_id",
            field=models.CharField(
                blank=True,
                max_length=128,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9][a-z0-9._-]{0,127}$", "Enter a canonical source stable ID."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="source_checksum",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="source_commit_sha",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="homework",
            name="source_content_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="homework",
            name="source_path",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!/)(?!.*\\\\).+$", "Enter a repository-relative POSIX path."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="source_checksum",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="source_commit_sha",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="module",
            name="source_content_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="module",
            name="source_path",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!/)(?!.*\\\\).+$", "Enter a repository-relative POSIX path."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="answer_envelope",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="source_checksum",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_commit_sha",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_content_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="question",
            name="source_path",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!/)(?!.*\\\\).+$", "Enter a repository-relative POSIX path."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="question",
            name="source_question_id",
            field=models.SlugField(
                blank=True,
                max_length=128,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[a-z0-9][a-z0-9._-]{0,127}$", "Enter a canonical source stable ID."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="source_checksum",
            field=models.CharField(
                blank=True,
                max_length=64,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="source_commit_sha",
            field=models.CharField(
                blank=True,
                max_length=40,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                    )
                ],
            ),
        ),
        migrations.AddField(
            model_name="unit",
            name="source_content_id",
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="unit",
            name="source_path",
            field=models.CharField(
                blank=True,
                max_length=1024,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        "^(?!/)(?!.*\\\\).+$", "Enter a repository-relative POSIX path."
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_checksum__isnull", True),
                        ("source_commit_sha__isnull", True),
                        ("source_content_id__isnull", True),
                        ("source_path__isnull", True),
                    ),
                    models.Q(
                        ("source_checksum__isnull", False),
                        ("source_commit_sha__isnull", False),
                        ("source_content_id__isnull", False),
                        ("source_path__isnull", False),
                        ("source_commit_sha__regex", "^[0-9a-f]{40}$"),
                        ("source_checksum__regex", "^[0-9a-f]{64}$"),
                    ),
                    _connector="OR",
                ),
                name="courses_cohort_source_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="cohort",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_content_id__isnull", False)),
                fields=("course", "source_content_id"),
                name="courses_cohort_source_content_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_checksum__isnull", True),
                        ("source_commit_sha__isnull", True),
                        ("source_content_id__isnull", True),
                        ("source_path__isnull", True),
                        ("source_stable_id__isnull", True),
                    ),
                    models.Q(
                        ("source_checksum__isnull", False),
                        ("source_commit_sha__isnull", False),
                        ("source_content_id__isnull", False),
                        ("source_path__isnull", False),
                        ("source_stable_id__isnull", False),
                        ("source_commit_sha__regex", "^[0-9a-f]{40}$"),
                        ("source_checksum__regex", "^[0-9a-f]{64}$"),
                    ),
                    _connector="OR",
                ),
                name="courses_course_source_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_content_id__isnull", False)),
                fields=("source_content_id",),
                name="courses_course_source_content_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_stable_id__isnull", False)),
                fields=("source_stable_id",),
                name="courses_course_source_stable_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="course",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_stable_id__isnull", True),
                    ("source_stable_id__regex", "^[a-z0-9][a-z0-9._-]{0,127}$"),
                    _connector="OR",
                ),
                name="courses_course_source_stable_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="homework",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_checksum__isnull", True),
                        ("source_commit_sha__isnull", True),
                        ("source_content_id__isnull", True),
                        ("source_path__isnull", True),
                    ),
                    models.Q(
                        ("source_checksum__isnull", False),
                        ("source_commit_sha__isnull", False),
                        ("source_content_id__isnull", False),
                        ("source_path__isnull", False),
                        ("source_commit_sha__regex", "^[0-9a-f]{40}$"),
                        ("source_checksum__regex", "^[0-9a-f]{64}$"),
                    ),
                    _connector="OR",
                ),
                name="courses_homework_source_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="homework",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_content_id__isnull", False)),
                fields=("course", "source_content_id"),
                name="courses_homework_source_content_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_checksum__isnull", True),
                        ("source_commit_sha__isnull", True),
                        ("source_content_id__isnull", True),
                        ("source_path__isnull", True),
                    ),
                    models.Q(
                        ("source_checksum__isnull", False),
                        ("source_commit_sha__isnull", False),
                        ("source_content_id__isnull", False),
                        ("source_path__isnull", False),
                        ("source_commit_sha__regex", "^[0-9a-f]{40}$"),
                        ("source_checksum__regex", "^[0-9a-f]{64}$"),
                    ),
                    _connector="OR",
                ),
                name="courses_module_source_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="module",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_content_id__isnull", False)),
                fields=("cohort", "source_content_id"),
                name="courses_module_source_content_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_checksum__isnull", True),
                        ("source_commit_sha__isnull", True),
                        ("source_content_id__isnull", True),
                        ("source_path__isnull", True),
                        ("source_question_id__isnull", True),
                    ),
                    models.Q(
                        ("source_checksum__isnull", False),
                        ("source_commit_sha__isnull", False),
                        ("source_content_id__isnull", False),
                        ("source_path__isnull", False),
                        ("source_question_id__isnull", False),
                        ("source_commit_sha__regex", "^[0-9a-f]{40}$"),
                        ("source_checksum__regex", "^[0-9a-f]{64}$"),
                    ),
                    _connector="OR",
                ),
                name="courses_question_source_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_content_id__isnull", False)),
                fields=("homework", "source_content_id"),
                name="courses_question_source_content_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_question_id__isnull", False)),
                fields=("homework", "source_question_id"),
                name="courses_question_source_stable_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="question",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("source_question_id__isnull", True),
                    ("source_question_id__regex", "^[a-z0-9][a-z0-9._-]{0,127}$"),
                    _connector="OR",
                ),
                name="courses_question_source_stable_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("source_checksum__isnull", True),
                        ("source_commit_sha__isnull", True),
                        ("source_content_id__isnull", True),
                        ("source_path__isnull", True),
                    ),
                    models.Q(
                        ("source_checksum__isnull", False),
                        ("source_commit_sha__isnull", False),
                        ("source_content_id__isnull", False),
                        ("source_path__isnull", False),
                        ("source_commit_sha__regex", "^[0-9a-f]{40}$"),
                        ("source_checksum__regex", "^[0-9a-f]{64}$"),
                    ),
                    _connector="OR",
                ),
                name="courses_unit_source_complete",
            ),
        ),
        migrations.AddConstraint(
            model_name="unit",
            constraint=models.UniqueConstraint(
                condition=models.Q(("source_content_id__isnull", False)),
                fields=("module", "source_content_id"),
                name="courses_unit_source_content_uq",
            ),
        ),
        migrations.AddIndex(
            model_name="coursecurriculumimportrun",
            index=models.Index(
                fields=["source_uuid", "state", "-created_at"], name="courses_curr_import_state_idx"
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecurriculumimportrun",
            constraint=models.UniqueConstraint(
                fields=("source_uuid", "commit_sha", "parser_version"),
                name="courses_curriculum_import_identity_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecurriculumimportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "state__in",
                        ("received", "validating", "applying", "succeeded", "rejected", "failed"),
                    )
                ),
                name="courses_curriculum_import_state_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecurriculumimportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("commit_sha__regex", "^[0-9a-f]{40}$")),
                name="courses_curriculum_import_commit_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecurriculumimportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("manifest_checksum__isnull", True),
                    ("manifest_checksum__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="courses_curriculum_import_manifest_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecurriculumimportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("schema_version__gte", 1)),
                name="courses_curriculum_import_schema_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecurriculumimportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("source_stable_id__regex", "^[a-z0-9][a-z0-9._-]{0,127}$")),
                name="courses_curriculum_import_source_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecurriculumimportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("repository_owner__regex", "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
                ),
                name="courses_curriculum_import_owner_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecurriculumimportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("repository_name__regex", "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
                ),
                name="courses_curriculum_import_repo_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecurriculumimportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("repository_branch__regex", "^[A-Za-z0-9][A-Za-z0-9._/-]{0,254}$")
                ),
                name="courses_curriculum_import_branch_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="coursecurriculumimportrun",
            constraint=models.CheckConstraint(
                condition=models.Q(("parser_version__regex", "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")),
                name="courses_curriculum_import_parser_ck",
            ),
        ),
    ]
