# Generated by Django 6.0.8 on 2026-09-02 14:20

import courses.curriculum_source_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0052_merge_duplicate_course_families'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='code_sources',
            field=models.JSONField(blank=True, default=list, help_text='Companion code files declared by the course repository frontmatter.', validators=[courses.curriculum_source_validators.validate_unit_code_sources]),
        ),
        migrations.AddField(
            model_name='unit',
            name='video_url',
            field=models.URLField(blank=True, help_text='Lesson video declared by the course repository frontmatter.'),
        ),
    ]
