# Generated by Django 6.0.8 on 2026-09-02 14:44

import courses.curriculum_source_validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0053_unit_lesson_video_and_code_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='homework',
            name='instructions_source_path',
            field=models.CharField(blank=True, default='', help_text='Repository path of the Markdown file the instructions were imported from.', max_length=1024, validators=[courses.curriculum_source_validators.validate_source_path]),
        ),
    ]
