# Generated by Django 6.0.8 on 2026-09-03 10:32

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PendingUnsubscribe',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('unsubscribe_token', models.CharField(max_length=128, unique=True)),
                ('token_fingerprint', models.CharField(db_index=True, max_length=32)),
                ('scope', models.CharField(max_length=16)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('applied', 'Applied'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=16)),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('last_outcome', models.CharField(blank=True, max_length=32)),
                ('accepted_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'pending unsubscribe',
                'verbose_name_plural': 'pending unsubscribes',
                'indexes': [models.Index(fields=['status', 'accepted_at'], name='pending_unsub_status_idx')],
            },
        ),
    ]
