# Generated by Django 6.0.8 on 2026-09-09 15:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('email_app', '0002_copy_pending_unsubscribe_to_cb_mail'),
        ('email_app', '0002_pendingunsubscribe_generation'),
    ]

    operations = [
    ]
