# Generated by Django 6.0.8 on 2026-09-16 20:28

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models



# The old events_* registrant tables, in the order their rows must be written so
# foreign keys land after the rows they point at.
_COPY_ORDER = (
    ("events_eventregistrantidentity", "event_registrants", "EventRegistrantIdentity"),
    ("events_eventregistration", "event_registrants", "EventRegistration"),
    ("events_eventregistrantinterestsignal", "event_registrants", "EventRegistrantInterestSignal"),
    ("events_eventregistrantimportprogress", "event_registrants", "EventRegistrantImportProgress"),
)


def copy_registrant_rows_out_of_events(apps, schema_editor):
    """Copy registrant rows out of the old events_* tables before events.0010 drops them.

    The old and new tables carry identical column names, so each row is read as
    a dict from the source table and written into the new model as-is.  On a
    fresh database where the events app never created its tables (or after the
    P5 rebuild removes it), this is a no-op.  Irreversible by design: the
    source tables are dropped immediately after, so there is nothing to copy
    back to.
    """

    connection = schema_editor.connection
    existing = set(connection.introspection.table_names(connection.cursor()))
    for table, app_label, model_name in _COPY_ORDER:
        if table not in existing:
            continue
        Model = apps.get_model(app_label, model_name)
        with connection.cursor() as cursor:
            columns = [
                column.name
                for column in connection.introspection.get_table_description(cursor, table)
            ]
            select = ", ".join(f'"{name}"' for name in columns)
            for row in cursor.execute(f'SELECT {select} FROM "{table}"').fetchall():
                Model.objects.create(**dict(zip(columns, row)))



class Migration(migrations.Migration):



    initial = True

    dependencies = [
        ('events', '0003_provisional_integration_attempt'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventRegistrantIdentity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('normalized_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('account', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='event_registrant_identity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='EventRegistrantImportProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('external_event_identifier', models.CharField(max_length=512)),
                ('completed', models.BooleanField(default=False)),
                ('rows_total', models.PositiveIntegerField(default=0)),
                ('rows_written', models.PositiveIntegerField(default=0)),
                ('rows_skipped', models.PositiveIntegerField(default=0)),
                ('matched_account_total', models.PositiveIntegerField(default=0)),
                ('matched_prior_identity_total', models.PositiveIntegerField(default=0)),
                ('new_identity_total', models.PositiveIntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('provider', 'external_event_identifier'),
                'constraints': [models.UniqueConstraint(fields=('provider', 'external_event_identifier'), name='event_registrants_import_progress_provider_external_unique')],
            },
        ),
        migrations.CreateModel(
            name='EventRegistrantInterestSignal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('general', 'General'), ('conference', 'Conference'), ('podcast', 'Podcast'), ('production', 'Production'), ('analytics', 'Analytics'), ('data', 'Data'), ('soft_skills', 'Soft skills'), ('data_science', 'Data science')], max_length=32)),
                ('source', models.CharField(choices=[('mailchimp_tag', 'Mailchimp tag')], default='mailchimp_tag', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='interest_signals', to='event_registrants.eventregistrantidentity')),
            ],
            options={
                'ordering': ('identity_id', 'category', 'source'),
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('status', models.CharField(max_length=32)),
                ('registered_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrant_registrations', to='events.event')),
                ('identity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='registrations', to='event_registrants.eventregistrantidentity')),
            ],
            options={
                'ordering': ('event_id', 'provider', 'id'),
            },
        ),
        migrations.AddConstraint(
            model_name='eventregistrantidentity',
            constraint=models.UniqueConstraint(condition=models.Q(('account__isnull', True)), fields=('normalized_email',), name='event_registrants_identity_email_unique_unmatched'),
        ),
        migrations.AddConstraint(
            model_name='eventregistrantidentity',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('account__isnull', False), ('normalized_email__isnull', True)), models.Q(('account__isnull', True), ('normalized_email__isnull', False)), _connector='OR'), name='event_registrants_identity_exactly_one_anchor'),
        ),
        migrations.AddConstraint(
            model_name='eventregistrantinterestsignal',
            constraint=models.UniqueConstraint(fields=('identity', 'category', 'source'), name='event_registrants_interest_signal_unique'),
        ),
        migrations.AddIndex(
            model_name='eventregistration',
            index=models.Index(fields=['identity'], name='event_registrants_reg_identity'),
        ),
        migrations.RunPython(copy_registrant_rows_out_of_events, migrations.RunPython.noop),
    ]

