# Generated by Django 6.0.8 on 2026-09-16 19:58

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models



# The old events_* historical tables, in the order their rows must be written so
# foreign keys land after the rows they point at.
_COPY_ORDER = (
    ("events_historicalregistrationsourcerun", "historical_registrations", "HistoricalRegistrationSourceRun"),
    ("events_historicalregistrationaggregaterevision", "historical_registrations", "HistoricalRegistrationAggregateRevision"),
    ("events_historicalregistrationaggregateslot", "historical_registrations", "HistoricalRegistrationAggregateSlot"),
    ("events_historicalregistrationpointerdisplacement", "historical_registrations", "HistoricalRegistrationPointerDisplacement"),
    ("events_historicalregistrationtotalstate", "historical_registrations", "HistoricalRegistrationTotalState"),
)


def copy_historical_rows_out_of_events(apps, schema_editor):
    """Copy aggregate rows out of the old events_* tables before events.0009 drops them.

    The old and new tables carry identical column names, so each row is read as
    a dict from the source table and written into the new model as-is.  On a
    fresh database where the events app never created its tables (or after the
    P5 rebuild removes it), this is a no-op.  Irreversible by design: the
    source tables are dropped immediately after, so there is nothing to copy
    back to.
    """

    connection = schema_editor.connection
    existing = set(connection.introspection.table_names(connection.cursor()))
    for table, app_label, model_name in _COPY_ORDER:
        if table not in existing:
            continue
        Model = apps.get_model(app_label, model_name)
        with connection.cursor() as cursor:
            columns = [
                column.name
                for column in connection.introspection.get_table_description(cursor, table)
            ]
            select = ", ".join(f'"{name}"' for name in columns)
            for row in cursor.execute(f'SELECT {select} FROM "{table}"').fetchall():
                Model.objects.create(**dict(zip(columns, row)))



# The old events_* historical tables, in the order their rows must be written so
# foreign keys land after the rows they point at.
_COPY_ORDER = (
    ("events_historicalregistrationsourcerun", "historical_registrations", "HistoricalRegistrationSourceRun"),
    ("events_historicalregistrationaggregaterevision", "historical_registrations", "HistoricalRegistrationAggregateRevision"),
    ("events_historicalregistrationaggregateslot", "historical_registrations", "HistoricalRegistrationAggregateSlot"),
    ("events_historicalregistrationpointerdisplacement", "historical_registrations", "HistoricalRegistrationPointerDisplacement"),
    ("events_historicalregistrationtotalstate", "historical_registrations", "HistoricalRegistrationTotalState"),
)


def copy_historical_rows_out_of_events(apps, schema_editor):
    """Copy aggregate rows out of the old events_* tables before events.0009 drops them.

    The old and new tables carry identical column names, so each row is read as
    a dict from the source table and written into the new model as-is.  On a
    fresh database where the events app never created its tables (or after the
    P5 rebuild removes it), this is a no-op.  Irreversible by design: the
    source tables are dropped immediately after, so there is nothing to copy
    back to.
    """

    connection = schema_editor.connection
    existing = set(connection.introspection.table_names(connection.cursor()))
    for table, app_label, model_name in _COPY_ORDER:
        if table not in existing:
            continue
        Model = apps.get_model(app_label, model_name)
        with connection.cursor() as cursor:
            columns = [
                column.name
                for column in connection.introspection.get_table_description(cursor, table)
            ]
            select = ", ".join(f'"{name}"' for name in columns)
            for row in cursor.execute(f'SELECT {select} FROM "{table}"').fetchall():
                Model.objects.create(**dict(zip(columns, row)))


class Migration(migrations.Migration):



    initial = True

    dependencies = [
        ('events', '0008_remove_eventqnacohostinvite_events_qna_cohost_name_unique_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalRegistrationAggregateRevision',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('external_event_identifier', models.CharField(max_length=512)),
                ('eligible_count', models.PositiveBigIntegerField()),
                ('excluded_count', models.PositiveBigIntegerField(default=0)),
                ('quarantined_count', models.PositiveBigIntegerField(default=0)),
                ('coverage_boundary', models.CharField(max_length=128)),
                ('status_policy_version', models.CharField(max_length=32)),
                ('combination_policy', models.CharField(choices=[('additive_disjoint', 'Additive, disjoint'), ('replacement', 'Replacement'), ('exclude', 'Exclude')], max_length=24)),
                ('aggregate_checksum', models.CharField(max_length=64)),
                ('state', models.CharField(choices=[('staged', 'Staged'), ('validated', 'Validated'), ('active', 'Active'), ('superseded', 'Superseded'), ('quarantined', 'Quarantined'), ('rolled_back', 'Rolled back')], default='staged', max_length=16)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='historical_registration_aggregate_revisions', to='events.event')),
            ],
            options={
                'ordering': ('source_run_id', 'created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationAggregateSlot',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_repository', models.CharField(max_length=255)),
                ('canonical_revision', models.CharField(max_length=64)),
                ('canonical_source_key', models.CharField(max_length=512)),
                ('canonical_slug_snapshot', models.SlugField(max_length=255)),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('coverage_boundary', models.CharField(max_length=128)),
                ('replacement_revision_id', models.UUIDField(blank=True, null=True)),
                ('replacement_eligible_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('replacement_combination_policy', models.CharField(blank=True, choices=[('additive_disjoint', 'Additive, disjoint'), ('replacement', 'Replacement'), ('exclude', 'Exclude')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('active_revision', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='active_slot', to='historical_registrations.historicalregistrationaggregaterevision')),
            ],
            options={
                'ordering': ('canonical_source_key', 'provider', 'coverage_boundary'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationPointerDisplacement',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('row_replacement_revision_id', models.UUIDField(blank=True, null=True)),
                ('row_replacement_eligible_count', models.PositiveBigIntegerField(blank=True, null=True)),
                ('row_replacement_combination_policy', models.CharField(blank=True, choices=[('additive_disjoint', 'Additive, disjoint'), ('replacement', 'Replacement'), ('exclude', 'Exclude')], max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('displaced_revision', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='displaced_by_replacements', to='historical_registrations.historicalregistrationaggregaterevision')),
                ('replacing_revision', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pointer_displacements', to='historical_registrations.historicalregistrationaggregaterevision')),
                ('slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='displacement_history', to='historical_registrations.historicalregistrationaggregateslot')),
            ],
            options={
                'ordering': ('created_at', 'id'),
            },
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationSourceRun',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('luma', 'Luma'), ('eventbrite', 'Eventbrite')], max_length=16)),
                ('adapter_version', models.CharField(max_length=32)),
                ('schema_version', models.CharField(max_length=64)),
                ('whole_source_checksum', models.CharField(max_length=64)),
                ('source_reference_digest', models.CharField(max_length=64)),
                ('manifest_entry_total', models.PositiveIntegerField()),
                ('manifest_event_total', models.PositiveIntegerField()),
                ('parsed_row_total', models.PositiveBigIntegerField()),
                ('eligible_row_total', models.PositiveBigIntegerField()),
                ('excluded_row_total', models.PositiveBigIntegerField()),
                ('quarantined_event_total', models.PositiveIntegerField(default=0)),
                ('status_totals', models.JSONField(default=dict)),
                ('state_totals', models.JSONField(default=dict)),
                ('reason_codes', models.JSONField(default=list)),
                ('mapping_set_revision', models.PositiveBigIntegerField()),
                ('policy_version', models.CharField(max_length=32)),
                ('state', models.CharField(choices=[('staged', 'Staged'), ('validated', 'Validated'), ('active', 'Active'), ('cancelled', 'Cancelled'), ('rolled_back', 'Rolled back'), ('quarantined', 'Quarantined')], default='staged', max_length=16)),
                ('actor_ref', models.CharField(blank=True, max_length=128)),
                ('reason_code', models.CharField(blank=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_registration_source_runs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at', '-id'),
                'permissions': (('historical_registration_import_manage', 'Can manage historical registration aggregate imports'), ('historical_registration_mapping_manage', 'Can manage historical event mappings')),
            },
        ),
        migrations.AddField(
            model_name='historicalregistrationaggregaterevision',
            name='source_run',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aggregate_revisions', to='historical_registrations.historicalregistrationsourcerun'),
        ),
        migrations.CreateModel(
            name='HistoricalRegistrationTotalState',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('canonical_repository', models.CharField(max_length=255)),
                ('canonical_revision', models.CharField(max_length=64)),
                ('canonical_source_key', models.CharField(max_length=512)),
                ('canonical_slug_snapshot', models.SlugField(max_length=255)),
                ('complete', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('canonical_repository', 'canonical_revision', 'canonical_source_key'), name='historical_registrations_total_source_unique'), models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='historical_registrations_total_revision_positive')],
            },
        ),
        migrations.AddIndex(
            model_name='historicalregistrationaggregateslot',
            index=models.Index(fields=['canonical_repository', 'canonical_revision', 'canonical_source_key'], name='hist_registrations_slot_source'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregateslot',
            constraint=models.UniqueConstraint(fields=('canonical_repository', 'canonical_revision', 'canonical_source_key', 'provider', 'coverage_boundary'), name='historical_registrations_active_slot_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregateslot',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='historical_registrations_slot_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregateslot',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('active_revision__isnull', False), ('replacement_combination_policy', ''), ('replacement_eligible_count__isnull', True), ('replacement_revision_id__isnull', True)), models.Q(('active_revision__isnull', True), ('replacement_combination_policy__gt', ''), ('replacement_eligible_count__isnull', False), ('replacement_revision_id__isnull', False)), models.Q(('active_revision__isnull', True), ('replacement_combination_policy', ''), ('replacement_eligible_count__isnull', True), ('replacement_revision_id__isnull', True)), _connector='OR'), name='historical_registrations_slot_one_pointer'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationpointerdisplacement',
            constraint=models.UniqueConstraint(fields=('replacing_revision', 'slot'), name='historical_registrations_displacement_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationpointerdisplacement',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('displaced_revision__isnull', False), ('row_replacement_combination_policy', ''), ('row_replacement_eligible_count__isnull', True), ('row_replacement_revision_id__isnull', True)), models.Q(('displaced_revision__isnull', True), ('row_replacement_combination_policy__gt', ''), ('row_replacement_eligible_count__isnull', False), ('row_replacement_revision_id__isnull', False)), _connector='OR'), name='historical_registrations_displacement_one_pointer'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationsourcerun',
            index=models.Index(fields=['provider', 'state', '-created_at'], name='hist_registrations_run_state'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationsourcerun',
            index=models.Index(fields=['whole_source_checksum'], name='hist_regs_run_checksum'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.UniqueConstraint(fields=('provider', 'whole_source_checksum', 'schema_version', 'mapping_set_revision', 'policy_version'), name='historical_registrations_run_replay_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='historical_registrations_run_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.CheckConstraint(condition=models.Q(('eligible_row_total__lte', models.F('parsed_row_total'))), name='historical_registrations_run_eligible_bounded'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationsourcerun',
            constraint=models.CheckConstraint(condition=models.Q(('excluded_row_total__lte', models.F('parsed_row_total'))), name='historical_registrations_run_excluded_bounded'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationaggregaterevision',
            index=models.Index(fields=['event', 'state', '-created_at'], name='hist_registrations_agg_state'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationaggregaterevision',
            index=models.Index(fields=['aggregate_checksum'], name='hist_regs_agg_checksum'),
        ),
        migrations.AddIndex(
            model_name='historicalregistrationaggregaterevision',
            index=models.Index(fields=['source_run', 'external_event_identifier'], name='hist_regs_agg_run_ext_id'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregaterevision',
            constraint=models.UniqueConstraint(fields=('source_run', 'external_event_identifier', 'aggregate_checksum'), name='historical_registrations_aggregate_revision_unique'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregaterevision',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='historical_registrations_aggregate_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='historicalregistrationaggregaterevision',
            constraint=models.CheckConstraint(condition=models.Q(('external_event_identifier__gt', '')), name='historical_registrations_aggregate_external_id_nonempty'),
        ),
        migrations.RunPython(copy_historical_rows_out_of_events, migrations.RunPython.noop),
        migrations.RunPython(copy_historical_rows_out_of_events, migrations.RunPython.noop),
    ]

