# Generated by Django 6.0.8 on 2026-09-03 10:32

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='APIPrincipal',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('human', 'Human'), ('service', 'Service')], max_length=16)),
                ('name', models.CharField(max_length=120)),
                ('identity_snapshot', models.CharField(max_length=128)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_management_api_principals', to=settings.AUTH_USER_MODEL)),
                ('permissions', models.ManyToManyField(blank=True, related_name='management_api_principals', to='auth.permission')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='management_api_principal', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('name', 'id'),
                'permissions': (('read_admin_health', 'Can read management API health'), ('manage_api_credentials', 'Can manage API credentials')),
            },
        ),
        migrations.CreateModel(
            name='APICredential',
            fields=[
                ('revision', models.PositiveBigIntegerField(default=1)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120)),
                ('prefix', models.CharField(max_length=16)),
                ('secret_digest', models.CharField(max_length=256)),
                ('digest_algorithm', models.CharField(max_length=32)),
                ('digest_version', models.PositiveSmallIntegerField()),
                ('scopes', models.JSONField(default=list)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('rotated_at', models.DateTimeField(blank=True, null=True)),
                ('overlap_expires_at', models.DateTimeField(blank=True, null=True)),
                ('last_used_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_management_api_credentials', to=settings.AUTH_USER_MODEL)),
                ('predecessor', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='successor', to='management_auth.apicredential')),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credentials', to='management_auth.apiprincipal')),
            ],
            options={
                'ordering': ('-created_at', '-id'),
            },
        ),
        migrations.CreateModel(
            name='APIRateAdmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('subject_hash', models.CharField(max_length=64)),
                ('cost_class', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('adaptive', 'Adaptive digest')], max_length=16)),
                ('cost', models.PositiveSmallIntegerField()),
                ('created_at', models.DateTimeField()),
                ('principal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rate_admissions', to='management_auth.apiprincipal')),
            ],
        ),
        migrations.CreateModel(
            name='APIRateSubject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_hash', models.CharField(max_length=64)),
                ('cost_class', models.CharField(choices=[('read', 'Read'), ('write', 'Write'), ('adaptive', 'Adaptive digest')], max_length=16)),
                ('revision', models.PositiveBigIntegerField(default=0)),
            ],
            options={
                'constraints': [models.UniqueConstraint(fields=('subject_hash', 'cost_class'), name='mgmt_rate_subject_class_unique')],
            },
        ),
        migrations.CreateModel(
            name='ManagementIdempotencyRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('operation', models.CharField(max_length=128)),
                ('key_hash', models.CharField(max_length=64)),
                ('request_hash', models.CharField(max_length=64)),
                ('status', models.CharField(choices=[('in_progress', 'In progress'), ('completed', 'Completed')], max_length=16)),
                ('safe_result', models.JSONField(blank=True, null=True)),
                ('owner_token', models.UUIDField(default=uuid.uuid4, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField()),
                ('principal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='idempotency_records', to='management_auth.apiprincipal')),
            ],
        ),
        migrations.AddIndex(
            model_name='apiprincipal',
            index=models.Index(fields=['kind', 'is_active', 'id'], name='mgmt_principal_active'),
        ),
        migrations.AddConstraint(
            model_name='apiprincipal',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='mgmt_principal_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='apiprincipal',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('kind', 'human'), ('user__isnull', False)), models.Q(('kind', 'service'), ('user__isnull', True)), _connector='OR'), name='mgmt_principal_kind_user_consistent'),
        ),
        migrations.AddIndex(
            model_name='apicredential',
            index=models.Index(fields=['principal', 'revoked_at', 'expires_at'], name='mgmt_credential_active'),
        ),
        migrations.AddConstraint(
            model_name='apicredential',
            constraint=models.UniqueConstraint(fields=('prefix',), name='mgmt_credential_prefix_unique'),
        ),
        migrations.AddConstraint(
            model_name='apicredential',
            constraint=models.CheckConstraint(condition=models.Q(('revision__gte', 1)), name='mgmt_credential_revision_positive'),
        ),
        migrations.AddConstraint(
            model_name='apicredential',
            constraint=models.CheckConstraint(condition=models.Q(('digest_version__gte', 1)), name='mgmt_credential_digest_version_positive'),
        ),
        migrations.AddConstraint(
            model_name='apicredential',
            constraint=models.CheckConstraint(condition=models.Q(('expires_at__gt', models.F('created_at'))), name='mgmt_credential_expiry_after_create'),
        ),
        migrations.AddConstraint(
            model_name='apicredential',
            constraint=models.CheckConstraint(condition=models.Q(('overlap_expires_at__isnull', True), models.Q(('overlap_expires_at__gte', models.F('rotated_at')), ('rotated_at__isnull', False)), _connector='OR'), name='mgmt_credential_overlap_consistent'),
        ),
        migrations.AddIndex(
            model_name='apirateadmission',
            index=models.Index(fields=['subject_hash', 'cost_class', 'created_at'], name='mgmt_rate_window'),
        ),
        migrations.AddIndex(
            model_name='apirateadmission',
            index=models.Index(fields=['created_at'], name='mgmt_rate_cleanup'),
        ),
        migrations.AddConstraint(
            model_name='apirateadmission',
            constraint=models.CheckConstraint(condition=models.Q(('cost__gte', 1), ('cost__lte', 10)), name='mgmt_rate_cost_bounded'),
        ),
        migrations.AddIndex(
            model_name='managementidempotencyrecord',
            index=models.Index(fields=['expires_at'], name='mgmt_idempotency_expiry'),
        ),
        migrations.AddConstraint(
            model_name='managementidempotencyrecord',
            constraint=models.UniqueConstraint(fields=('principal', 'operation', 'key_hash'), name='mgmt_idempotency_principal_operation_key'),
        ),
        migrations.AddConstraint(
            model_name='managementidempotencyrecord',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('completed_at__isnull', True), ('safe_result__isnull', True), ('status', 'in_progress')), models.Q(('completed_at__isnull', False), ('safe_result__isnull', False), ('status', 'completed')), _connector='OR'), name='mgmt_idempotency_state_consistent'),
        ),
    ]
