# Generated by Django 6.0.7 on 2026-08-08 08:56

import content.models
import django.core.validators
import django.db.models.deletion
import django.db.models.functions.text
import uuid
from django.db import migrations, models


POSTGRES_GUARDS = r"""
CREATE OR REPLACE FUNCTION dtc_content_active_state_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    PERFORM pg_advisory_xact_lock(1146372913, 37);

    IF EXISTS (
        SELECT 1
        FROM content_contentsource source
        LEFT JOIN content_contentrelease release
          ON release.id = source.active_release_id
        WHERE source.active_release_id IS NOT NULL
          AND (
              release.id IS NULL
              OR release.source_id <> source.id
              OR release.status <> 'active'
          )
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'content_source_active_state_ct',
            MESSAGE = 'content source active release invariant failed';
    END IF;

    IF EXISTS (
        SELECT 1
        FROM content_contentrelease release
        JOIN content_contentsource source ON source.id = release.source_id
        WHERE release.status = 'active'
          AND source.active_release_id IS DISTINCT FROM release.id
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'content_release_active_state_ct',
            MESSAGE = 'active content release pointer invariant failed';
    END IF;

    IF EXISTS (
        SELECT namespace.path
        FROM (
            SELECT document.exact_public_path AS path
            FROM content_contentdocument document
            JOIN content_contentsource source
              ON source.active_release_id = document.release_id
             AND source.enabled
            WHERE document.exact_public_path IS NOT NULL
            UNION ALL
            SELECT asset.stable_public_path AS path
            FROM content_contentasset asset
            JOIN content_contentsource source
              ON source.active_release_id = asset.release_id
             AND source.enabled
        ) namespace
        GROUP BY namespace.path
        HAVING count(*) > 1
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'content_active_path_namespace_ct',
            MESSAGE = 'active content path namespace collision';
    END IF;

    RETURN NULL;
END;
$function$;

CREATE OR REPLACE FUNCTION dtc_content_source_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
BEGIN
    IF TG_OP = 'UPDATE' AND NEW.stable_id IS DISTINCT FROM OLD.stable_id THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'content_source_stable_immutable',
            MESSAGE = 'content source stable identity is immutable';
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION dtc_content_release_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    allowed_transition boolean;
BEGIN
    IF TG_OP = 'DELETE' THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'content_release_no_delete',
            MESSAGE = 'content releases cannot be deleted';
    END IF;

    IF NEW.based_on_release_id IS NOT NULL AND NOT EXISTS (
        SELECT 1 FROM content_contentrelease base
        WHERE base.id = NEW.based_on_release_id AND base.source_id = NEW.source_id
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'content_release_base_source_ck',
            MESSAGE = 'content release base must belong to the same source';
    END IF;

    IF TG_OP = 'INSERT' THEN
        IF NEW.status <> 'queued' THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'content_release_transition_ck',
                MESSAGE = 'new content release must be queued';
        END IF;
        RETURN NEW;
    END IF;

    IF NEW.id IS DISTINCT FROM OLD.id
       OR NEW.created_at IS DISTINCT FROM OLD.created_at
       OR NEW.source_id IS DISTINCT FROM OLD.source_id
       OR NEW.sequence IS DISTINCT FROM OLD.sequence
       OR NEW.based_on_release_id IS DISTINCT FROM OLD.based_on_release_id
       OR NEW.commit_sha IS DISTINCT FROM OLD.commit_sha
       OR NEW.parser_version IS DISTINCT FROM OLD.parser_version
       OR NEW.rendering_version IS DISTINCT FROM OLD.rendering_version
       OR NEW.requested_at IS DISTINCT FROM OLD.requested_at
       OR NEW.initiator_ref IS DISTINCT FROM OLD.initiator_ref
       OR NEW.request_provenance IS DISTINCT FROM OLD.request_provenance
       OR NEW.webhook_delivery_id IS DISTINCT FROM OLD.webhook_delivery_id
       OR NEW.sync_request_id IS DISTINCT FROM OLD.sync_request_id
       OR NEW.public_contracts_sha256 IS DISTINCT FROM OLD.public_contracts_sha256
    THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'content_release_identity_immutable',
            MESSAGE = 'content release identity and provenance are immutable';
    END IF;

    IF OLD.status IN ('ready', 'active', 'superseded', 'invalid', 'failed') AND (
       NEW.document_count IS DISTINCT FROM OLD.document_count
       OR NEW.relation_count IS DISTINCT FROM OLD.relation_count
       OR NEW.asset_count IS DISTINCT FROM OLD.asset_count
       OR NEW.warning_count IS DISTINCT FROM OLD.warning_count
       OR NEW.warnings IS DISTINCT FROM OLD.warnings
       OR NEW.structured_errors IS DISTINCT FROM OLD.structured_errors
       OR NEW.search_build_id IS DISTINCT FROM OLD.search_build_id
       OR NEW.graph_build_id IS DISTINCT FROM OLD.graph_build_id
       OR NEW.asset_manifest_checksum IS DISTINCT FROM OLD.asset_manifest_checksum
    ) THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'content_release_evidence_immutable',
            MESSAGE = 'frozen content release evidence is immutable';
    END IF;

    IF OLD.status IN ('ready', 'active', 'superseded', 'invalid', 'failed') THEN
        IF NEW.status = OLD.status THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'content_release_frozen_update',
                MESSAGE = 'frozen content release requires an allowed lifecycle swap';
        END IF;
        IF NEW.fetched_at IS DISTINCT FROM OLD.fetched_at
           OR NEW.validated_at IS DISTINCT FROM OLD.validated_at
           OR NEW.failed_at IS DISTINCT FROM OLD.failed_at
           OR (OLD.status NOT IN ('ready', 'superseded')
               AND NEW.activated_at IS DISTINCT FROM OLD.activated_at)
           OR (OLD.status <> 'active' AND OLD.status <> 'superseded'
               AND NEW.superseded_at IS DISTINCT FROM OLD.superseded_at)
           OR (OLD.status = 'ready' AND NEW.superseded_at IS DISTINCT FROM OLD.superseded_at)
           OR (OLD.status = 'active' AND NEW.activated_at IS DISTINCT FROM OLD.activated_at)
        THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'content_release_lifecycle_fields',
                MESSAGE = 'frozen content release lifecycle fields changed unexpectedly';
        END IF;
    END IF;

    IF NEW.revision <> OLD.revision + 1 THEN
        RAISE EXCEPTION USING
            ERRCODE = '23514',
            CONSTRAINT = 'content_release_revision_step_ck',
            MESSAGE = 'content release revision must advance exactly once';
    END IF;

    IF NEW.status IS DISTINCT FROM OLD.status THEN
        allowed_transition :=
            (OLD.status = 'queued' AND NEW.status IN ('fetching', 'failed'))
            OR (OLD.status = 'fetching' AND NEW.status IN ('validating', 'failed'))
            OR (OLD.status = 'validating' AND NEW.status IN ('ready', 'invalid', 'failed'))
            OR (OLD.status = 'ready' AND NEW.status = 'active')
            OR (OLD.status = 'active' AND NEW.status = 'superseded')
            OR (OLD.status = 'superseded' AND NEW.status = 'active');
        IF NOT allowed_transition THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'content_release_transition_ck',
                MESSAGE = 'content release transition is not allowed';
        END IF;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE OR REPLACE FUNCTION dtc_content_child_guard()
RETURNS trigger
LANGUAGE plpgsql
AS $function$
DECLARE
    old_release uuid;
    new_release uuid;
    source_release uuid;
    target_release uuid;
    required_prefix text;
    suffix text;
    locked_parent record;
BEGIN
    IF TG_TABLE_NAME = 'content_contentrelation' THEN
        IF TG_OP IN ('UPDATE', 'DELETE') THEN
            SELECT release_id INTO old_release
            FROM content_contentdocument WHERE id = OLD.source_document_id;
        END IF;
        IF TG_OP IN ('INSERT', 'UPDATE') THEN
            SELECT release_id INTO new_release
            FROM content_contentdocument WHERE id = NEW.source_document_id;
        END IF;
    ELSE
        IF TG_OP IN ('UPDATE', 'DELETE') THEN
            old_release := OLD.release_id;
        END IF;
        IF TG_OP IN ('INSERT', 'UPDATE') THEN
            new_release := NEW.release_id;
        END IF;
    END IF;

    FOR locked_parent IN
        SELECT id, status
        FROM content_contentrelease
        WHERE id IN (old_release, new_release)
        ORDER BY id
        FOR SHARE
    LOOP
        IF locked_parent.status IN ('ready', 'active', 'superseded', 'invalid', 'failed') THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'content_frozen_child_mutation',
                MESSAGE = 'frozen content release children are immutable';
        END IF;
    END LOOP;

    IF TG_OP IN ('INSERT', 'UPDATE') AND TG_TABLE_NAME = 'content_contentrelation' THEN
        IF NEW.resolved_target_document_id IS NOT NULL THEN
            SELECT release_id INTO source_release
            FROM content_contentdocument WHERE id = NEW.source_document_id;
            SELECT release_id INTO target_release
            FROM content_contentdocument WHERE id = NEW.resolved_target_document_id;
            IF source_release IS DISTINCT FROM target_release THEN
                RAISE EXCEPTION USING
                    ERRCODE = '23514',
                    CONSTRAINT = 'content_relation_same_release_ck',
                    MESSAGE = 'content relation target must belong to the same release';
            END IF;
        END IF;
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') AND TG_TABLE_NAME = 'content_contentdocument' THEN
        IF NEW.exact_public_path IS NOT NULL AND (
            left(NEW.exact_public_path, 1) <> '/'
            OR left(NEW.exact_public_path, 2) = '//'
            OR NEW.exact_public_path ~ '[?#[:space:][:cntrl:]]'
        ) THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'content_doc_exact_path_ck',
                MESSAGE = 'content document public path is invalid';
        END IF;
    END IF;

    IF TG_OP IN ('INSERT', 'UPDATE') AND TG_TABLE_NAME = 'content_contentasset' THEN
        IF left(NEW.stable_public_path, 1) <> '/'
           OR left(NEW.stable_public_path, 2) = '//'
           OR NEW.stable_public_path ~ '[?#[:space:][:cntrl:]]'
        THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'content_asset_public_path_ck',
                MESSAGE = 'content asset public path is invalid';
        END IF;

        SELECT 'content/' || source.stable_id || '/' || release.id::text || '/'
        INTO required_prefix
        FROM content_contentrelease release
        JOIN content_contentsource source ON source.id = release.source_id
        WHERE release.id = NEW.release_id;
        suffix := substr(NEW.storage_key, length(required_prefix) + 1);
        IF required_prefix IS NULL
           OR left(NEW.storage_key, length(required_prefix)) <> required_prefix
           OR suffix = ''
           OR position(chr(92) in NEW.storage_key) > 0
           OR NEW.storage_key ~ '[[:cntrl:]]'
           OR NEW.storage_key ~ '(^|/)([.]|[.][.]|)($|/)'
        THEN
            RAISE EXCEPTION USING
                ERRCODE = '23514',
                CONSTRAINT = 'content_asset_storage_key_ck',
                MESSAGE = 'content asset storage key is invalid';
        END IF;
    END IF;

    IF TG_OP = 'DELETE' THEN
        RETURN OLD;
    END IF;
    RETURN NEW;
END;
$function$;

CREATE TRIGGER content_source_stable_tr
BEFORE UPDATE OF stable_id ON content_contentsource
FOR EACH ROW EXECUTE FUNCTION dtc_content_source_guard();

CREATE TRIGGER content_release_frozen_tr
BEFORE INSERT OR UPDATE OR DELETE ON content_contentrelease
FOR EACH ROW EXECUTE FUNCTION dtc_content_release_guard();

CREATE TRIGGER content_document_frozen_tr
BEFORE INSERT OR UPDATE OR DELETE ON content_contentdocument
FOR EACH ROW EXECUTE FUNCTION dtc_content_child_guard();

CREATE TRIGGER content_relation_frozen_tr
BEFORE INSERT OR UPDATE OR DELETE ON content_contentrelation
FOR EACH ROW EXECUTE FUNCTION dtc_content_child_guard();

CREATE TRIGGER content_asset_frozen_tr
BEFORE INSERT OR UPDATE OR DELETE ON content_contentasset
FOR EACH ROW EXECUTE FUNCTION dtc_content_child_guard();

CREATE CONSTRAINT TRIGGER content_source_active_state_ct
AFTER INSERT OR DELETE OR UPDATE OF active_release_id, enabled ON content_contentsource
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION dtc_content_active_state_guard();

CREATE CONSTRAINT TRIGGER content_release_active_state_ct
AFTER INSERT OR DELETE OR UPDATE OF status, source_id ON content_contentrelease
DEFERRABLE INITIALLY DEFERRED
FOR EACH ROW EXECUTE FUNCTION dtc_content_active_state_guard();
"""

DROP_POSTGRES_GUARDS = """
DROP TRIGGER IF EXISTS content_release_active_state_ct ON content_contentrelease;
DROP TRIGGER IF EXISTS content_source_active_state_ct ON content_contentsource;
DROP TRIGGER IF EXISTS content_asset_frozen_tr ON content_contentasset;
DROP TRIGGER IF EXISTS content_relation_frozen_tr ON content_contentrelation;
DROP TRIGGER IF EXISTS content_document_frozen_tr ON content_contentdocument;
DROP TRIGGER IF EXISTS content_release_frozen_tr ON content_contentrelease;
DROP TRIGGER IF EXISTS content_source_stable_tr ON content_contentsource;
DROP FUNCTION IF EXISTS dtc_content_child_guard();
DROP FUNCTION IF EXISTS dtc_content_release_guard();
DROP FUNCTION IF EXISTS dtc_content_source_guard();
DROP FUNCTION IF EXISTS dtc_content_active_state_guard();
"""


def install_postgres_guards(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(POSTGRES_GUARDS)


def remove_postgres_guards(apps, schema_editor):
    del apps
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(DROP_POSTGRES_GUARDS)


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ContentRelease",
            fields=[
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("sequence", models.PositiveBigIntegerField()),
                (
                    "commit_sha",
                    models.CharField(
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                            )
                        ],
                    ),
                ),
                ("parser_version", models.CharField(max_length=128)),
                ("rendering_version", models.CharField(max_length=128)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("queued", "Queued"),
                            ("fetching", "Fetching"),
                            ("validating", "Validating"),
                            ("ready", "Ready"),
                            ("active", "Active"),
                            ("superseded", "Superseded"),
                            ("invalid", "Invalid"),
                            ("failed", "Failed"),
                        ],
                        default="queued",
                        max_length=16,
                    ),
                ),
                ("requested_at", models.DateTimeField()),
                ("fetched_at", models.DateTimeField(blank=True, null=True)),
                ("validated_at", models.DateTimeField(blank=True, null=True)),
                ("activated_at", models.DateTimeField(blank=True, null=True)),
                ("superseded_at", models.DateTimeField(blank=True, null=True)),
                ("failed_at", models.DateTimeField(blank=True, null=True)),
                ("initiator_ref", models.CharField(blank=True, max_length=128)),
                ("request_provenance", models.JSONField(blank=True, default=dict)),
                ("webhook_delivery_id", models.CharField(blank=True, max_length=128)),
                ("sync_request_id", models.CharField(blank=True, max_length=128)),
                ("document_count", models.PositiveIntegerField(default=0)),
                ("relation_count", models.PositiveIntegerField(default=0)),
                ("asset_count", models.PositiveIntegerField(default=0)),
                ("warning_count", models.PositiveIntegerField(default=0)),
                ("warnings", models.JSONField(blank=True, default=list)),
                ("structured_errors", models.JSONField(blank=True, default=list)),
                ("search_build_id", models.CharField(blank=True, max_length=128, null=True)),
                ("graph_build_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "asset_manifest_checksum",
                    models.CharField(
                        blank=True,
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                (
                    "public_contracts_sha256",
                    models.CharField(
                        default="50f875806217865ef35b74f58ed885c4b5c832284391dbea7f84344d3416f66d",
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "based_on_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="based_candidates",
                        to="content.contentrelease",
                    ),
                ),
            ],
            options={
                "ordering": ("source_id", "-sequence"),
            },
        ),
        migrations.CreateModel(
            name="ContentDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content_kind", models.CharField(max_length=64)),
                ("stable_key", models.CharField(max_length=255)),
                ("source_path", models.CharField(max_length=1024)),
                (
                    "checksum",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("source_created_at", models.DateTimeField(blank=True, null=True)),
                ("source_modified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "exact_public_path",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        validators=[content.models.validate_exact_public_path],
                    ),
                ),
                ("slug", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=512)),
                ("summary", models.TextField(blank=True)),
                ("canonical_url", models.URLField(blank=True, max_length=2048)),
                ("seo_title", models.CharField(blank=True, max_length=512)),
                ("seo_description", models.TextField(blank=True)),
                ("seo_image_url", models.URLField(blank=True, max_length=2048)),
                ("raw_frontmatter", models.JSONField(blank=True, default=dict)),
                ("raw_body", models.TextField(blank=True)),
                ("rendered_html", models.TextField(blank=True)),
                ("normalized_text", models.TextField(blank=True)),
                ("adapter_metadata", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(default=False)),
                ("noindex", models.BooleanField(default=False)),
                ("edit_url", models.URLField(blank=True, max_length=2048)),
                ("contract_id", models.CharField(blank=True, max_length=64, null=True)),
                ("contract_source_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "contract_source_revision",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="content.contentrelease",
                    ),
                ),
            ],
            options={
                "ordering": ("release_id", "content_kind", "stable_key"),
            },
        ),
        migrations.CreateModel(
            name="ContentAsset",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("source_path", models.CharField(max_length=1024)),
                (
                    "stable_public_path",
                    models.CharField(
                        max_length=2048, validators=[content.models.validate_exact_public_path]
                    ),
                ),
                (
                    "storage_key",
                    models.CharField(
                        max_length=2048, validators=[content.models.validate_storage_key_shape]
                    ),
                ),
                ("content_type", models.CharField(max_length=255)),
                ("size", models.PositiveBigIntegerField()),
                (
                    "checksum",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("contract_id", models.CharField(blank=True, max_length=64, null=True)),
                ("contract_source_id", models.CharField(blank=True, max_length=128, null=True)),
                (
                    "contract_source_revision",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        null=True,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                            )
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assets",
                        to="content.contentrelease",
                    ),
                ),
            ],
            options={
                "ordering": ("release_id", "stable_public_path"),
            },
        ),
        migrations.CreateModel(
            name="ContentSource",
            fields=[
                ("revision", models.PositiveBigIntegerField(default=1)),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("stable_id", models.SlugField(max_length=128)),
                ("display_name", models.CharField(max_length=255)),
                ("repository_owner", models.CharField(max_length=128)),
                ("repository_name", models.CharField(max_length=128)),
                ("branch", models.CharField(max_length=255)),
                ("path_allowlist", models.JSONField(blank=True, default=list)),
                ("adapter_type", models.CharField(max_length=64)),
                (
                    "mount_path",
                    models.CharField(
                        max_length=512, validators=[content.models.validate_exact_public_path]
                    ),
                ),
                ("enabled", models.BooleanField(default=False)),
                ("max_files", models.PositiveIntegerField(default=10000)),
                ("max_bytes", models.PositiveBigIntegerField(default=100000000)),
                (
                    "last_successful_commit",
                    models.CharField(
                        blank=True,
                        max_length=40,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{40}$", "Enter a full lowercase Git SHA."
                            )
                        ],
                    ),
                ),
                ("last_webhook_at", models.DateTimeField(blank=True, null=True)),
                ("last_reconciled_at", models.DateTimeField(blank=True, null=True)),
                ("sync_locked_at", models.DateTimeField(blank=True, null=True)),
                ("pending_follow_up", models.BooleanField(default=False)),
                ("freshness_target_minutes", models.PositiveIntegerField(default=60)),
                (
                    "secret_reference",
                    models.CharField(
                        blank=True,
                        max_length=255,
                        validators=[content.models.validate_secret_reference],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "active_release",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_for_sources",
                        to="content.contentrelease",
                    ),
                ),
            ],
            options={
                "ordering": ("stable_id",),
            },
        ),
        migrations.AddField(
            model_name="contentrelease",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="releases",
                to="content.contentsource",
            ),
        ),
        migrations.CreateModel(
            name="ContentRelation",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("relation_type", models.CharField(max_length=64)),
                ("target_kind", models.CharField(max_length=64)),
                ("target_key", models.CharField(max_length=255)),
                (
                    "resolved_public_path",
                    models.CharField(
                        blank=True,
                        max_length=2048,
                        null=True,
                        validators=[content.models.validate_exact_public_path],
                    ),
                ),
                ("label", models.CharField(blank=True, max_length=512)),
                ("order", models.PositiveIntegerField(default=0)),
                ("timestamp_seconds", models.PositiveIntegerField(blank=True, null=True)),
                ("is_required", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "resolved_target_document",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="incoming_relations",
                        to="content.contentdocument",
                    ),
                ),
                (
                    "source_document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="relations",
                        to="content.contentdocument",
                    ),
                ),
            ],
            options={
                "ordering": ("source_document_id", "relation_type", "order"),
                "indexes": [
                    models.Index(
                        fields=["target_kind", "target_key"], name="content_relation_target"
                    ),
                    models.Index(
                        fields=["resolved_public_path"], name="content_relation_public_path"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source_document", "relation_type", "order"),
                        name="content_relation_order_uq",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("resolved_target_document__isnull", False),
                            ("resolved_public_path__isnull", False),
                            _negated=True,
                        ),
                        name="content_relation_resolution_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("is_required", False),
                            ("resolved_target_document__isnull", False),
                            ("resolved_public_path__isnull", False),
                            _connector="OR",
                        ),
                        name="content_relation_required_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("order__gte", 0)), name="content_relation_order_ck"
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="contentdocument",
            index=models.Index(
                fields=["exact_public_path", "release"], name="content_document_exact_path"
            ),
        ),
        migrations.AddIndex(
            model_name="contentdocument",
            index=models.Index(
                fields=["source_path", "release"], name="content_document_source_path"
            ),
        ),
        migrations.AddIndex(
            model_name="contentdocument",
            index=models.Index(
                fields=["content_kind", "stable_key"], name="content_document_kind_key"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentdocument",
            constraint=models.UniqueConstraint(
                fields=("release", "content_kind", "stable_key"), name="content_doc_stable_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("exact_public_path__isnull", False)),
                fields=("release", "exact_public_path"),
                name="content_doc_release_path_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentdocument",
            constraint=models.UniqueConstraint(
                condition=models.Q(("contract_id__isnull", False)),
                fields=("release", "contract_id"),
                name="content_doc_contract_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentdocument",
            constraint=models.CheckConstraint(
                condition=models.Q(("checksum__regex", "^[0-9a-f]{64}$")),
                name="content_doc_checksum_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentdocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("exact_public_path__isnull", True),
                    models.Q(
                        ("exact_public_path__startswith", "/"),
                        models.Q(("exact_public_path__startswith", "//"), _negated=True),
                        models.Q(("exact_public_path__contains", "?"), _negated=True),
                        models.Q(("exact_public_path__contains", "#"), _negated=True),
                    ),
                    _connector="OR",
                ),
                name="content_doc_exact_path_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentdocument",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("contract_id__isnull", True),
                        ("contract_source_id__isnull", True),
                        ("contract_source_revision__isnull", True),
                    ),
                    models.Q(
                        ("contract_id__isnull", False),
                        ("contract_source_id__isnull", False),
                        ("contract_source_revision__regex", "^[0-9a-f]{40}$"),
                    ),
                    _connector="OR",
                ),
                name="content_doc_provenance_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="contentasset",
            index=models.Index(
                fields=["stable_public_path", "release"], name="content_asset_public_path"
            ),
        ),
        migrations.AddIndex(
            model_name="contentasset",
            index=models.Index(fields=["source_path", "release"], name="content_asset_source_path"),
        ),
        migrations.AddConstraint(
            model_name="contentasset",
            constraint=models.UniqueConstraint(
                fields=("storage_key",), name="content_asset_storage_key_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentasset",
            constraint=models.UniqueConstraint(
                fields=("release", "source_path"), name="content_asset_source_path_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentasset",
            constraint=models.UniqueConstraint(
                fields=("release", "stable_public_path"), name="content_asset_public_path_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentasset",
            constraint=models.UniqueConstraint(
                condition=models.Q(("contract_id__isnull", False)),
                fields=("release", "contract_id"),
                name="content_asset_contract_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("checksum__regex", "^[0-9a-f]{64}$")),
                name="content_asset_checksum_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentasset",
            constraint=models.CheckConstraint(
                condition=models.Q(("size__gte", 0)), name="content_asset_size_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("stable_public_path__startswith", "/"),
                    models.Q(("stable_public_path__startswith", "//"), _negated=True),
                    models.Q(("stable_public_path__contains", "?"), _negated=True),
                    models.Q(("stable_public_path__contains", "#"), _negated=True),
                ),
                name="content_asset_public_path_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentasset",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("contract_id__isnull", True),
                        ("contract_source_id__isnull", True),
                        ("contract_source_revision__isnull", True),
                    ),
                    models.Q(
                        ("contract_id__isnull", False),
                        ("contract_source_id__isnull", False),
                        ("contract_source_revision__regex", "^[0-9a-f]{40}$"),
                    ),
                    _connector="OR",
                ),
                name="content_asset_provenance_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="contentsource",
            index=models.Index(fields=["enabled", "stable_id"], name="content_source_enabled_id"),
        ),
        migrations.AddIndex(
            model_name="contentsource",
            index=models.Index(
                fields=["repository_owner", "repository_name", "branch"],
                name="content_source_repository",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.UniqueConstraint(
                fields=("stable_id",), name="content_source_stable_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("repository_owner"),
                django.db.models.functions.text.Lower("repository_name"),
                django.db.models.functions.text.Lower("branch"),
                name="content_source_repo_branch_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="content_source_revision_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_files__gte", 1)), name="content_source_files_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("max_bytes__gte", 1)), name="content_source_bytes_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("freshness_target_minutes__gte", 1)),
                name="content_source_freshness_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("last_successful_commit", ""),
                    ("last_successful_commit__regex", "^[0-9a-f]{40}$"),
                    _connector="OR",
                ),
                name="content_source_success_sha_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("stable_id__regex", "^[a-z0-9][a-z0-9._-]{0,127}$")),
                name="content_source_stable_shape_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("repository_owner__regex", "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
                ),
                name="content_source_repo_owner_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("repository_name__regex", "^[A-Za-z0-9][A-Za-z0-9._-]{0,127}$")
                ),
                name="content_source_repo_name_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentsource",
            constraint=models.CheckConstraint(
                condition=models.Q(("branch__regex", "^[A-Za-z0-9][A-Za-z0-9._/-]{0,254}$")),
                name="content_source_branch_ck",
            ),
        ),
        migrations.AddIndex(
            model_name="contentrelease",
            index=models.Index(
                fields=["source", "status", "-sequence"], name="content_release_state_seq"
            ),
        ),
        migrations.AddIndex(
            model_name="contentrelease",
            index=models.Index(fields=["status", "-sequence"], name="content_release_status_seq"),
        ),
        migrations.AddIndex(
            model_name="contentrelease",
            index=models.Index(fields=["commit_sha"], name="content_release_commit"),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.UniqueConstraint(
                fields=("source", "sequence"), name="content_release_source_seq_uq"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.UniqueConstraint(
                fields=("source", "commit_sha", "parser_version", "rendering_version"),
                name="content_release_build_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("source",),
                name="content_release_one_active_uq",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(("revision__gte", 1)), name="content_release_revision_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(("sequence__gte", 1)), name="content_release_sequence_ck"
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(("commit_sha__regex", "^[0-9a-f]{40}$")),
                name="content_release_commit_sha_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("asset_manifest_checksum", ""),
                    ("asset_manifest_checksum__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="content_release_manifest_sha_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "public_contracts_sha256",
                        "50f875806217865ef35b74f58ed885c4b5c832284391dbea7f84344d3416f66d",
                    )
                ),
                name="content_release_contract_sha_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("document_count__gte", 0),
                    ("relation_count__gte", 0),
                    ("asset_count__gte", 0),
                    ("warning_count__gte", 0),
                ),
                name="content_release_counts_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("status__in", ("ready", "active", "superseded")), _negated=True),
                    ("asset_manifest_checksum__regex", "^[0-9a-f]{64}$"),
                    _connector="OR",
                ),
                name="content_release_ready_sha_ck",
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(
                        ("activated_at__isnull", True),
                        ("failed_at__isnull", True),
                        ("fetched_at__isnull", True),
                        ("status", "queued"),
                        ("superseded_at__isnull", True),
                        ("validated_at__isnull", True),
                    ),
                    models.Q(
                        ("activated_at__isnull", True),
                        ("failed_at__isnull", True),
                        ("fetched_at__isnull", True),
                        ("status", "fetching"),
                        ("superseded_at__isnull", True),
                        ("validated_at__isnull", True),
                    ),
                    models.Q(
                        ("activated_at__isnull", True),
                        ("failed_at__isnull", True),
                        ("fetched_at__isnull", False),
                        ("status", "validating"),
                        ("superseded_at__isnull", True),
                        ("validated_at__isnull", True),
                    ),
                    models.Q(
                        ("activated_at__isnull", True),
                        ("failed_at__isnull", True),
                        ("fetched_at__isnull", False),
                        ("status", "ready"),
                        ("superseded_at__isnull", True),
                        ("validated_at__isnull", False),
                    ),
                    models.Q(
                        ("activated_at__isnull", False),
                        ("failed_at__isnull", True),
                        ("fetched_at__isnull", False),
                        ("status", "active"),
                        ("superseded_at__isnull", True),
                        ("validated_at__isnull", False),
                    ),
                    models.Q(
                        ("activated_at__isnull", False),
                        ("failed_at__isnull", True),
                        ("fetched_at__isnull", False),
                        ("status", "superseded"),
                        ("superseded_at__isnull", False),
                        ("validated_at__isnull", False),
                    ),
                    models.Q(
                        ("activated_at__isnull", True),
                        ("failed_at__isnull", True),
                        ("fetched_at__isnull", False),
                        ("status", "invalid"),
                        ("superseded_at__isnull", True),
                        ("validated_at__isnull", False),
                    ),
                    models.Q(
                        ("activated_at__isnull", True),
                        ("failed_at__isnull", False),
                        ("status", "failed"),
                        ("superseded_at__isnull", True),
                        ("validated_at__isnull", True),
                    ),
                    _connector="OR",
                ),
                name="content_release_timestamps_ck",
            ),
        ),
        migrations.RunPython(install_postgres_guards, remove_postgres_guards),
    ]
