# Generated by Django 6.0.7 on 2026-08-09 05:13

import hashlib

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import content.migration_validators


def backfill_active_content_paths(apps, schema_editor):
    using = schema_editor.connection.alias
    ContentSource = apps.get_model("content", "ContentSource")
    ContentRelease = apps.get_model("content", "ContentRelease")
    ContentDocument = apps.get_model("content", "ContentDocument")
    ContentAsset = apps.get_model("content", "ContentAsset")
    ActiveContentPath = apps.get_model("content", "ActiveContentPath")

    claims = {}
    sources = ContentSource.objects.using(using).filter(
        enabled=True,
        active_release_id__isnull=False,
    )
    for source in sources.iterator():
        release = ContentRelease.objects.using(using).get(
            pk=source.active_release_id,
            source_id=source.pk,
        )
        if release.status != "active":
            raise RuntimeError("active content source points at a non-active release")
        paths = set(
            ContentDocument.objects.using(using)
            .filter(release_id=release.pk, exact_public_path__isnull=False)
            .values_list("exact_public_path", flat=True)
        ) | set(
            ContentAsset.objects.using(using)
            .filter(release_id=release.pk)
            .values_list("stable_public_path", flat=True)
        )
        for path in paths:
            digest = hashlib.sha256(path.encode("utf-8")).hexdigest()
            existing = claims.get(digest)
            if existing is not None and (
                existing.exact_public_path != path or existing.source_id != source.pk
            ):
                raise RuntimeError("enabled active content paths are not globally unique")
            claims[digest] = ActiveContentPath(
                path_digest=digest,
                exact_public_path=path,
                source_id=source.pk,
                release_id=release.pk,
            )
    ActiveContentPath.objects.using(using).bulk_create(
        [claims[digest] for digest in sorted(claims)]
    )


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ActiveContentPath",
            fields=[
                (
                    "path_digest",
                    models.CharField(
                        max_length=64,
                        primary_key=True,
                        serialize=False,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                (
                    "exact_public_path",
                    models.CharField(
                        max_length=2048,
                        validators=[content.migration_validators.validate_exact_public_path],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "release",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_path_claims",
                        to="content.contentrelease",
                    ),
                ),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="active_path_claims",
                        to="content.contentsource",
                    ),
                ),
            ],
            options={
                "ordering": ("exact_public_path",),
                "indexes": [
                    models.Index(fields=["source", "release"], name="content_active_path_owner"),
                    models.Index(fields=["release"], name="content_active_path_release"),
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(("path_digest__regex", "^[0-9a-f]{64}$")),
                        name="content_active_path_digest_ck",
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("exact_public_path__startswith", "/"),
                            models.Q(("exact_public_path__startswith", "//"), _negated=True),
                            models.Q(("exact_public_path__contains", "?"), _negated=True),
                            models.Q(("exact_public_path__contains", "#"), _negated=True),
                        ),
                        name="content_active_path_shape_ck",
                    ),
                ],
            },
        ),
        migrations.RunPython(
            backfill_active_content_paths,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
