# Generated by Django 6.0.8 on 2026-09-03 18:40

from django.db import migrations


class Migration(migrations.Migration):
    """Drop fields confirmed write-only across the whole codebase.

    ``ContentSource.secret_reference`` and ``last_successful_commit`` are set
    on write but never read back (the fetch pipeline is unauthenticated and
    public-repo-only; nothing consults the last-activated commit).
    ``ContentDocument.normalized_text`` is written on every row but the
    published-document query projection deliberately excludes it, and nothing
    else reads it. ``ContentRelease.webhook_delivery_id``, ``sync_request_id``,
    and ``initiator_ref`` are write-only provenance: the real webhook/pull
    pipelines never populate the first two, and actor attribution is already
    captured durably by the generic audit-event log, making ``initiator_ref``
    a redundant duplicate rather than a needed audit hook.
    """

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentsource',
            name='content_source_success_sha_ck',
        ),
        migrations.RemoveField(
            model_name='contentdocument',
            name='normalized_text',
        ),
        migrations.RemoveField(
            model_name='contentrelease',
            name='initiator_ref',
        ),
        migrations.RemoveField(
            model_name='contentrelease',
            name='sync_request_id',
        ),
        migrations.RemoveField(
            model_name='contentrelease',
            name='webhook_delivery_id',
        ),
        migrations.RemoveField(
            model_name='contentsource',
            name='last_successful_commit',
        ),
        migrations.RemoveField(
            model_name='contentsource',
            name='secret_reference',
        ),
    ]
