# Generated by Django 6.0.8 on 2026-09-05 08:19

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_remove_content_write_only_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleFaqSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(help_text='The article slug this FAQ section belongs to.', max_length=200, unique=True)),
                ('heading_id', models.CharField(help_text='The article heading the FAQ section answers to.', max_length=200)),
                ('block_index', models.PositiveIntegerField(help_text='Split point inside the article body: blocks before it render above the FAQ.')),
                ('source_path', models.CharField(help_text="Legacy data file the pairs were recovered from, e.g. '_data/faqs/<key>.yml'.", max_length=512)),
                ('source_sha256', models.CharField(help_text='Digest of the legacy source file at import time.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('article_source_path', models.CharField(help_text="Article source inside DataTalksClub/content, e.g. 'articles/<slug>.md'.", max_length=512)),
                ('article_source_sha256', models.CharField(help_text='Digest of the article source at import time.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('blocks_sha256', models.CharField(help_text='Digest of the projected article blocks the section was bound to.', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('slug',),
                'constraints': [models.CheckConstraint(condition=models.Q(('slug__regex', '^[a-z0-9][a-z0-9-]*$')), name='content_articlefaq_slug_ck'), models.CheckConstraint(condition=models.Q(('block_index__gte', 1)), name='content_articlefaq_block_index_ck'), models.CheckConstraint(condition=models.Q(('source_sha256__regex', '^[0-9a-f]{64}$')), name='content_articlefaq_source_sha_ck'), models.CheckConstraint(condition=models.Q(('article_source_sha256__regex', '^[0-9a-f]{64}$')), name='content_articlefaq_article_sha_ck'), models.CheckConstraint(condition=models.Q(('blocks_sha256__regex', '^[0-9a-f]{64}$')), name='content_articlefaq_blocks_sha_ck')],
            },
        ),
        migrations.CreateModel(
            name='ArticleFaqQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveIntegerField(help_text='Order inside the section; lower positions render first.')),
                ('anchor_id', models.CharField(help_text="Stable fragment for the question, e.g. 'faq-<slug>'.", max_length=84)),
                ('question', models.CharField(max_length=500)),
                ('answer_markdown', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='content.articlefaqsection')),
            ],
            options={
                'ordering': ('position', 'id'),
                'indexes': [models.Index(fields=['section', 'position'], name='content_articlefaq_read_idx')],
                'constraints': [models.UniqueConstraint(fields=('section', 'anchor_id'), name='content_articlefaq_question_anchor_uq'), models.UniqueConstraint(fields=('section', 'position'), name='content_articlefaq_question_position_uq'), models.CheckConstraint(condition=models.Q(('anchor_id__regex', '^faq-[a-z0-9][a-z0-9-]*$')), name='content_articlefaq_anchor_ck')],
            },
        ),
    ]
