# Generated by Django 6.0.8 on 2026-09-12 08:50

import uuid

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models

import content.migration_validators


class Migration(migrations.Migration):
    dependencies = [
        ("cb_content_sync", "0001_initial"),
        ("content", "0002_remove_content_write_only_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="SyncedDocument",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("content_kind", models.CharField(max_length=64)),
                ("stable_key", models.CharField(max_length=255)),
                ("slug", models.CharField(blank=True, max_length=255)),
                ("title", models.CharField(max_length=512)),
                ("summary", models.TextField(blank=True)),
                (
                    "public_path",
                    models.CharField(
                        max_length=2048,
                        validators=[content.migration_validators.validate_exact_public_path],
                    ),
                ),
                ("source_path", models.CharField(max_length=1024)),
                (
                    "checksum",
                    models.CharField(
                        max_length=64,
                        validators=[
                            django.core.validators.RegexValidator(
                                "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                            )
                        ],
                    ),
                ),
                ("record", models.JSONField(blank=True, default=dict)),
                ("is_published", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "source",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="synced_documents",
                        to="cb_content_sync.contentsource",
                    ),
                ),
            ],
            options={
                "ordering": ("content_kind", "stable_key"),
                "indexes": [
                    models.Index(
                        fields=["content_kind", "public_path"], name="synced_document_kind_path"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("source", "content_kind", "stable_key"),
                        name="synced_document_source_key_uq",
                    ),
                    models.UniqueConstraint(
                        fields=("source", "public_path"), name="synced_document_source_path_uq"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(("checksum__regex", "^[0-9a-f]{64}$")),
                        name="synced_document_checksum_ck",
                    ),
                ],
            },
        ),
    ]
