# Generated by Django 6.0.7 on 2026-08-09 07:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0002_active_content_path_claims"),
    ]

    operations = [
        migrations.AddField(
            model_name="contentdocument",
            name="raw_structured_data",
            field=models.TextField(blank=True),
        ),
    ]
