# Generated by Django 6.0.8 on 2026-09-16 11:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_synceddocument'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='contentrelease',
            name='content_release_contract_sha_ck',
        ),
        migrations.AlterField(
            model_name='contentrelease',
            name='public_contracts_sha256',
            field=models.CharField(default='a9f435476325cbb0e1bc573d1ec991dda6ea9bc08764fce8c7e27b9d5209f792', max_length=64, validators=[django.core.validators.RegexValidator('^[0-9a-f]{64}$', 'Enter a lowercase SHA-256 digest.')]),
        ),
        migrations.AddConstraint(
            model_name='contentrelease',
            constraint=models.CheckConstraint(condition=models.Q(('public_contracts_sha256__in', ('a9f435476325cbb0e1bc573d1ec991dda6ea9bc08764fce8c7e27b9d5209f792', '31f505350566bfcde0a30109dadcfb3565042fd395b4c1bd151966f94d361332', '50f875806217865ef35b74f58ed885c4b5c832284391dbea7f84344d3416f66d'))), name='content_release_contract_sha_ck'),
        ),
    ]
