# Generated by Django 6.0.8 on 2026-08-21 23:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("content", "0003_content_document_structured_data"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="contentrelease",
            name="content_release_contract_sha_ck",
        ),
        migrations.AlterField(
            model_name="contentrelease",
            name="public_contracts_sha256",
            field=models.CharField(
                default="31f505350566bfcde0a30109dadcfb3565042fd395b4c1bd151966f94d361332",
                max_length=64,
                validators=[
                    django.core.validators.RegexValidator(
                        "^[0-9a-f]{64}$", "Enter a lowercase SHA-256 digest."
                    )
                ],
            ),
        ),
        migrations.AddConstraint(
            model_name="contentrelease",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "public_contracts_sha256",
                        "31f505350566bfcde0a30109dadcfb3565042fd395b4c1bd151966f94d361332",
                    )
                ),
                name="content_release_contract_sha_ck",
            ),
        ),
    ]
