# Generated by Django 6.0.8 on 2026-09-16 22:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_remove_contentrelease_content_release_contract_sha_ck_and_more'),
        ('events', '0003_provisional_integration_attempt'),
    ]

    operations = [
        migrations.CreateModel(
            name='EventSource',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('repository', models.CharField(max_length=255)),
                ('revision', models.CharField(max_length=64)),
                ('source_key', models.CharField(max_length=512)),
                ('source_path', models.CharField(default='', max_length=512)),
                ('source_checksum', models.CharField(default='', max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='source_identity', to='events.event')),
            ],
            options={
                'ordering': ('source_key', 'id'),
                'constraints': [models.UniqueConstraint(fields=('repository', 'revision', 'source_key'), name='content_event_source_identity_unique'), models.CheckConstraint(condition=models.Q(('repository__gt', ''), ('revision__gt', ''), ('source_key__gt', '')), name='content_event_source_identity_nonempty')],
            },
        ),
    ]
